### ISSUE TITLE
missing intercom entity

### ISSUE THREAD

**Issue by RoLiFru** [JoDehli/PyLoxone#102]
First of all, thank you for the great binding. I was able to bind all my entities except for the intercom. I am using Loxone gen. 1 server and HA does not show any intercom entity. Also, since I am running HA in SSL, I am unable to display the intercom camera in an iframe (the lox video stream is http only). Also the approach to create a custom sensor did not work: I read the LoxApp3.json and found the intercom, but not really a UUID-id for the intercom-camera and therefore got nowhere.
Any tips on how to tie the intercom camera to HA would be greatly appreciated!

**Comment by JoDehli** [comment]
I think the intercom is handled differently. Am I right intercom is a video door bell? Have you tried all the ports which are documented in this document 
 https://www.loxone.com/dede/wp-content/uploads/sites/2/2021/10/Loxone-Required-Ports-Domains.pdf

I found only the German documentation.

**Comment by RoLiFru** [comment]
many thanks for your fast reply! You are right, intercom is the original Loxone video door bell. I will give the UDP ports 8110 and 8111 shown in the document you linked a try later this afternoon.

**Comment by RoLiFru** [comment]
Unfortunately, even after forwarding the ports 8110 and 8111 to my HA, the intercom was not detected. If anybody found a way to integrate the intercom, please share. Adding the videostream was not possible because the internal stream is http (as described in my first post) and the external stream can only be accessed by the loxone app itself, as I just learned from Loxone: "Aus Sicherheitsgründen ist das direkte externe Zugreifen auf den Videostream der Intercom über einen Browser leider nicht möglich."

**Comment by JoDehli** [comment]
@RoLiFru I think I can close this issue. This is no problem of the integration itself. 

I found an thread maybe this is helpful for you: 

https://www.loxforum.com/forum/german/software-konfiguration-programm-und-visualisierung/19333-loxone-intercom-externe-video-%C3%BCbertragung
