### ISSUE TITLE
Music Server - add an audiozone to Home Assistant?

### ISSUE THREAD

**Issue by DSew20** [JoDehli/PyLoxone#105]
Hello - brilliant plugin for Home Assistant.

I don't think this is an issue, but I can not add nor find any instructions on how to add a Loxone Music Server zone to Home Assistant via this plugin.

Is this possible?  Any tips on how to get Home Assistant to see and control the zones with the Media Player?

Regards, DS

**Comment by JoDehli** [comment]
![image](https://user-images.githubusercontent.com/32484282/156812839-d897e1c5-12f3-4137-aaee-96abfef83140.png)

**Comment by DSew20** [comment]
Just in case it helps anyone else - I discovered (by accident) that Loxone Music Zones can be added to Home Assistant through the Squeezebox integration.  Works perfectly well.

**Comment by JoDehli** [comment]
If you want you can describe it and add it in the documentation by makeing a pull request.

**Comment by elRadix** [comment]
> Just in case it helps anyone else - I discovered (by accident) that Loxone Music Zones can be added to Home Assistant through the Squeezebox integration. Works perfectly well.

@DSew20 
can you please share how managed to install it and control the player?

**Comment by tamunave** [comment]
I'm also looking for a direct way to control the audio server (the purple one!) from HA.

For now I've managed to Macgyver it:

![afbeelding](https://user-images.githubusercontent.com/25452661/177172239-955fdd35-892f-4172-90a5-b3600dbb6e1a.png)

How to:
- 2 outputs for the states
> 
![afbeelding](https://user-images.githubusercontent.com/25452661/177172394-447b6041-1279-49cf-9f10-d873f71166ed.png)

- the buttons control  scenes I've made in Loxone
 > 
![afbeelding](https://user-images.githubusercontent.com/25452661/177172582-8c236030-1b7a-46ee-a0d4-fcffdd798075.png)
> 
![afbeelding](https://user-images.githubusercontent.com/25452661/177172630-674a2556-802e-4e43-ae2c-58f4189457a1.png)
> 
![afbeelding](https://user-images.githubusercontent.com/25452661/177172664-3baf0875-0732-48c8-b42a-b468004b574f.png)

The card in HA

`
 - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: entity
            entity: sensor.playing_leefriumte
            icon: mdi:music
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            icon: mdi:pause
            show_state: false
            entity: switch.leefruimte_pauze
      - type: horizontal-stack
        cards:
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.leefruimte_vol_2
            icon: mdi:volume-minus
            show_state: false
          - type: custom:bignumber-card
            entity: sensor.volume_leefruimte
            scale: 35px
            color: white
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.leefruimte_vol
            icon: mdi:volume-plus
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.leefruimte_mnm
            name: MNM
            show_icon: false
          - type: custom:button-card
            entity: switch.leefruimte_qmusic
            name: Q-Music
            show_icon: false
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.leefruimte_mnm_hits
            name: MNM Hits
            show_icon: false
          - type: custom:button-card
            entity: switch.leefruimte_mnm_throwback
            name: MNM Throwback
            show_icon: false
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.leefruimte_joe_80_90
            name: Joe 80's & 90's
            show_icon: false
          - type: custom:button-card
            entity: switch.leefruimte_radio_2
            name: Radio 2
            show_icon: false
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.leefruimte_one_world_radio
            name: One World Radio
            show_icon: false
          - type: custom:button-card
            entity: switch.leefruimte_topradio
            name: Topradio
            show_icon: false
`

**Comment by maaso** [comment]
Did anyone ever figure out how to add the zones via the Squeezebox integration that @DSew20 mentioned?

**Comment by NicoDeBelder** [comment]
@maaso Nope, I gave up on the purple audio server, I found nothing in the API besides my hacky solution above.
I've sold my audio server, bought a second hand Loxone amplifier and deployed a self brew docker container with LMS and squeezelite. 
It works great with HA, only downside is the start time for the amplifier when going to sleep.
The doorbell sound starts after like 1-2 seconds, i should look into the trigger function to see if it speeds up the wake-up.

**Comment by maaso** [comment]
Yeah, I've hacked together something with LMS and the Airplay plugin, so I'm using LMS -> Airplay -> Loxone Audio Zone. LMS also has the Spotty plugin enabled for Spotify Connect, and I disabled the Spotify Connect on the Audioserver. I then integrated the LMS players into HA with the Squeezebox (LMS) integration. 

Music played via Spotify Connect is picked up by HA perfectly; downside is that if someone plays audio from the Loxone app, I get no info at all in HA since it bypasses my intermediary LMS. The Loxone app is kinda meh though, so maybe I can convince my users to switch to the HA app :)

**Comment by tamunave** [comment]
@maaso 
Oops, I've used the wrong account in my post above ;)
The Loxone app is better than before, but I've never really used it. 
All GUI (and some automations) is done by HA in my setup. I kinda only use Loxone as fancy relays and 24V light control.
