### ISSUE TITLE
Since HA 2022.3 Loxone switches doesn't work

### ISSUE THREAD

**Issue by funbirdcas** [JoDehli/PyLoxone#106]
Hi,

I'm using Loxone switches to control non Loxone lights.

Therefore the Loxone switches are available as sensors in HA and trigger an automation.
But HA doesn't notice anymore when I touching the switch ?

Surprisingly, I can easily control Loxone sockets via HA.
Also reading out Loxone temperature sensors work fine in HA.

Any ideas ?

**Comment by JoDehli** [comment]
Need more info. Which loxone element do you want to switch? A light or a switch? 

Do you use a light controller?

**Comment by funbirdcas** [comment]
Hi @JoDehli 

I have got a Loxone Touch Air.
In Loxone Config I just say "Visualisation activated" for the desired buttons.

There is no light controller involved.

The PyLoxone integration finds automatically the buttons as sensors.

example:

`uuid: 17c3ae03-01db-40a1-ffffa43bf43e2d6e
device_typ: digital_sensor
platform: loxone
category: Bedienelemente
friendly_name: wo-Schalter-TI5`

This sensor is me trigger for a light

`alias: Loxone Taster 5 Wohnzimmer
description: ''
trigger:
  - platform: state
    to: An
    entity_id: sensor.wo_schalter_ti5
condition: []
action:
  - type: toggle
    device_id: 9613b807a62f19a4112a23d394a02d78
    entity_id: light.backlight
    domain: light
mode: single`

This worked befor I updated HA to 2022.3.
Nothing changed on Loxone side.

**Comment by JoDehli** [comment]
And what is the light? What type? I mean which type in loxone?

**Comment by funbirdcas** [comment]
Hi @JoDehli 

the light is zigbee Ikea Device, controlled by Deconz Integration

**Comment by JoDehli** [comment]
Is the state On on An if you trigger the switch. Because there was a change on the naming on the state. Maybe you have to change to on as a trigger. You can look in the developer tools under states.

**Comment by funbirdcas** [comment]
Hey @JoDehli 

you're right !

When I change the trigger value  from "An" to "on" the automation comes back in service.

Thanks a lot for your quick help!
