### ISSUE TITLE
Error during start

### ISSUE THREAD

**Issue by tanker11** [JoDehli/PyLoxone#11]
Hello,

I really love your binding to Loxone, it is very promising.
Based on the instructions I successfully installed the latest version and it seems working, almost...
I can see some (only 2-3) items from Loxone project under HA, but not more.
I checked the logs and can see two related messages:

1.)
Error while setting up platform loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/loxone/switch.py", line 33, in async_setup_platform
    room=get_room_name_from_room_uuid(loxconfig, push_button['room']),
KeyError: 'room'

2.)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/loxone/sensor.py", line 89, in event_handler
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 418, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'

Do you have any idea what the problem could be?
Thanks in advance.

**Comment by noocyte** [comment]
I'm getting the same error... I'm not 100% sure that I copied the files correctly either to be honest... I do not understand where the www folder is supposed to go...

**Comment by JoDehli** [comment]
I found the mistake. It was when the category or the room was not defined. In my config 
I defined everything that was why I had no problems. 

Please download the newest version. 

@noocyte:
the www is exactly at the same directory where the "custom_components" folder is located.
you only need it when you want to use the custom loxone cover which only has a position in percent
and a switch for the shading. 
It looks like this:
![grafik](https://user-images.githubusercontent.com/32484282/72554465-08fb6180-389b-11ea-9f85-c2d11f1e8239.png)

Can some give me feedback if it is working. Then I close this issue. 

Jojo

**Comment by tanker11** [comment]
Hi Jojo,

Thanks for the fix, it imports seemingly all my entities from Loxone project.
Only some covers are not imported, though...
I have 2 in one room, 2 in the other, and only 1-1 imported.

**Comment by JoDehli** [comment]
Can you provide a error log? 
Do you see this covers in the original app?

**Comment by tanker11** [comment]
I'm not sure which log you mean, as the one under Developer Tools->Log does not show much.
Only the following:
2020-01-17 10:37:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for loxone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-17 10:37:46 WARNING (MainThread) [homeassistant.setup] Setup of loxone is taking over 10 seconds.

The two covers imported in the new are exactly the same imported in the older version.

**Comment by noocyte** [comment]
> Can some give me feedback if it is working. Then I close this issue.

Perfect! Thank you so very much! :)

**Comment by tanker11** [comment]
Hello,

I have written that except covers it works.

Jarle Nygård <notifications@github.com> ezt írta (időpont: 2020. jan. 17.,
Pén 15:55):

**Comment by tanker11** [comment]
Sorry, missed the quotation.


Jarle Nygård <notifications@github.com> ezt írta (időpont: 2020. jan. 17.,
Pén 15:55):

**Comment by JoDehli** [comment]
@tanker11:
I do not really understand what you mean. As I understood everything works except of 2 covers.
Is that right? 
Do you see this covers in the orginal app from loxone? Because you mark is as to "use" otherwise
it is not visible for apps and third party bindings.

**Comment by tanker11** [comment]
Everything works, except that only two covers are visible only. :)
All covers are set to 'use' in Loxconfig, so displayed normally on my
Loxone interface.

Let me know what info I could collect or check.

Joachim <notifications@github.com> ezt írta (időpont: 2020. jan. 17., Pén
17:22):

**Comment by JoDehli** [comment]
Ok we can try to find the mistake. But I need more formation. 

First of all define a room and a category for this covers and try it again. 
Only for testing purpose. 

When you have more covers and you have covers they show up and some not 
are they from a different kind. For example are some from type automatic and some not? 

What you can do is to get the LoxAPP3.json from your loxone. To do so you 
have to go from your browser and visit this page:

http://<ip_from_your_loxone>:<port_of_your_loxone>/data/LoxAPP3.json

Replace all parts in <> for example for my setup I have to visit:

http://192.168.1.225:8080/data/LoxAPP3.json

You have to enter your username and password. Then you can see a json with 
all you config data. When you want you can sent it direct to me 
at my email adress:

joachim.dehli(at)gmail.com

When you sent it me give me the names from the problem covers.

**Comment by tanker11** [comment]
Hello,

After a while I got back to the project to test it according to your
request.
I realized that now all the covers are imported. I don't know how this
happened, but I suppose I missed something.
Apologies and thanks for your support. You can close the issue.


Joachim <notifications@github.com> ezt írta (időpont: 2020. jan. 18., Szo,
9:39):
