### ISSUE TITLE
Jalousie slat tilt position

### ISSUE THREAD

**Issue by tanker11** [JoDehli/PyLoxone#111]
Hello,

I love the project and thanks for the great work.
I just started using the covers where basic open/close commands seem to work, but when I get to "Set tile position" service, the cover either opens or closes the slats fully, not according to the percentage I set.
Is it a known issue? Could I help in investigating it?

Thanks

**Comment by JoDehli** [comment]
It is a know issue. In Loxone you can not set a tilt position. I know that it not implemented optimal but it works at least when the jalousie is open to close direct to the shade position. If you want to optimize it feel free to make a PR.

**Comment by JoDehli** [comment]
@tanker11 I was wrong. At that time I implemented it it was not possible or I did not see it. Then It should be possible to implement it better. I will take a look. 

If you want to try it you can do it with a websocket command like this:
![image](https://user-images.githubusercontent.com/32484282/161796353-7af49e6a-3ef6-4e55-90fb-fc909b720fa3.png)


### And here you can see all available commands for the cover:
![image](https://user-images.githubusercontent.com/32484282/161796587-77078e8f-2b19-4cf2-b0da-af367930e33f.png)

**Comment by JoDehli** [comment]
@tanker11  As a hint I discovered that the manualLamelle command does not work in every position. I got it to work when call down first and the for a example manualLamelle/50. But I am not really sure how to get it to work in every situation. I think that must be clear at first. 
Maybe you can investigate a little bit more.

**Comment by tanker11** [comment]
Yep, indeed, in the past the lamelle (slat) position did not work, but very
recently Loxone fixed it.
I will take a look at calling web socket and let you know the findings.

Joachim D. ***@***.***> ezt írta (időpont: 2022. ápr. 5., K,
18:27):

**Comment by JoDehli** [comment]
I found a thread with a similar topic. It is in German but maybe you can read it or translate it.

https://www.loxone.com/dede/question/api-manualpositoin-wird-ignoriert-wenn-das-zuletzt-verwendete-manualposition-die-gleiche-zahl-nutzte/

I think this workaround could work.

**Comment by JoDehli** [comment]
@tanker11 you can check the master branch if you want. I changed only the jalousie. For me now it works to set the tilt position.

**Comment by JoDehli** [comment]
@tanker11 did you try the fixed tilt version?

**Comment by tanker11** [comment]
I thought I answered already, sorry if not.
Yes, it works! Thanks a lot.

Joachim D. ***@***.***> ezt írta (időpont: 2022. ápr. 14.,
Csü 8:03):
