### ISSUE TITLE
Issues during conecting from outside of network due rejecting redirects from dns.loxonecloud.com

### ISSUE THREAD

**Issue by 07pepa** [JoDehli/PyLoxone#112]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
g2 but i am not shure

**Which software version does your loxone use?**
12.2.12.1

**How did you install HomeAssistant? Over Hassio oder manual install?**
in  docker  (but on windows... should not matter)

**Which Version do you use of HomeAssistant?**
Home Assistant 2022.4.0

**Describe the bug**
I know this is probaly "feature" but 304 receaved from dns.loxonecloud.com are not treated as redirects

i am conected from separate place then my loxone is and network is setted up corectly since i can easyly reach it with broswer (even the port changes from 80)

by reading log and code as pytho developer myself i come to folowing conclusions
*  maybe there needs to be some "discovery phase" that allows redirects
* maybe something in setup is missing (loxone must be port forwarded to 80)

** Paste the error log
```Logtalk
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 156, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 121, in getJson
    api_resp = await client.get("/jdev/cfg/apiKey")
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1729, in get
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1661, in _send_handling_redirects
    await hook(response)
  File "/config/custom_components/loxone/api.py", line 84, in raise_if_not_200
    raise LoxoneHTTPStatusError(
custom_components.loxone.api.LoxoneHTTPStatusError: Miniserver response code 307
```

**Comment by 07pepa** [comment]
this is mostly to let you know i think i will go custom solution build on https://github.com/JoDehli/pyloxone-api
since i need to keep confort temperature based on google calendar events and  home assitant would be unreliebly cumbersome ( only simple trigers) but i want to set start ends of heating so i need to use  your api

**Comment by JoDehli** [comment]
The python API is not working well. There is a bug with the reconnect. I already started completely from scratch here:

 https://github.com/JoDehli/PyLoxone_beta

For better development I included the API in the project. If you want you could take this as a base. 

In the first place my goal was to separate the loxone communication from the home assistant stuff. But the biggest problems I discovered is because this is not a official component the dependencies are often out of date and the component stopped working. 

At the moment I do not know if I should go this way to separate it in tow projects or should only make the pyloxone beta to the master.

Please do not use the API because it is not working properly

**Comment by JoDehli** [comment]
I think you could do your automation with python script in home assistant. And there was another plugin where you can make use of external python scripts in home assistant. Or you can use node red if you install it via hassio. This is the best way to run home assistant. Very stable and node red is already on board.

**Comment by JoDehli** [comment]
An for the connection problem. As I mentioned I want to make the pyloxone beta as the master branch. And I think there is it already y fixed this problem. If not it would be great if you can help me because I have no gen2. The gen1 can not use this feature. 

If you want you can join a discord channel which I made for general discussions or features request. 

https://discord.gg/mVCcG5nS

**Comment by 07pepa** [comment]
thanks for info we have gen 2 for shure... and further comunication wil be done on discord

**Comment by imbrechtsjurgen** [comment]
@JoDehli Is there any update on this issue? Can I try some beta-version with my Gen2 miniserver?
I would like to join the discord server but the link has become invalid.

**Comment by imbrechtsjurgen** [comment]
Yeah, I also think it would be very easy to do.
If I may ask, what exactly do you need? credentials to a Gen2 miniserver?

I also read somewhere that you were investigating using the API, will that be better/easier?
If I'm not mistaken, the homebridge loxone plugin is already using the API.

**Comment by imbrechtsjurgen** [comment]
So I have a miniserver v2 and to test, I just used the local IP in the home assistant setup and this worked apparently.
I'm still at work so there are things I can not test directly but the basics seem to work.
Why is the url used for v2 and not the direct IP address?

**Comment by JoDehli** [comment]
@JoDehli you can try https://github.com/JoDehli/PyLoxone_beta for testing. 
And I also tried to make the discord server public so maybe you can join it.
