### ISSUE TITLE
integration of EIB Dimmer

### ISSUE THREAD

**Issue by beber-msft** [JoDehli/PyLoxone#117]
Hello,
pyloxone is detecting my EIB switches but not my EIB dimmer, is there a way to integrate those?
I am on Gen1 server with latest updates and latest versions of HA and PyLoxone.

thanks.

**Comment by JoDehli** [comment]
What is a eib dimmer? How can I add it to my config? Is it a knx component?

**Comment by beber-msft** [comment]
yes, please see here:
https://www.loxone.com/enen/kb/eibknx-basics/

pylyxone does integrate the EIB push-buttons already, but not the dimmer.

**Comment by JoDehli** [comment]
Can I add this sensors to my config without a knx installation?

**Comment by beber-msft** [comment]
you should be, not sure what you can get out of it though. happy to provide any loxone configs from my end as well if it's any help. thanks for your support on this, much appreciated!

**Comment by JoDehli** [comment]
@beber-msft I could not add any eib (knx) component to my loxone without a knx installation. Sorry I can not implement it or look why it is not showing up in installation. 

What you can do is to implement it manually like it is decribed here: 
https://github.com/JoDehli/PyLoxone#if-your-device-is-not-supported

First you must get you conig file where your uuids are saved. Search for the dimmers and try so send websockets commands 
from home assistant. I would try the same commands which are implemented for normal dimmers.

**Comment by JoDehli** [comment]
@beber-msft I was able to add some knx entites but they showed up only as "type": "InfoOnlyAnalog"
Maybe it is because I added it wrong or it is because I have not real installation. 

If you found your dimmer config you can paste it here. Only the section for the device not the whole config because
there are sensible data in it for example your position etc.

**Comment by JoDehli** [comment]
@beber-msft I added the eib dimmer to the newest version of pyloxone. You can try it out and if you have any problems please report it back. I do not use any light and dimmer at all so I only tested it a little bit.

**Comment by beber-msft** [comment]
wow, thanks for the great progress. will test over the weekend and report back!

**Comment by JoDehli** [comment]
@beber-msft Ok I think I can close this issue. If you have problems you can reopen it or open a new issue.

**Comment by beber-msft** [comment]
confirm, everything working great so far, thanks again for your work on this! really appreciated!
