### ISSUE TITLE
Use async_get instead of async_get_registry for entity registry

### ISSUE THREAD

**Issue by elRadix** [JoDehli/PyLoxone#118]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen2

**Which software version does your loxone use?**
0.3.10

**How did you install HomeAssistant? Over Hassio oder manual install?**
Home Assistant OS on Proxmox 

**Which Version do you use of HomeAssistant?**
2022.6 

**Describe the bug**
See error log below 

**Paste the error log with the following settings:**
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 07:39:18 (3 occurrences)
Last logged: 07:39:46


Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. 
Please report issue to the custom component author for loxone using this method at 
custom_components/loxone/miniserver.py, line 181: device_registry = await self.hass.helpers.device_registry.async_get_registry() 


```

**Comment by JoDehli** [comment]
@elRadix thanks for your hint. I fixed it in the newest version.
