### ISSUE TITLE
Can't connect pyloxone anymore

### ISSUE THREAD

**Issue by fl1p1** [JoDehli/PyLoxone#119]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen 2

**Which software version does your loxone use?**
12.4.5.31

**How did you install HomeAssistant? Over Hassio oder manual install?**
Manual

**Which Version do you use of HomeAssistant?**
core-2022.6.4
5.15.32-v8

**Describe the bug**
I can't seem to connect my Loxone to Pyloxone. I tried with loxone dns link (http://dns.loxonecloud.com/SERIALNUMBER)
And several ports: 80, 8080, and the local port I set in my Loxone miniserver settings.
After that I tried with local url with the local port, just to try, but it failed too.
I already deleted and reinstalled Pyloxone.

**Error log:**
2022-06-10 15:40:57 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration loxone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-10 15:41:07 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
File "/config/custom_components/loxone/__init__.py", line 132, in async_setup_entry
File "/config/custom_components/loxone/miniserver.py", line 101, in async_setup
File "/config/custom_components/loxone/api.py", line 60, in getJson

**Comment by JoDehli** [comment]
@fl1p1 when did the error occur? After a update of loxone? 

For me it is nearly impossible to test a gen2 because I have a gen 1.

**Comment by fl1p1** [comment]
@JoDehli after about 6 months of HA updates :) It worked before, but not after the updates.
I now removed hacs, deleted every loxone folder, rebooted, installed pyloxone the manual way, but still nothing.

**Comment by JoDehli** [comment]
@fl1p1 Change the IP of the device where home assistant is installed. If you have too many failed login your IP will banned for a certain time.

**Comment by fl1p1** [comment]
@JoDehli I put my backup back and now it works again... But on old version of HA (2021.7.3). So I guess the ip isn't blocked.

Imo it's strange I need to put the local port I set in the miniserver? Is it automatically taken for the loxone DNS too cause that seems strange to me...
I guess I also don't need to put http, but just dns.loxonecloud...?

**Comment by JoDehli** [comment]
@fl1p1 Any success?

**Comment by fl1p1** [comment]
@JoDehli Thanks for the follow up.
To be correct: I just delete the loxone folders and paste the ones found here on github?
(HA is installed on a dedicated raspberry pi)

**Comment by JoDehli** [comment]
@fl1p1 yes correct. I think you have old version and the update was not correct. If you download the source code and copy it to your custom components folder under loxone and restart then you should have the newest pyloxone

**Comment by fl1p1** [comment]
@JoDehli I just updated pyloxone, did not update HA yet, but no success.
Also tried local ip, loxone dns ip in combination with local port and port 80... :(

**Comment by JoDehli** [comment]
@fl1p1 it is a gen2 thing I think. I do not know what you must fill in. I only know that only local access will work. I think it is not a big deal but I can not fix it without a gen2. Sorry. You can join my discord server. there is a user which successful connect to a gen2.

**Comment by JoDehli** [comment]
@fl1p1 here is the link to the server https://discord.gg/yRzxv6Xs
