### ISSUE TITLE
Can't create group 'Loxone Switches'

### ISSUE THREAD

**Issue by huliz** [JoDehli/PyLoxone#120]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
gen2 

**Which software version does your loxone use?**
12.2.12.1
**How did you install HomeAssistant? Over Hassio oder manual install?**
home-assistant docker
**Which Version do you use of HomeAssistant?**
[2022.6]
**Describe the bug**
error during the startup:
```
2022-06-12 20:39:10 ERROR (MainThread) [custom_components.loxone] Can't create group 'Loxone Analog Sensors' with error: 'group_registry'
2022-06-12 20:39:10 ERROR (MainThread) [custom_components.loxone] Can't create group 'Loxone Digital Sensors' with error: 'group_registry'
2022-06-12 20:39:10 ERROR (MainThread) [custom_components.loxone] Can't create group 'Loxone Switches' with error: 'group_registry'
2022-06-12 20:39:10 ERROR (MainThread) [custom_components.loxone] Can't create group 'Loxone Covers' with error: 'group_registry'
2022-06-12 20:39:10 ERROR (MainThread) [custom_components.loxone] Can't create group 'Loxone Lights' with error: 'group_registry'
```
my lights are missing (all dimmers/scenes), ventilation is missing.

I'd love to add them manually including scripts, e.g. setting ventilation to "2.0" or "3.0" but not sure what kind of command to issue via websocket event

**Comment by huliz** [comment]
e.g. this is the ventilation config
```"0e9a7357-03a5-d1b8-ffff58dbabe525cb": {
            "name": "Ventilatie",
            "type": "Radio",
            "uuidAction": "0e9a7357-03a5-d1b8-ffff58dbabe525cb",
            "room": "0c4bc0a8-0270-03ba-ffff58dbabe525cb",
            "cat": "0c4bc0a8-0261-02fc-ffff58dbabe525cb",
            "defaultRating": 0,
            "isFavorite": false,
            "isSecured": false,
            "defaultIcon": null,
            "details": {
                "jLockable": true,
                "allOff": "",
                "outputs": {
                    "1": "Stand 1",
                    "2": "Stand 2",
                    "3": "Stand 3"
                }
            },
            "states": {
                "jLocked": "8e9a7357-03a5-d1aa-ffff04c72879d5c2",
                "activeOutput": "0e9a7357-03a5-d1b7-ffff04c72879d5c2"
            }
        },```

**Comment by huliz** [comment]
1 part of lights that are not appearing in HA at all
```
"0e9267b6-0092-d9bf-ffff58dbabe525cb": {
            "name": "Lichtscenes sl. kamer 2",
            "type": "LightController",
            "uuidAction": "0e9267b6-0092-d9bf-ffff58dbabe525cb",
            "room": "0c4bc0a8-0275-03e8-ffff58dbabe525cb",
            "cat": "0c4bc0a8-025c-02d8-ffff58dbabe525cb",
            "defaultRating": 0,
            "isFavorite": false,
            "isSecured": false,
            "details": {
                "jLockable": false
            },
            "states": {
                "activeScene": "0e9267b6-0092-d9bc-ffff2b14af86fbdf",
                "sceneList": "100df4b0-0328-1e93-ffff58dbabe525cb"
            },
            "subControls": {
                "0e9267b6-0092-d9bf-ffff58dbabe525cb/AI1": {
                    "name": "Spots raam",
                    "type": "Dimmer",
                    "uuidAction": "0e9267b6-0092-d9bf-ffff58dbabe525cb/AI1",
                    "defaultRating": 0,
                    "isFavorite": false,
                    "isSecured": false,
                    "states": {
                        "position": "0e9267b6-0092-d9b0-ffff2b14af86fbdf",
                        "min": "0e9267b6-0092-d9a4-ffff2b14af86fbdf",
                        "max": "0e9267b6-0092-d9a5-ffff2b14af86fbdf",
                        "step": "0e9267b6-0092-d9a2-ffff2b14af86fbdf"
                    }
                },
                "0e9267b6-0092-d9bf-ffff58dbabe525cb/AI2": {
                    "name": "Lamp sl. kamer 2",
                    "type": "Switch",
                    "uuidAction": "0e9267b6-0092-d9bf-ffff58dbabe525cb/AI2",
                    "defaultRating": 0,
                    "isFavorite": false,
                    "isSecured": false,
                    "states": {
                        "active": "0e9267b6-0092-d9b1-ffff2b14af86fbdf"
                    }
                }
            }
        },
```

**Comment by JoDehli** [comment]
Radio and light controllers are not supported. 

And because of the start up errors which version of pyloxone do you use? If you not use the latest version please update.

**Comment by huliz** [comment]
thank you for your response.
It is the latest version of pyloxone.

do you think there will be radio controllers supported in future? do you have any hints how to send a manual command maybe? I was sending 2.0 to my ventilation uuid via websocket event but I got 404

**Comment by JoDehli** [comment]
I would first get rid of the error messages for the group creation. It is strange because I get no errors. I know there where a issue in the past but it should already fixed.

Because of the radio button: how can I configure a radio button in loxone? What device is it? I maybe I can add it and have a look how your command should look to switch between the states.

**Comment by huliz** [comment]
alright, when I enabled debug yesterday and tried to change modes of the ventilation, I could actually see it in the pyloxone debug output, so, I am going to get that log out and put it here in the coming days (can't reach it remotely yet).
in fact I see the same for lights but perhaps let's focus on one thing first.

do you think I can provide anything for you to dig into the errors? i tried increasing the generation from 3s to 15s but it didn't affect anything, the error was still there. the debug logging didn't provide anything extra I could think of relevance

**Comment by JoDehli** [comment]
Maybe I try it today an come back to you. How can I add  radio buttons?

**Comment by huliz** [comment]
if you mean in loxone, I think it's this one: https://www.loxone.com/enen/kb/radio-buttons/

i'm really new to this thing and I didn't configure it myself. trying to put home assistant in front of it so that I don't even need to touch this beast 😆

**Comment by JoDehli** [comment]
@huliz Regarding the radio buttons try this:
![image](https://user-images.githubusercontent.com/32484282/173383692-5e9fefe1-109b-4063-9d5f-a9f6bc4d8fc3.png)

The uuid is your action uuid of your radio entity. And in your example 1 means "Stand 1" and 2 "Stand 2" etc. 

And for "all off" you must sent a reset. Hope this helps.


Did you already converted the light controller to light controllerV2 ?

**Comment by huliz** [comment]
oh man, it worked, I saw 2.0 in the logs yesterday and it didn't occur to me to try just 2 or 3, was trying 2.0 in various ways. that will be easy for me to create buttons on HA for these.

for the light controllerV2 - is it something I can do myself? I had an impression that it is a hardware thing or is it pure configuration via loxone config?

**Comment by huliz** [comment]
ok, I found the way to convert but I have a warning about I5 inputs being not supported, I think I will need a Loxone support to help with that.
is there anything I can provide you with regards those errors? do you think they are because of light controller v1?
I also have heating connected that is not appearing on HA. I assume it is not yet supported

thank you for your help, amazing

**Comment by JoDehli** [comment]
@huliz thanks for the coffee. 

The errors are only for the group creation. I think all devices which are supported are created although this error occurs. I do not know why. Do you really have the latest pyloxone? Or maybe it is a gen2 thing. I have only a gen1. 

Because of the light controller v1: the controller v2 is more powerful but also some things are not compatible. So it could be that some things are not working properly if you convert it. But with this I can not help you. You can control it also with a websocket command if you have not to many. 

As I started with this binding the light controller v1 was already deprecated. Maybe I can look to integrate it if I have time.

**Comment by huliz** [comment]
thank you, no worries, I will play around with websocket commands for the lights.

**Comment by JoDehli** [comment]
@huliz I tried to add a lightcontroller v1 to my project but I can not find it. I only can add a v2 controller. Can you tell me how I add a v1 to my project. Maybe I must set something to a v2 to behave like a v1?

**Comment by huliz** [comment]
FYI, I managed to convert some of the light controllers to V2, now the scenes and switches are generated. Unfortunately I'll have to play around a bit longer with the 2 other rooms, it looks like there are some KNX components configured as inputs that prevent migration to V2. Almost there :-)
the number of group errors is still the same at the startup. I imagine it might be related to the KNX analog inputs

**Comment by rolandpj** [comment]
Was there any solution for this error: ?

custom_components.loxone] Can't create group 'Loxone Group' with error: 'group_registry'

I see this in my logs with current pyloxone and Ha version with Gen1 miniserver

**Comment by JoDehli** [comment]
@rolandpj no. We couldn't figure out what causes the error. If you see all entities it should not a big problem for the functionality for your system.

**Comment by huliz** [comment]
Indeed, after one year it's still there and there is nothing wrong with the
integration apart from this startup error message.

**Comment by radosek21** [comment]
> Was there any solution for this error: ?
> 
> custom_components.loxone] Can't create group 'Loxone Group' with error: 'group_registry'
> 
> I see this in my logs with current pyloxone and Ha version with Gen1 miniserver

Hi. I had the same problem. Tried everything to make it running. Only comment out affected lines in custom_components\loxone\__init__.py file helped. I'm newbee in HA and do not know impact of this modification to the system. But it works ;-)

**Comment by JoDehli** [comment]
@radosek21 @huliz I can catch the error so that the error message is not thrown but I would personally know what the error causes. I mean which devices. I do never get this error but I have the smallest system of all users of pyloxone I think.
