### ISSUE TITLE
[QUESTION] How to get temperature value from TouchTree sensor?

### ISSUE THREAD

**Issue by mikebocian** [JoDehli/PyLoxone#123]
Hi there, 

At the beginning, thanks a lot for such a functional integration. 
I've got (most probably) silly question. I would like to see a temperature taken from Touch Tree sensors. I can see the values in the Loxone app, however, it is not visible when running out-of-the-box configuration. Do you have any tip how to approach this?

Mike.

**Comment by JoDehli** [comment]
@mikebocian sorry for the late response. Very busy at the moment. 

First of all I do not have a Touch Tree device but I think you can get the temperature values by using a custom 
sensor with the uuid from the touch tree device. 

1. you have the get the uuid from your tree device. You can download the config from your loxone server by following this steps: 
   https://github.com/JoDehli/PyLoxone#how-do-you-get-the-uuid
2. You can then search for the tree device by searching for the name of the device or the type.
3. If you have the uuid you can define your custom sensor by following this steps:
    https://github.com/JoDehli/PyLoxone#if-your-device-is-not-supported

If you do not find the uuid or if you do not know exactly to interpret the entry in the config you can paste ONLY the part with the touch device here. Maybe I can help you with it.

**Comment by mikebocian** [comment]
Thank you, I've managed to get the temperature by adding custom sensor and it is working like a charm. For future generation, something like this shoud work: 

```  - name: pokoj1.temperatura
    platform: loxone
    uuidAction: "18xxxxxxxxxhash-hash-hash-hashb35b"
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "total"```
