### ISSUE TITLE
Py Loxone on Home Assistant Version 2022.7.5

### ISSUE THREAD

**Issue by KobeNuyts** [JoDehli/PyLoxone#124]
Dear,
I have great respect for your project and use it every day. 
I wonder if the code also has been updated to the latest version of Home Assistant (2022.7.5).
If you have this new version, or are working on it, could you please let me know?
Thanks in advance!

**Comment by JoDehli** [comment]
@KobeNuyts why do think you need a special version for the be HA version? The newest version of pyloxone should work with the newest HA version.
