### ISSUE TITLE
How to get Data from Homeassistant to Loxone.

### ISSUE THREAD

**Issue by BarisYal** [JoDehli/PyLoxone#125]
Im trying to get a temperatur value from Home Assistant into an Marker from Loxone, but i dont know how this should work. I have no experience in yaml. Please Help

**Comment by JoDehli** [comment]
@BarisYal you can not set a marker direct. You have to find something else which you can set directly.

**Comment by JoDehli** [comment]
@BarisYal I looked for a way to set some data from HA. 

If you want you can try the following:

1. Add a virtual Input in Loxone. Add it to a Sheet and configure it as you want. For example as "Left-Right Buttons" or "Slider"
2. Then try it first to set it via the loxone app. .
3. If you can set it via loxone app you can use the output in loxone for example to set a value for a automation or something else. 
4. Now the question is how to set it via home assistant and not by the loxone app. This is very simple. First of all you need the uuid for your virtual input. You get the uuid by following these steps:
```shell
You can download the config of your loxone by go to the following adress: 
http://{ip-address-of-your-loxone}:{port}/data/LoxAPP3.json

{ip-address-of-your-loxone} --> replace with the ip of your loxone 

{port} --> replace with your port (default: 80)

```
5. Search for the name of the virtual input.
6. And then try to send a websocket command over HA like in this example: 
![image](https://user-images.githubusercontent.com/32484282/182559845-f6a7b746-8c15-495e-a90f-dc8ac24cb3e2.png)

In this example I set the value to 12 for the input. If this is successful you see that that value changes for the virtual input.
Now you can use the method in all kind of automations in HA and set the value in the miniserver.

**Comment by JoDehli** [comment]
@BarisYal have tried it?
