### ISSUE TITLE
Tunable White Support

### ISSUE THREAD

**Issue by funbirdcas** [JoDehli/PyLoxone#127]
Hey,

Since Loxone Config 13 they released a tunable white support for the RGBW Dimmer and Lightcontroller.

Does PyLoxone support this "new" kind of color selection ?

**Comment by JoDehli** [comment]
Not at the moment. I did not recognize that there are ne features on the light controller as I do not use any lights. Maybe I can implement if I have time.

**Comment by JoDehli** [comment]
@funbirdcas I looked at it and I think implementing into HA direct is not possible. But you can call it directly via websocket command and use it via a script. I already explained in other issues how it works to get the uuidAction and send command. If you search in some of the recently closed issues you find some explanations.

**Comment by funbirdcas** [comment]
Thx @JoDehli  for the fast reply
