### ISSUE TITLE
Can't see any Entities or Devices

### ISSUE THREAD

**Issue by efuks** [JoDehli/PyLoxone#129]
Hi,

I am new to HA and I managed so far to get HA to run on a Synology on Docker. Also I have been able to install the PyLoxone Binding via HACS. Binding is up and is shown under Devices and Entities.
But I don't get any Devices shown. 
HACS Version 1.27.1
PyLoxone Version 0.3.14
![Bildschirm­foto 2022-09-10 um 23 29 59](https://user-images.githubusercontent.com/113206857/189502391-672ef35a-8314-4306-b9cf-d05a959a7c6e.png)

**Comment by JoDehli** [comment]
Do you use the official app from loxone? Do you see devices on the official app? And do you use the same user and password or did you use a different user for ha?

**Comment by efuks** [comment]
Thanks. I have made a service account in Loxone, but forgot to add the ui rights to that account. 
Thanks a lot!
