### ISSUE TITLE
The loxone platform for the binary_sensor integration does not support platform setup

### ISSUE THREAD

**Issue by ztamas83** [JoDehli/PyLoxone#135]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen1

**Which software version does your loxone use?**
13.x

**How did you install HomeAssistant? Over Hassio oder manual install?**
Hassio

**Which Version do you use of HomeAssistant?**
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Describe the bug**

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:193
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 08:41:48 (1 occurrences)
Last logged: 08:41:48

The loxone platform for the binary_sensor integration does not support platform setup. Please remove it from your config.

**Paste the error log with the following settings:**
No logs as of now, not sure if this is a loxone or a HA issue. Any ideas?

**Comment by JoDehli** [comment]
For now you can ignore this error. I have the same error but everything works just fine. I had no time to really dig into this problem as everything works fine.

**Comment by ztamas83** [comment]
I thought's it's related to my problem where a binary_sensor with template platform using loxone sensor in the template value, but apparently not.
This error has something to do with setting up the binary sensors in the Loxone platform. But probably you are right, if everything is OK then nothing to worry about. Ugly with error though :)
