### ISSUE TITLE
Can't get the PyLoxone config screen.

### ISSUE THREAD

**Issue by TheChristan** [JoDehli/PyLoxone#136]
I can't get this screen: 
![cloud_config](https://user-images.githubusercontent.com/93482737/199325055-95cb2cec-bd07-402f-88c2-37e9c8d824fc.png)
 should i just add the Configuration over yaml (deprecated) code?

**Comment by JoDehli** [comment]
Then the installation failed. Try to reinstall it.  How did you install it?

**Comment by TheChristan** [comment]
> Then the installation failed. Try to reinstall it. How did you install it?

I installed it with HACS and have tried to reinstall it multiple times, also tried a fresh HA install still didn't work.

**Comment by TheChristan** [comment]
Fixed it!
