### ISSUE TITLE
Read actual state from radio button

### ISSUE THREAD

**Issue by Dohnalradek** [JoDehli/PyLoxone#137]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen1

**Which software version does your loxone use?**
9.3.3.26

**How did you install HomeAssistant? Over Hassio oder manual install?**
manual install (on ubuntu os)
**Which Version do you use of HomeAssistant?**
(2022.11.1

**Describe the bug**
Is there any way how to read actual state of Loxone radion button (8x or 16x)? I can set state I wish (from HA) but I cant read the actual state from Loxone back to HA.

**Paste the error log with the following settings:**
From Loxone it sends this data:
```
"174fde1e-0256-2c65-fffff314d320ca87": {
  "name": "Zásuvky skleník",
  "type": "Radio",
  "uuidAction": "174fde1e-0256-2c65-fffff314d320ca87",
  "room": "0ed7e2ef-0382-9622-ffff00bdc36df1d0",
  "cat": "1067574d-035a-4cee-ffff00bdc36df1d0",
  "defaultRating": 0,
  "isFavorite": false,
  "isSecured": false,
  "defaultIcon": null,
  "details": {
    "allOff": "",
    "outputs": {
      "1": "ZAP",
      "2": "TOPENÍ",
      "3": "VĚTRÁNÍ",
      "4": "VYP"
    }
  },
  "states": {
    "activeOutput": "174fde1e-0256-2c7e-fffff314d320ca87"
  }
},
```
Actual state should be in "activeOutput" but there is only the UUID (I dont know why). 

logger:
  default: warning
  logs:
    homeassistant: warning
    homeassistant.helpers: warning
    custom_components.loxone: debug
    custom_components.loxone.api: debug
```

**Comment by JoDehli** [comment]
You have to make custom sensor as described in the main page. The uuid must be the states uuid. Then you should get a int value which radio button is active.

**Comment by elRadix** [comment]
just for my curiosity, what is a radio button in loxone? do you have a T5?
Is that a physical button? @Dohnalradek
Can you explain your use case.

**Comment by Dohnalradek** [comment]
Its any logical box with up to 8 inputs and 8 outputs. Only one output can be active at a time. E.g. pulse at input (I3) activates output (O3). And I can switch between this states by impuls on selected input, or by mobile/PC app.

In my case I use 4 states (on, heating, ventilation, off) to change function of sockets in my green house.
