### ISSUE TITLE
invert binary sensor ?

### ISSUE THREAD

**Issue by elmattt** [JoDehli/PyLoxone#138]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
msgen1
**Which software version does your loxone use?**
latest
**How did you install HomeAssistant? Over Hassio oder manual install?**
rpi
**Which Version do you use of HomeAssistant?**
latest
**Describe the bug**

i cant figure out how to invert a binary sensor, in loxone the door is open, in HA the same door is closed ?

thanks by advance

**Comment by JoDehli** [comment]
@elmattt you have multiple options for switching the state. I would define a output in loxone with the opposite state of the door.  And then you can use this on ha as door indicator. 

Or you can define a template sensor on the home assistant side where you switch the state. 

For both options you find a lot of examples on the net. 

The other question for me is what state does the door has in loxone and what state on home assistant. And what type of entity is it in loxone and what in Homeassistent? Is it a custom sensor or a cover or door implementation of pyloxone.

**Comment by JoDehli** [comment]
@elmattt what is the state of this issue? Have you solved you problem?
