### ISSUE TITLE
Double tap on loxone touch (or other binary sensors

### ISSUE THREAD

**Issue by brechtvhb** [JoDehli/PyLoxone#146]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen2
**Which software version does your loxone use?**
13.1
**How did you install HomeAssistant? Over Hassio oder manual install?**
image for odroid n2+
**Which Version do you use of HomeAssistant?**
2022.11.4
**Describe the bug**
When double tapping the loxone touch PyLocoxone / Home assistant often detect only one tap.
Sometimes it registers 2 taps sometimes just one tap. I would say it is about 50/50

**Comment by brechtvhb** [comment]
Been testing with https://github.com/Loxone/LxCommunicator.NET to find out if it is a problem in loxone or not and this library seems to return every state change.

**Comment by JoDehli** [comment]
Could be a websocket delay problem. I can not test it I have no touch. Try to play around with the times for the double tab. Maybe you can fix it that way. On the implementation I can not change anything.
