### ISSUE TITLE
See but can't use/read the Loxone hardware

### ISSUE THREAD

**Issue by Nico0W** [JoDehli/PyLoxone#148]
Hello,

Previously, I had installed my HA on a virtual machine to test what I can do with my Loxone in HA. Previously on this virtual machine, i was able to read sensors and control everything directly. Easy game.

Now, I've installed HA on a Raspberry 4. The installation of PyLoxone was done without any problems (I've got a Gen1 Loxone server).
Home Assistant detects each sensor, switch,... But I can't control/read it. Each device seems to be attached to a uuid so i don't understand what I have to do to make it work.

I tried to use my old installation files that I used on my virtual machine but it was worse.

I made a manual installation. Should I try the Hacs one ?

Can you help me, please ? :-)

**Comment by Nico0W** [comment]
Some news: I changed the power supply of the RPI (for cable management) and now, it seems ok! I do not understand...

**Comment by JoDehli** [comment]
I do not know why but I had also some strange behaviour of the rasp when the power supply is to weak. Glad that it works now.

**Comment by Nico0W** [comment]
Works perfectly now. 

But I can't manage my Loxone switches... Can you say me how ? I've got temperature and Humidity of them but that's all. Is it possible to change/add the configuration of them ?

And my Loxone movment detector are not recognised too... Is it possible ? 

Thank's in advance :-)

**Comment by JoDehli** [comment]
Can you see them in the official app?

**Comment by JoDehli** [comment]
The movement detectors are maybe not supported but the switches should work.

**Comment by Nico0W** [comment]
I do not see them in the official app. I didn't know that it was possible to manage them in the official app! But I've got only the user access, not the admin one. 

For the movement detectors, I've got these: https://shop.loxone.com/frfr/detecteur-de-presence-multicapteur-tree-blanc.html

**Comment by JoDehli** [comment]
If you do not see them in the official app you will not see them in pyloxone and HA. There is a visibility option for every entity. You have to ask if the admin can make it visible.

**Comment by Nico0W** [comment]
Ok, Thank you. I'm going to ask my admin for it. I already can see this:

![image](https://user-images.githubusercontent.com/96498657/209980125-b95ff917-7c90-47ed-8039-7fb37c433d9a.png)

Information about the light controller. Can't manage it with this, right ?

**Comment by Nico0W** [comment]
Hi @JoDehli , i spoke to my admin about the visibility option for my switches and detectors. For the detectors, he can do something. He will try.

But for the switches, he says that the only thing that is possible is to make a virtual switch in the app that could replace a physical one. I suppose it's not what he have to do. 

Can you say me where he can find the visibility option to make it visible in HA ? 
I guess he would not be really happy I ask Loxone by myself...
