### ISSUE TITLE
Entities of type "Zentral" are missing

### ISSUE THREAD

**Issue by Lesani** [JoDehli/PyLoxone#149]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
  Gen2
**Which software version does your loxone use?**
  Version: 13.1.10.19
**How did you install HomeAssistant? Over Hassio oder manual install?**
  Home Assistant 2022.12.1
  Supervisor 2022.11.2
  Operating System 9.3
  Frontend 20221208.0 - latest
**Which Version do you use of HomeAssistant?**

**Describe the bug**
Loxone Object types "Licht Zentral" for Lights and "Automatikbeschattung Zentral" for Blinds are not represented in PyLoxone
Individual objects of type "Lichtsteuerung" and "Automatikbeschattung" are represented correctly

![image](https://user-images.githubusercontent.com/5182104/206863011-172ca296-adb0-47e1-8e44-c9416ea4a972.png)

**Comment by JoDehli** [comment]
They are not implemented and will not be implemented. Please use a home assistant alternative for example a script or group.

**Comment by Lesani** [comment]
sure, why make it easy and only implement all of the things that loxone offers, just because another method already exists in HA 👍 you just have to do everything twice when you edit something
