### ISSUE TITLE
Cannot find PyLoxone in HACS

### ISSUE THREAD

**Issue by Juxz** [JoDehli/PyLoxone#15]
Browsing manually or searching "loxone" or "PyLoxone" brings no result in HACS

**HACS :**
Integration version: | 0.22.2
Frontend version: | 20200229193422
Repositories: | 397

**HA:**
arch | armv7l
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.6
version | 0.105.1
virtualenv | false

**Comment by JoDehli** [comment]
Have you added the repo to the custom repos in hacs? It is not in the official repository.

**Comment by Juxz** [comment]
If everything could be so simple ... :) thanks
