### ISSUE TITLE
An idea who's going on?

### ISSUE THREAD

**Issue by I-am-OK-86** [JoDehli/PyLoxone#151]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?** Gen2

**Which software version does your loxone use?** 13.1.11.17

**How did you install HomeAssistant? Over Hassio oder manual install?** 

**Which Version do you use of HomeAssistant?**
Home Assistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest

**Describe the bug**
Error setting up entry PyLoxone for loxone

**Paste the error log with the following settings:**
2022-12-26 20:28:08.905 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
File "/config/custom_components/Loxone/__init__.py", line 195, in async_setup_entry
File "/config/custom_components/Loxone/miniserver.py", line 140, in async_setup
File "/config/custom_components/Loxone/api.py", line 122, in getJson

**Comment by JoDehli** [comment]
Error occurs right at the beginning. Are the credentials and username and port right?

**Comment by JoDehli** [comment]
And with the gen2 only local access via the IP address is supported at the moment.

**Comment by I-am-OK-86** [comment]
Many thanks, that was the root cause. I did not see that it only can be reached with the local IP address. Maybe it’s me but if it is actually missing in the description it would be good to add it.

**Comment by JoDehli** [comment]
I am working on a better integration for the gen2.then this should be solved. But it needs some time to finish.
