### ISSUE TITLE
newly added devices don't seem to sync across

### ISSUE THREAD

**Issue by a011528** [JoDehli/PyLoxone#159]
Gen2 - Latest Config / Latest HA / Latest PYloxone

Devices + entities flow across when I first install and set the configuration up.  However it seems hit and miss that when I create a new device in Loxone or a Virtual Device in Loxone some seem to sync across but not all!

Question Is the "Reload" the re-sync command? vs restarting the whole Home Assistant
What is the interval of refresh / polling set at and where >?
And are certain devices excluded such as **Virtual Inputs** ?

**Comment by JoDehli** [comment]
Reload is not supported for now. Only restarting home assistant will reload the entries from loxone and update the entities in Homeassistent.

**Comment by a011528** [comment]
thx that addressed 2 of 3 Q I Have.

As mentioned some Virtual Interfaces are read , others are not (and in Loxone config they are set-up the same way) - so its odd, do any limitations exist around Virtual Interfaces being read ? or is the expectation to create these manually in yaml ?

**Comment by JoDehli** [comment]
Do you see them in the official app? If you see them on the official app it could be a problem.

If you do not see them in the official app then they are maybe set to visible=false in locone config or they are not supported. 

You can define a visibility for each entity in locone config. This is useful for entities you use only for internal data parsing or logic and you do not want that they show up in the app. And pyloxone uses the same API which the official app uses. So you can double check it with your app if you think there is something wrong.

**Comment by JoDehli** [comment]
Normally not. I used only this option to hide or make visible. And there are no way to hide in the official app and not in HA. Of course you can use different user with rights. Then you can define or hide things vor each person.

**Comment by a011528** [comment]
I was thinking the same: to restrict with a User or User Group, yet i still have the problem that when i create a VI it does not flow (even though i can see them in loxon App)
 
Can you conform or validate the behaviour: Creating a normal Virtual Interface in Loxone Config that it flows into HA via Pyloxone 

Other than that it is a Great Tool/ Add_on!!! and solving many legacy workarounds i have!

**Comment by JoDehli** [comment]
I do not understand what you mean with flow into HA? 
I do not know (without looking into the code or test) if a virtual output is showing up in the HA. If you see them in the official app you know that it could be integrated into HA somehow if it is not already done. Can you tell me what you want to do or how you configured your entity in locone config. Maybe I can configure the same entitiy on my system and look if it is already supported?

If you want you could join the discord server I made for such problems. https://discord.gg/PehvmwzU

**Comment by a011528** [comment]
Just updating for others: 

1. i had to set "use" in the VI
2. i had to enter some text in the Description 

Only then would it flow.

**Comment by JoDehli** [comment]
@a011528 I am interested to know if the entities show up in the LoxAPP3.json if you do not use a description? Do you know how to get it from your Miniserver?
