### ISSUE TITLE
Loxone Light Controller v2 improvements

### ISSUE THREAD

**Issue by Juxz** [JoDehli/PyLoxone#16]
Hi,
I propose the following improvements regarding Light Controller integration

Assumptions: the Loxone Light Controller v2 is configured with dimmable and rgb light circuits.

AS-IS :
For each Loxone Light Controllers v2 are created in HA :

- 1 entity device_type "lightcontrollerv2" with effects (Scenes) in "Loxone Lights" group. HA Entity name = Loxone lightcontrollerv2 name
- 1 entity with a static name "Overall Brightness" defined as device_type "dimmer" in "Loxone Lights" group.
- 1 entity with a static name "Overall Color" defined as device_type "colorpicker". Not assigned to a group
- n individual lights entities:
a) if light circuit is switch or colorpicker: Not assigned to a group
b) if light circuit is dimmer: assigned to "Loxone Lights" group.

TO-BE:
For each Loxone Light Controllers v2 are created in HA :

A) 
1 group named by the Light Controller name, and inside this group :
- 1 entity device_type "lightcontrollerv2" with effects (Scenes)
- 1 entity with a static name "Overall Brightness" defined as device_type "dimmer" 
- 1 entity with a static name "Overall Color" defined as device_type "colorpicker"

B)
n individual lights entities (switch, colorpicker, dimmer). Not assigned to a group

**Comment by JoDehli** [comment]
@Juxz can you test the Dec branch. There I added a option to suppress the subcontrols of a light controller. You have only a master brightness and color.

**Comment by Juxz** [comment]
Will try a.s.a.p !

**Comment by Juxz** [comment]
I was not able to get light working on HA 2021.1.0. I tried with and without "Generate subcontrols for lightcontrolerV2", I keep getting the following error log, and no light entity is created (other entities like cover and sensors are working) : 


07.01.21 10:32:05 (+0100)  homeassistant  2021-01-07 10:32:05 ERROR (MainThread) [homeassistant.components.light] Error while setting up loxone platform for light
07.01.21 10:32:05 (+0100)  homeassistant  Traceback (most recent call last):
07.01.21 10:32:05 (+0100)  homeassistant    File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
07.01.21 10:32:05 (+0100)  homeassistant      await asyncio.shield(task)
07.01.21 10:32:05 (+0100)  homeassistant    File "/config/custom_components/loxone/light.py", line 48, in async_setup_entry
07.01.21 10:32:05 (+0100)  homeassistant      new_light_controller = LoxonelightcontrollerV2(**light_controller)
07.01.21 10:32:05 (+0100)  homeassistant    File "/config/custom_components/loxone/light.py", line 164, in __init__
07.01.21 10:32:05 (+0100)  homeassistant      if self.states["masterValue"] is not None and self.states["masterColor"] is not None:
07.01.21 10:32:05 (+0100)  homeassistant  KeyError: 'masterColor'

**Comment by JoDehli** [comment]
@Juxz can you try it with the updated dev branch if you have time?

**Comment by Juxz** [comment]
Mostly everything work perfectly, that's brilliant thank you.
I didn't manage to generate Scenes, but lightcontrollers and subcontrols are OK.

**Comment by JoDehli** [comment]
Ok I saw the problem with the scenes. I do not use scenes at all that is why i missed it. I updated the dev branch again if you want to try it again.

**Comment by Juxz** [comment]
I can see and change "effects" inside a lightcontrollerv2, but I don't see any Scenes generated as entities like it was before.

**Comment by JoDehli** [comment]
Have you checked to generate scenes in the options menu?

**Comment by Juxz** [comment]
Yes yes

**Comment by JoDehli** [comment]
You must restart after changing the options in the integration menus. 

Did you use the newest Dev branch from yesterday?

**Comment by Juxz** [comment]
Yes I was using the latest version from Dev branch, with several restarts in between.
However, I just tried the Master branch and still don't get any scenes with that version 😵
We should request someone else to test it, could something buggy on my specific loxone project.

**Comment by Mike26051981** [comment]
Did you already implement those light controller changes?

I get weird errors complaining about the object not having 'supported_color_modes' set if i try to turn on a light entity.


    281473214778624] 'LoxoneLight' object has no attribute 'supported_color_modes'
    [281473243739520] 'LoxoneLight' object has no attribute 'supported_color_modes'
    [281473245496416] 'LoxoneLight' object has no attribute 'supported_color_modes'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 272, in async_handle_light_on_service
    supported_color_modes = light.supported_color_modes
AttributeError: 'LoxoneLight' object has no attribute 'supported_color_modes'



Pretty sure that this worked a week ago without problems.

**Comment by JoDehli** [comment]
I already made changes. But a versions ago. Did you make an update.

**Comment by Mike26051981** [comment]
I tied beta from HACS and for now i copied the files manually from your github repo and readded the loxone integration.

**Comment by JoDehli** [comment]
You had a working version. Which version was that? If you use hacs you can go back to any version if you have trouble. So this is the way to go. If you find a problem with a new version please give me the last working version number and the version with the error. I changed it a longer time ago and since then I made already some other changes.

**Comment by Mike26051981** [comment]
Tried to reinstall version 0.3.2 and 0.3.1 but this strange as it's a lightcontrollerv2 subcontrol entity.
I noticed i can turn off the light once it's turned on.

but if the light is currently turned off and i try to turn it on again it states:

failed to call service light/turn_on. 'LoxonLight' object has no attribute 'supported_color_mods'.

I also tried setting an supported color mods attribute via customizations, but it won't work either.


Logger: homeassistant.components.websocket_api.http.connection
Source: components/light/__init__.py:272
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:52:52 AM (7 occurrences)
Last logged: 10:57:56 AM
[281472984524016] 'LoxoneLight' object has no attribute 'supported_color_modes'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 272, in async_handle_light_on_service
    supported_color_modes = light.supported_color_modes
AttributeError: 'LoxoneLight' object has no attribute 'supported_color_modes'

**Comment by JoDehli** [comment]
I found the mistake. They changed something on the light implementation. It is on the newest version on ha. I will fix it. So you have 2 options. 1 downgrade you ha to the version before or 2 wait until i fixed it. Maybe this weekend. you can use then the newest version. I will make a 0.3.4

**Comment by Mike26051981** [comment]
Wow thanks for the investigation.
I'll wait for the fix ;)

**Comment by JoDehli** [comment]
@Mike26051981 can you try the dev branch? Does it work?

**Comment by Mike26051981** [comment]
@JoDehli Yes i tried the DEV Version.
This time there a no supported_color_mode failures or other weird stuff.

At least all lights which previously failed i can now switch on and off again as usual.
Thank you for fixing it that quickly, i can move on with the UI now.
