### ISSUE TITLE
Incorrect auto_state value for cover

### ISSUE THREAD

**Issue by ascha191** [JoDehli/PyLoxone#163]
Gen1

Latest Loxone Updates

Hassio

Home Assistant 2023.2.2

The auto_state attribute of Loxone cover entities does not always have the correct value.
E.g. The Loxone app shows that the automatic mode is disabled, but the attribute of the entity says that the automatic mode is enabled.
I have not yet been able to specifically track down the error, but I suspect it has something to do with setting/deactivating the automatic modus via a Shading Central block?!

**Comment by ascha191** [comment]
I can reproduce the error as follows
- Enable automatic sun positioning for the blind
- Disable automatic sun positioning by raising the blind manually (via Loxone App)
=> Now in the Loxone App the automatic sun positioning is deactivated, but the attribute in the Home Assistant auto_state = on

automatic_text: Automatik Beschattung wegen Eingriffs für heute deaktiviert.
Are there maybe 2 different types of deactivated? 
- Complete
- Just for today

**Comment by JoDehli** [comment]
@ascha191 I could not reproduce the error? With my bilnd it works. Can you provide more details?
