### ISSUE TITLE
Cover device_class integration

### ISSUE THREAD

**Issue by Juxz** [JoDehli/PyLoxone#17]
Hi,

I propose to improve the Cover integration.

In loxone miniserver there are 6 types of objects to be mapped to Cover in HA:

- Garage/Gate controller, which has 6 "animation"
-- 0: Garage door
-- 1: Single Gate Opening to the left
-- 2: Single Gate opening to the right
-- 3: Gate opening to both side
-- 4: Folding Door opening to the left
-- 5: Folding Door opening to the right
- Skylight controller
- Skylight shade controller
- Automatic blind controller, which has 7 "types"
-- 0: Venetian Slatted Blinds
-- 1: Roller Blinds or Shutters
-- 2: Curtains opening to both sides
-- 3: Schlotterer Retrolux
-- 4: Curtain left
-- 5: Curtain right
-- 6: Awning
- EIB blind controller
- Door controller

In HA, there only 1 object Cover which has 10 possible values for device_class:
- None
- awning
- blind
- curtain
- damper
- door
- garage
- shade
- shutter
- window

In current PyLoxone version:
- all Garage/Gate controller are mapped to "device_class=Gate".
- all "Jalousie " are mapped to "device_class=Jalousie". I don't know what object it includes (Skylight? EIB dimmer?...)

Anyway, I suggest improving this part because it has several impacts related to voice assistant integrations (alexa, google assistant, homekit...). The vocal commands and security might be different whether it's door or a garage door or other.

As a workaround I'm using this type of entry in customize.yaml, but this is not ideal:
```
cover.porte_garage:
  device_class: garage   
```

Here below one mapping table proposal. I don't know if loxone API is offering all this flexibility, but I refer to loxone config capabilities

Loxone   Config | device_class
-- | --
Garage/Gate controller,   animation =0: Garage door | garage
Garage/Gate   controller, animation = 1: Single Gate Opening to the left | door
Garage/Gate   controller, animation = 2: Single Gate opening to the right | door
Garage/Gate   controller, animation = 3: Gate opening to both side | door
Garage/Gate   controller, animation = 4: Folding Door opening to the left | door
Garage/Gate   controller, animation = 5: Folding Door opening to the right | door
Skylight controller | window
Skylight shade controller | shade
Automatic   blind controller, type = 0: Venetian Slatted Blinds | blind
Automatic   blind controller, type = 1: Roller Blinds or Shutters | blind
Automatic   blind controller, type = 2: Curtains opening to both sides | curtain
Automatic   blind controller, type = 3: Schlotterer Retrolux | shutter
Automatic   blind controller, type = 4: Curtain left | curtain
Automatic   blind controller, type = 5: Curtain right | curtain
Automatic   blind controller, type = 6: Awning | awning
EIB blind controller | blind
Door controller | door

Thanks

**Comment by JoDehli** [comment]
Have you checked it if the changes in the dev branch? Is something missing?

**Comment by Juxz** [comment]
I need to test a few more combinations of devices but so far it's working well.

**Comment by Juxz** [comment]
Tested in release PyLoxone 0.2.1 with Loxone Miniserver 10.3.11.27 and it's all good
Thanks JoDehli
