### ISSUE TITLE
Dataflow disrupts when electricity goes off

### ISSUE THREAD

**Issue by Alwyn989** [JoDehli/PyLoxone#171]
Hi there,
I live in South Africa where the electricity grid turns off several times a day (" load shedding") as we do not have enough generating capacity. I have a PV system. Whenever public electricity goes off, my entire house goes dark for about 3 seconds before the PV system takes over. This is necessary because the PV system needs to build it's own internal grid and also to make sure that no electricity from my PV system gets fed into the public grid. My Loxone server (Gen 1) is on UPS and never gets disrupted. So far, so good.
But for a while now (maybe 2 months?), I have noticed that whenever the power grid goes off, Sensors start to freeze in HA and never come on again. The only way to fix this is by rebooting HA, after which it works perfectly well, until the next load shedding event.
This behaviour appears only in HA/PyLoxone, when checking the original Loxone app, all sensors there are fine. That means, I cannot pinpoint this problem to either HA or PyLoxone, but it definitely comes from that side.
I am not too familiar with HA but have managed to set up everything i need so far.

**Comment by JoDehli** [comment]
@Alwyn989 please use the issue template.

**Comment by Alwyn989** [comment]
I am confused... i thought this was the right way? would you please direct me to the template you are referring to?

**Comment by JoDehli** [comment]
When you create in Issue your are asked some questions. Please fill in at least these questions with a detailed home assistant log from the problem.

**Comment by johny-mnemonic** [comment]
@Alwyn989 this sounds like even though your Loxone Miniserver is on UPS some network component isn't which causes connectivity issue between HA and Loxone. And PyLoxone sometimes have hard time reconnecting back to Loxone.
Maybe it will get better with the new communication @JoDehli is working on right now, but currently you only option is probably to create automation to reload the PyLoxone integration.
Or better yet, make sure your network is not disturbed by grid turn off/on events - i.e. put Loxone, HA and network components on UPS.

**Comment by Alwyn989** [comment]
You are correct, the loxone server is on UPS, but not the network as i am using powerline adapters which obviously don't work during a blackout. however, this setup has worked flawlessly in the past, and it works again now, after the last HA core update. not sure what was wrong, but it seems something has changed within HA and now all works well again.
i am sorry for my sluggish replies, but i am travelling so much for business lately, i just don't have the time to be on top of this issue.
