### ISSUE TITLE
Pyloxone Startup - argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by coreGreenberet** [JoDehli/PyLoxone#172]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen2
**Which software version does your loxone use?**
13.1.11.17
**How did you install HomeAssistant? Over Hassio or manual install?**
HASSIO
**Which Version do you use of HomeAssistant?**
  - Home Assistant 2023.3.3 
  - Supervisor 2023.03.1 
  - Operating System 9.5 
  - Frontend 20230309.0 - latest 
  - PyLoxone 0.5.0b3
**Describe the bug**
Pyloxone isn't starting.
I don't know when exactly this error has started, as I've updated pyloxone and HomeAssistant recently.
I've tried to reinstall&reconfigure the integration, but nothing seems to work. 
I've also tried to reconfigure the settings with dns.loxonecloud.com/<SN> with HTTP&HTTPS.
Normally it is working just with the internal IP:80

**Paste the error log with the following settings:**
```
2023-03-13 10:12:16.124 DEBUG (MainThread) [custom_components.loxone] Error while loading token...
2023-03-13 10:12:16.124 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 264, in async_setup_entry
    if "_token" in token:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by JoDehli** [comment]
@coreGreenberet if you have issues please do not use the beta version. Go back to the newest stable version.

**Comment by coreGreenberet** [comment]
I've just tried it again with 0.4.3. It just did start correctly again.

I thought the beta version is here for tests. And if there is an issue we should report it, so that the problems won't happen in the stable release

**Comment by JoDehli** [comment]
@coreGreenberet how did you downgrade? If you downgraded with hacs do it again. I always need to do it twice in a row to really downgrade.  If you do it only once it is still the beta.

**Comment by JoDehli** [comment]
@coreGreenberet do you still have the problem?

**Comment by coreGreenberet** [comment]
No after the downgrade it was working fine again. I also just had to install it once.

**Comment by JoDehli** [comment]
@coreGreenberet normally if you upgrade to a bets version from the newest stable version this  error should not be there. The token file has changed and in the newest stable I support both. And on the beta branch only the new format.
