### ISSUE TITLE
Number of digits in analog sensors

### ISSUE THREAD

**Issue by tanker11** [JoDehli/PyLoxone#174]
I have upgraded from 0.4.1 to 0.4.3 and something changed with the number of digits reported from Loxone to HA.
Namely, in 0.4.1, it respected the number of digits of the analog sensors according to the setting in Loxconfig.
For example: if I set the Display->Unit to <v.1>°C in Loxconfig, then I have a XX.X°C format, so one decimal digit in Home Assistant.
If I upgrade to 0.4.3, it has as many digits as it has in the original variable within the miniserver.

Is it something intentionally done and if yes, how to fix it?

HA version: 2023.2.4 (should it be upgraded?)

**Comment by JoDehli** [comment]
The formatting will no longer read from the loxone. If you upgrade to the newest beta release the Temperature should be formatted by default with one digit. And you also get the option in HA to easily override it for example to 3 digits if you want.

**Comment by tanker11** [comment]
OK, noted to work a little bit on the precision via the HA GUI.

**Comment by tanker11** [comment]
With this situation I have a bit of problem: due to fine tuning on the Assist, sometimes I need to rename the areas within Loxconfig. For that to be reloaded within HA, I need to remove and add again the PyLoxone integration. After that, all analog sensor precision setting is gone... :/
Is there a way to avoid it? I have numerous sensors reporting their value from Loxone into HA.

**Comment by tanker11** [comment]
Wow, that would mean a lot of manual work, double the number of my sensors,
replace the references in all record service and graphs... :/
And I do not really trust the GUI based templates if they will or will not
be gone after a later upgrade. So I am a bit reluctant to do so.

BTW, the sensor class is OK, and the digits are not, see below:


[image: image.png]


Joachim D. ***@***.***> ezt írta (időpont: 2023. szept. 28.,
Cs, 16:32):

**Comment by JoDehli** [comment]
@tanker11 First of I do not see any picture but I believe you if you say that the sensor type is right and the number of digits are wrong.

For the templates I do not mean GUI templates.  You can create templates sensor without using the gui and they stay the same even if you do a complete new install. 

Other than that I can not improve it in pyloxone. On my system every sensor which I mapped right has the right format. So all temp sensors has the same numbers of digits and the right icon and unit.

**Comment by tanker11** [comment]
Hi, yes, it was what I ment by the pic, sorry for not enclosing correctly.

OK, so it means when I set a <v.1>°C for a temperature sensor, your code
correctly hands over the class (and icon), but does not do anything with
the digits, all available digits are sent over to HA, not only one like in
this example.

In such case, because I have proof that the despite the class the digits
are not defaulted to one digit in case of temp, I need to go to HA
developers, I guess.

Thanks

Joachim D. ***@***.***> ezt írta (időpont: 2023. okt. 1., V,
13:57):

**Comment by JoDehli** [comment]
@tanker11 I think I know what is the mistake. I will check something.

**Comment by JoDehli** [comment]
@tanker11 no my idea was not right. I checked the format evaluation for °C and this should work. If not I can not reproduce the error with the digits.

**Comment by tanker11** [comment]
@JoDehli , oh, I hoped there was a reason.
Including the pic again, I hope this time it is added correctly:

![image](https://github.com/JoDehli/PyLoxone/assets/32165691/e36c6603-5b92-4d83-ba37-6b7e5fe33acf)


So you suggest what I see is not correct - namely that the class is temperature and the unit_of_measurement is °C, so it should be defaulted to 1 digit?

**Comment by JoDehli** [comment]
@tanker11 this is what I do not understand 3hy it is not one digit. The formatting is done by homeassistant not oy pyloxone. Can you try a fresh install on a laptop or pc and test it is it the same with a new install. I had some issues with sensors which were created with older versions of home hassistant.

**Comment by tanker11** [comment]
Quickly created a new install (2023.10) on a VirtualBox, added HACS, added PyLoxone and connected.
Same...

![image](https://github.com/JoDehli/PyLoxone/assets/32165691/821f2b10-7d66-49bc-960b-e8f42f885a69)

Cannot it be the issue with the decimal character ('.' vs ',')?
Or shall I check anything on Loxconfig side?

**Comment by JoDehli** [comment]
@tanker11 I think I solved it. Can you try the latest source code from the master branch?  I guess you do not use a beta release. If you do use a beta you must wait. 

I hope you can download the code and paste it in your custom components folders. If not I make a version this weekend and you can download it via hacs.

**Comment by tanker11** [comment]
Wow, thanks! I could download the source, but will have no time until Sat
afternoon, so take your time!

Joachim D. ***@***.***> ezt írta (időpont: 2023. okt. 5., Csü
21:37):

**Comment by tanker11** [comment]
Checked today with the code from master branch and it works for the temp
values! Seemingly all of them are in the expected 1 decimal format.

Joachim D. ***@***.***> ezt írta (időpont: 2023. okt. 5., Cs,
21:37):

**Comment by JoDehli** [comment]
@tanker11 this solution works for temp and some other units like watt etc but not for humidity for example. There I have the problem that I cannot guess the unit and sensor type from the unit format because % can stand for humidity and also for battery. 

I have no idea how to implement it that it is working correctly. Maybe the category type from loxone can be used. But that can be defined by the user so there is no guarantee that it matches every time.

**Comment by tanker11** [comment]
Indeed, % is not limited in precision.
Well, category is a good idea, but could be so many different names by the
user. In my case a value for buffer tank charged is in the 'Hot Water'
category.
Cannot the setting of the <v.1> in the Display->Unit under Loxconfig be
used somehow? There the user already set the favoured precision so it would
be a good aid to find out what he/she needs. (I am not aware of the code
details, so this is why I suggest without knowing if it is possible or not).

Joachim D. ***@***.***> ezt írta (időpont: 2023. okt. 10., K,
11:02):

**Comment by JoDehli** [comment]
@tanker11 yes that is what I also thought about. But for this I need a little bit of time which I do not have at the moment. But I look at it next time I am working on pyloxone.

**Comment by JoDehli** [comment]
@tanker11 can you test the newest release? There I tried to get the precision also from the humidity and other units.

**Comment by tanker11** [comment]
Yes, it seems working. :)
Not sure to what extent you could go. I guess (as I can see) the % is not
yet handled, right?



Joachim D. ***@***.***> ezt írta (időpont: 2023. okt. 15., V,
17:04):

**Comment by JoDehli** [comment]
@tanker11 which %is not handled. 5he precision should be set but the type is not net to for example humidity. Only the precision should set right.

**Comment by tanker11** [comment]
Sorry for not being clear enough.
In my project I use some sensors like a valve opened for a certain xx%
And as I can see, the majority of the units are handled, as you wrote, but
the precision of the % unit (which is applicable for many things like
humidity, or proportion of something) is not limited to any precision. So
the setting of the displaying in Loxconfig, like <v.1> for one digit
precision is not fetched (yet?).

Joachim D. ***@***.***> ezt írta (időpont: 2023. okt. 16., H,
9:07):

**Comment by JoDehli** [comment]
@tanker11 I still don't understand what is not working. Actually, all float values should be converted and the decimal places should be recognised if the unit does not appear in my list of known units. So also the percentage values. Can you send me an example (maybe with a screenshot of the Loxone Config with the settings) so I can configure a virtual sensor on my system. And maybe with plausible values that can occur with you.

**Comment by tanker11** [comment]
@JoDehli , please see some screenshots below.
PyLoxone version: 0.5.0b11
Loxconfig version: 14.3.8.28

Example values in HA:
<img width="544" alt="image" src="https://github.com/JoDehli/PyLoxone/assets/32165691/d0fd6289-511f-496f-97f0-583a19565ad4">

Equivalent within Loxconfig:
<img width="775" alt="image" src="https://github.com/JoDehli/PyLoxone/assets/32165691/90bc80f9-6eb5-4526-84a3-d348d60f8c67">

As you can see this is a Memeory Flag in Loxconfig that is exposed with 'Use in User Interface' tick in the settings of the Periphery.
Let me know what else you may need for the investigation.

**Comment by JoDehli** [comment]
@tanker11 and what is shown on the gui/frontend for this sensors? Are the digits numbers the same? I have sensors which has a different amount of digits it the entites view and on the gui/frontend

**Comment by tanker11** [comment]
It is the same on the GUI, same number of digits there.

Joachim D. ***@***.***> ezt írta (időpont: 2023. nov. 7., K,
10:48):

**Comment by JoDehli** [comment]
@tanker11 at the moment I can do nothing to improve this as I really do not understand what you want to achieve. The best would be to format it on loxone right and pass only the rounded values to loxone. For example with a formula. As it is only for a few values it should not big deal.

**Comment by tanker11** [comment]
I get that you did everything on your side to reduce occurring the too many
digits issue.
My original suggestion was not to decide the precision based on the unit,
but on the setting at Loxconfig side ( <v> means 0 digit, <v.2> meand 2
digits etc.) but as I understand this is out of your intention. If so, you
can close the issue and thanks for supporting and maintaining the project.

Joachim D. ***@***.***> ezt írta (időpont: 2023. nov. 7., K,
13:31):
