### ISSUE TITLE
Loxone services not available/gone

### ISSUE THREAD

**Issue by pissten** [JoDehli/PyLoxone#177]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen.1
**Which software version does your loxone use?**
Version 14.0.3.28
**How did you install HomeAssistant? Over Hassio or manual install?**
Docker
**Which Version do you use of HomeAssistant?**
2023.4.6
**Describe the bug**
Seems like there is no more services for the loxone binding?
I have several automations set up for the service: loxone_websocket_event_command

When I browse the services in the developer tab, there is no services present for Loxone :/

**Paste the error log with the following settings:**
```
The automation "Netatmo Temp_to_loxone" (automation.netatmo_stue_temp_to_loxone) has an action that calls an unknown service: loxone.event_websocket_command
```

**Comment by pissten** [comment]
Seems like the services were gone, beacuse the loxone integration had stopped with an error. Restartet the integration, and service was back.. Maybe my issue regarding integration stopping, is similar to issue already reported by @arjenvrh

**Comment by JoDehli** [comment]
@pissten which version of pyloxone do you use?

**Comment by JoDehli** [comment]
@pissten can you install the 0.4.3 (latest stable version). But make sure that you really installed this version. I had to delete the loxone folder in the custom components folder manually and then install the 0.4.3 over hacs. I could not downgrade it over hacs. I do not know why. 

And then set your logger in homeassistant like this: 

```yaml
logger:
  default: critical
  logs:
    homeassistant: critical
    custom_components.loxone: debug
```

It the error occurs again you can paste the last lines from the log here. 
I do not have any problems with pyloxone at all. But I do not use the websocket command often on my system. 
So it is very difficult to find the error or the problem on your system.

**Comment by JoDehli** [comment]
@pissten I answered the other issue. 
https://github.com/JoDehli/PyLoxone/issues/176#issuecomment-1525548811

You can also try the newest beta if you want. For the other issue I think I found and solved the problem.
