### ISSUE TITLE
Get Loxone binding into HA

### ISSUE THREAD

**Issue by tgurr** [JoDehli/PyLoxone#18]
Have you considered re-opening https://github.com/home-assistant/core/pull/9706 now that you seem to be back using Home Assistant (and are probably more used to git)?

**Comment by JoDehli** [comment]
I had so much trouble and no help from the Home-assistant folks that I not go to integrate it in the main branch. I think with the possibility to to install it with hacs there is no real advantage. And for a serious integration in Home-assistant the binding should complete separated from the loxone communication.
