### ISSUE TITLE
Incorrect entity type for Loxone Touch temperature

### ISSUE THREAD

**Issue by zamojski** [JoDehli/PyLoxone#180]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Miniserver Gen2

**Which software version does your loxone use?**
Latest for 6th of April 2023. I don't know how to check it without Loxone Config.

**Which Version do you use of HomeAssistant?**
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1

**Describe the bug**
Room temperature entities imported from Loxone Touch buttons has incorrect type (device_class?) and cannot be used on temperature charts together with valid temperature entities. For the same Loxone Touch the humidity parameter is detected correctly.

All of these entities are visible like like sensor.temperatura_4:
![obraz](https://github.com/JoDehli/PyLoxone/assets/12007817/83aa9339-970a-44e6-8909-d85e4a0a0a81)
These cannot have a unit assigned, while some other entries, here from ventilation system, have correct type (sensor_temperatura_nawiewu).

I've tried to overwrite it from `/config/configuration.yaml` like this:
```yaml
sensor:
  - name: "Temperatura Kuchnia"
    platform: loxone
    uuidAction: "1a30a7fb-01d2-08bc-ffff720f38b2956a"
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "total"
```

But then I see an error in the log:
`Platform loxone does not generate unique IDs. ID 1a30a7fb-01d2-08bc-ffff720f38b2956a already exists - ignoring sensor.temperatura_4`

Entries in `/data/LoxAPP3.json`:
```json
    "1a30a7fb-01d2-08bc-ffff720f38b2956a": { // Loxone Touch temperature
      "name": "Temperatura",
      "type": "InfoOnlyAnalog",
      "uuidAction": "1a30a7fb-01d2-08bc-ffff720f38b2956a",
      "room": "1a30a3cc-002b-7ead-ffff720f38b2956a",
      "cat": "1a30a3cc-0007-7dd6-ffff720f38b2956a",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "defaultIcon": null,
      "restrictions": 0,
      "details": {
        "jLockable": false,
        "format": "%.1f°"
      },
      "states": {
        "value": "1a30a7fb-01d2-08bc-ffff720f38b2956a",
        "error": "1a30a7fb-01d2-08bb-ffff31438a32f4eb"
      }
    },
    "1a30a7fb-01d2-08c0-ffff720f38b2956a": { // Loxone Touch humidity
      "name": "Wilgotność powietrza",
      "type": "InfoOnlyAnalog",
      "uuidAction": "1a30a7fb-01d2-08c0-ffff720f38b2956a",
      "room": "1a30a3cc-002b-7ead-ffff720f38b2956a",
      "cat": "1a30a3cc-0009-7e0c-ffff720f38b2956a",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "defaultIcon": "IconsFilled/humidity.svg",
      "restrictions": 0,
      "details": {
        "jLockable": false,
        "format": "%.0f%%"
      },
      "states": {
        "value": "1a30a7fb-01d2-08c0-ffff720f38b2956a",
        "error": "1a30a7fb-01d2-08bf-ffff31438a32f4eb"
      }
    },
    "1a41de8a-037a-81ca-ffff720f38b2956a": { // Ventilation system temperature
      "name": "Temperatura nawiewu",
      "type": "InfoOnlyAnalog",
      "uuidAction": "1a41de8a-037a-81ca-ffff720f38b2956a",
      "room": "1a30a3cc-002b-7f21-ffff720f38b2956a",
      "cat": "1a30a3cc-0008-7dda-ffff720f38b2956a",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "defaultIcon": "IconsFilled/thermometer.svg",
      "restrictions": 17,
      "details": {
        "jLockable": false,
        "format": "%.1f°C"
      },
      "states": {
        "value": "1a41de8a-037a-81ca-ffff720f38b2956a",
        "error": "1a41de8a-037a-81c9-ffffd3f6531e8c81"
      }
    },
```

Is this something that can be handled in Home Assistant or should I change it somehow in Loxone Config?

**Comment by JoDehli** [comment]
@zamojski why do you not give the Temperatura an valid format string like for the other temperature sensor? You can define it in loxone. Important is that you use the °C as unit.

**Comment by zamojski** [comment]
Will it then be correctly recognized? It wasn't me who did the
configuration in Loxone, so I cannot judge why it's this way.

śr., 10 maj 2023, 20:18 użytkownik Joachim D. ***@***.***>
napisał:

**Comment by JoDehli** [comment]
@zamojski have you tried it as succeeded?

**Comment by zamojski** [comment]
I've requested to change the configuration. Let's wait a while.

**Comment by zamojski** [comment]
@JoDehli Looks fine after setting the units. Thanks for help!
