### ISSUE TITLE
ValueError: Sensor  has device class None, state class none unit and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)

### ISSUE THREAD

**Issue by brechtvhb** [JoDehli/PyLoxone#181]
Since upgrading to HA 2022.5

I receive this error for manual configured sensors:

2023-05-10 22:17:37.465 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
numerical_value = float(value) # type:ignore[arg-type]
ValueError: could not convert string to float: 'none'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
raise ValueError(
ValueError: Sensor sensor.entrance_hall_i5_state has device class None, state class None unit and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: none (<class 'str'>)

Sensor is configured as such:

```
    - platform: loxone
      name: "entrance_hall_i3_state"
      uuidAction: "1a2f9ca2-028c-22ed-fffffb405711d3f1"
```

The sensor in loxone is actually a string (function block: status) and should not be converted to an integer.

I've tried messing with device classes & state classes but wasn't able to solve the issue.
Most sensible option would be to define the device_class as enum. But then I have to set the "options" param too which is not supported in pyloxone.

'Cannot quick reload all YAML configurations because the configuration is not valid: Invalid config for [sensor.loxone]: [options] is an invalid option for [sensor.loxone]. Check: sensor.loxone->options. (See ?, line ?).'

**Comment by brechtvhb** [comment]
![image](https://github.com/JoDehli/PyLoxone/assets/330772/0455c4cd-147d-4d86-b718-e6dbaf5170f6)
When looking up the state in HA the unit_of_measurement is empty, (instead of none?) this might be the cause of the problem.

**Comment by brechtvhb** [comment]
Solved by explicityly setting unit_of_measurement to none:

```
    - platform: loxone
      name: "office_i3_state"
      uuidAction: "1a2f9c55-00b3-8e75-ffffdda045b8a7b3"
      unit_of_measurement: "none"
```

**Comment by JoDehli** [comment]
@brechtvhb maybe it is a good idea the set the unit of measurement as a required for a custom sensor or at least set it default to none.

**Comment by brechtvhb** [comment]
I think it would be best to set the default to none instead of an empty string as the unit of measurement has no use if device class is none.
