### ISSUE TITLE
Send data thru http not only websocket. 

### ISSUE THREAD

**Issue by johny-mnemonic** [JoDehli/PyLoxone#184]
Miniserver: Gen1
Loxone: 14.1.5.9
Hassio OS 10.3
HomeAssistant: 2023.7.2

After the error below all automations trying to write to Loxone are failing like this:
`2023-07-15 08:48:19.360 WARNING (MainThread) [homeassistant.components.automation.loxone_set_pc_power] Loxone - Set PC power: Already running`
Seems like one call gets stuck rendering HA to think the automation is still running so it is unable to run consequent automations.

Log:
```
2023-07-15 08:48:07.398 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Miniserver._run_in_background.<locals>.handle_errors(<Task finishe... (char 86)'))>) at /config/custom_components/loxone/pyloxone_api/miniserver.py:269
Traceback (most recent call last):
File "/config/custom_components/loxone/pyloxone_api/message.py", line 32, in __init__
self._parsed: dict[Any, Any] = json.loads(response)
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 87 (char 86)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/config/custom_components/loxone/pyloxone_api/miniserver.py", line 274, in handle_errors
_ = task.result()
^^^^^^^^^^^^^
File "/config/custom_components/loxone/pyloxone_api/miniserver.py", line 476, in _receive_and_add_to_queue
message = parse_message(message_data, header.message_type)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/loxone/pyloxone_api/message.py", line 239, in parse_message
return Class_Table[message_type](message)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/loxone/pyloxone_api/message.py", line 108, in __init__
ll_message = LoxoneResponse(message)
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/loxone/pyloxone_api/message.py", line 41, in __init__
raise ValueError(exc) from exc
ValueError: Unterminated string starting at: line 1 column 87 (char 86)
```

Could it be related to these warnings?
```
2023-07-15 00:38:32.325 WARNING (Recorder) [homeassistant.components.recorder.db_schema] Event data for loxone_event exceed maximum size of 32768 bytes. This can cause database performance issues; Event data will not be stored
2023-07-15 08:52:04.411 WARNING (Recorder) [homeassistant.components.recorder.db_schema] Event data for loxone_event exceed maximum size of 32768 bytes. This can cause database performance issues; Event data will not be stored
```
I mean, could the received Miniserver response be so big that it is bigger than the variable you use for storing it hence ending as `unterminated string` ?

**Comment by johny-mnemonic** [comment]
OK 🤔
Would you have an example ho to do that especially on HA side?
I have seen your old post about [sending data to input_number](https://community.home-assistant.io/t/custom-input-number-error-unable-to-find-referenced-entities-input-number-pyloxone/224432), but I see no reply to it. Not sure if this is even related though 🤷

**Comment by JoDehli** [comment]
@johny-mnemonic this post is not related to your problem. 

I found a nice video which describes a virtual input. I think this is a good starting point. 
https://youtube.com/watch?v=P2rohiZiec0&feature=share

You can send to this virtual input data to your loxone and can parse the data and do whatever you want.
This has nothing to do with homeassistant in the first place. You can sent this data from anywhere where you 
have access to your loxone. 

If you understand the virtual input concept you can use for example nodered to sent to this virtual input. 
Or you can use HomeAssistant but I would use Nodered. I had this in use several years with not problem. I do not 
use it anymore because I replaced some sensor which does not need the virtual inputs anymore. 

With the same concept I sent my wind-speed to my neighbor. This is working also very well. I is good for value data which changes very often because the loxone only receives the data and sends nothing back.

**Comment by johny-mnemonic** [comment]
Thanks @JoDehli 
I hoped you know a way how to do that directly in HA as I never tried to mess with Nodered but maybe it's time to tackle the beast ;-)

**Comment by JoDehli** [comment]
@johny-mnemonic I know to send a udp message from Linux so you I know it how to to that I ha. I think it is more difficult than in nodered but if you want you can sent a message like this in the command line

echo 'hello' | nc -u 192.168.1.225 1234

This should send hello to the port 1234 to the IP.

You can make can make a automation on a value change and the automation triggers a script where you can execute this command. Of course you must replace the hello with your value. For this you find lot of examples on the net.

**Comment by johny-mnemonic** [comment]
Yeah, [there is an discussion](https://community.home-assistant.io/t/wth-isn-t-udp-comms-integrated-in-ha/220261) about this on HA forum. Sending static value is easy but the trouble is how to provide HA variable to that shell script.

**Comment by JoDehli** [comment]
@johny-mnemonic I would do it like this with a script and arguments.


https://community.home-assistant.io/t/shell-command-submit-values-from-ha-to-shell-script/404621


The last reply should do the job. Not tested!

**Comment by johny-mnemonic** [comment]
@JoDehli thanks for pushing me in the right direction.
This is what works for virtual input and most probably the second command works for UDP as well (not tested yet).

configuration.yaml :
```
shell_command:
  loxone_udp: echo '"{{ value}}"' | nc -u loxone "{{ port }}"
  loxone_vi: curl -X GET -H "Authorization:Basic xxxREDACTEDxxx" http://loxone/dev/sps/io/"{{ vi_name }}"/"{{ value}}"
```

automations.yaml :
```
alias: Loxone - L23 power
description: ""
trigger:
  - platform: state
    entity_id:
      - input_number.l23_power
condition: []
action:
  - service: shell_command.loxone_vi
    data_template:
      vi_name: VI##
      value: "{{states(\"input_number.l23_power\")}}"
mode: single
```

**Comment by JoDehli** [comment]
@johny-mnemonic so as I got it right it is working now with this script and automation? 

But I have a idea. I could implement a service to send data to loxone not thru the websocket but thru the http with the http://loxone/dev/sps/io/ address. I already know everything like the password an username. And I can call the http get method for this. This should makes things even easier. 

If I have time I can implement it. Maybe you can try it with your setup.

**Comment by johny-mnemonic** [comment]
Interesting. I thought that going through websocket is a lighter way than going through REST api (http) and the lightest should be UDP. Unfortunately for UDP you need a bit more advanced config both on Loxone and HA side.

I finally made UDP working but it is certainly not straightforward.

You need a shell/python script as `shell_command` doesn't support pipes. And there is not much point going with python script as standard `python_scripts` integration doesn't support imports, so you would just execute netcat from python anyway.
```
loxone_udp.sh
#/bin/sh
echo "$1" | nc -u -w1 10.1.1.50 7151
```

```
shell_command:
  loxone_udp: /bin/sh loxone_udp.sh "{{ value }}"
```
Then you can use it from automation like this:
```
service: shell_command.loxone_udp
data_template:
  value: "pcpower{{states.sensor.pc_power.state | float(0) * 0.001 | float }}"
```

**Comment by JoDehli** [comment]
@johny-mnemonic this looks like a very good solution. When you have done the initial setup it is very simple to use. You even can pass the port by argument if you have another port which you want to send data.

For clarification:
yes it is easier to send data over websocket if you already have a connection. But your problem is that the message which comes back as a response of a value sent has errors or cannot be parsed to json. We had that in the past that the response had errors or was not well formatted. To evaluate the message sometimes a clean up is needed. The problem is that I cannot reproduce this on my system so it would be very easy to deal with it when I know what the message looks like which causes this error.

**Comment by johny-mnemonic** [comment]
I see.

I originally had the port as a parameter, but then I realized you can create many UDP commands for single UDP input in Loxone, so I made it static.
