### ISSUE TITLE
Unable to read power and energy from Smart Sockets Air devices

### ISSUE THREAD

**Issue by bittenauerchristoph** [JoDehli/PyLoxone#185]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen1
**Which software version does your loxone use?**
Firmware: 12.2.11.5
**How did you install HomeAssistant? Over Hassio or manual install?**
Hassio
**Which Version do you use of HomeAssistant?**
2023.5.4
**Describe the bug**
I have a miniserver with some Smart Sockets Air devices and i an unable to read power and energy from the devices 

- Whenever i try to automatically detect them (no manual sensor configuration)

- Whenever i try to manually configure the energy sensor via the uuid

I've added logs for both scenarios

**Log without manual sensor configuration**

> 2023-07-19 14:30:14.609 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-07-19 14:30:14.612 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration solarman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-07-19 14:30:14.614 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration loxone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-07-19 14:30:43.716 DEBUG (MainThread) [custom_components.loxone] starting loxone sensor...
> 2023-07-19 14:30:43.716 DEBUG (MainThread) [custom_components.loxone] starting loxone binary_sensor...
> 2023-07-19 14:30:43.717 DEBUG (MainThread) [custom_components.loxone] starting loxone switch...
> 2023-07-19 14:30:43.717 DEBUG (MainThread) [custom_components.loxone] starting loxone cover...
> 2023-07-19 14:30:43.717 DEBUG (MainThread) [custom_components.loxone] starting loxone fan...
> 2023-07-19 14:30:43.717 DEBUG (MainThread) [custom_components.loxone] starting loxone light...
> 2023-07-19 14:30:43.717 DEBUG (MainThread) [custom_components.loxone] starting loxone climate...
> 2023-07-19 14:30:43.717 DEBUG (MainThread) [custom_components.loxone] starting loxone alarm_control_panel...
> 2023-07-19 14:30:43.798 DEBUG (MainThread) [custom_components.loxone.api] try to read token
> 2023-07-19 14:30:43.798 DEBUG (MainThread) [custom_components.loxone.api] try to get_token_from_file
> 2023-07-19 14:30:43.798 DEBUG (MainThread) [custom_components.loxone.api] try to get public key: http://192.168.0.11/jdev/sys/getPublicKey
> 2023-07-19 14:30:44.055 DEBUG (MainThread) [custom_components.loxone.api] get_public_key successfully...
> 2023-07-19 14:30:44.397 DEBUG (MainThread) [custom_components.loxone.api] init_rsa_cipher successfully...
> 2023-07-19 14:30:44.400 DEBUG (MainThread) [custom_components.loxone.api] generate_session_key successfully...
> 2023-07-19 14:30:44.931 DEBUG (MainThread) [custom_components.loxone.api] parse_loxone_message successfully...
> 2023-07-19 14:30:44.931 DEBUG (MainThread) [custom_components.loxone.api] acquire_tokend
> 2023-07-19 14:30:44.939 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
> 2023-07-19 14:30:44.987 DEBUG (MainThread) [custom_components.loxone.api] parse_loxone_message successfully...
> 2023-07-19 14:30:44.990 DEBUG (MainThread) [custom_components.loxone.api] hash_credentials successfully...
> 2023-07-19 14:30:44.991 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
> 2023-07-19 14:30:45.133 DEBUG (MainThread) [custom_components.loxone.api] parse_loxone_message successfully...
> 2023-07-19 14:30:45.136 DEBUG (MainThread) [custom_components.loxone.api] save_token successfully...
> 2023-07-19 14:30:45.137 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
> 2023-07-19 14:30:45.169 DEBUG (MainThread) [custom_components.loxone] starting loxone scene...
> 2023-07-19 14:30:45.182 INFO (MainThread) [custom_components.loxone] loxone discovered
> 2023-07-19 14:30:45.324 ERROR (MainThread) [custom_components.loxone] Can't create group 'Loxone Switches' with error: 'group_registry'
> 2023-07-19 14:30:52.742 ERROR (MainThread) [custom_components.loxone] Can't create group 'Loxone Group' with error: 'group_registry'
> 2023-07-19 14:30:52.781 DEBUG (MainThread) [custom_components.loxone.api] message [type:2]):{'0b7341dd-012b-0284-ffff6f4bfad385ea': 5.0, '0b7341dd-013b-0296-ffff6f4bfad385ea': 314.0, '0b7341dd-013b-0299-ffff6f4bfad385ea': 1245.0, '1846a969-00f3-1cbd-ffff504f94107b08': 1.0, '1846a969-00f1-1cb9-ffff504f94107b08': 1.0, '1846ad77-00fe-a244-ffff6f4bfad385ea': 27.1, '1846ad77-00fe-a243-ffff77baad11dd81': 0.0, '1846af5b-02ee-fa0c-ffff0553893824a5': 0.0, '1847449a-001b-3df7-ffffe20673d42b65': 1.0, '1846ae33-02df-b39d-ffff01a68ec01a26': 0.0, '1846ae33-02df-b39c-ffff01a68ec01a26': 198.67991700000007, '1846b189-0143-1b45-ffff81611c8663aa': 0.0, '1846b189-0143-1b44-ffff81611c8663aa': 11.896002999999999, '1846b153-0200-1229-ffff6f4bfad385ea': 26.6, '1846b153-0200-1228-ffffc31badd89fa5': 0.0, '1846a96f-012a-1d5d-ffff504f94107b08': 0.0, '1846a96f-0130-1d62-ffff504f94107b08': 458926313454.0, '1847449a-001b-3dfa-ffffe20673d42b65': 0.0, '1847449a-001b-3dfb-ffffe20673d42b65': 0.0}
> 2023-07-19 14:30:53.092 DEBUG (MainThread) [custom_components.loxone.api] message [type:3]):{'0c70be7c-03a8-bed6-ffff7a96e57ecf79': '[]', '0c70be7c-03a8-bed5-ffff7a96e57ecf79': '[]', '1846a967-0373-1b0d-ffff504f94107b08': '[]', '1846a967-0373-1b0e-ffff504f94107b08': '["hsv(25,96,50)","hsv(24,95,80)","hsv(337,94,50)"]', '1846a967-0373-1b0f-ffff504f94107b08': '2023-07-19 14:30:46 +02:00:00', '1846aa0c-03b0-7cba-ffff504f94107b08': '', '1846aa0c-03b0-7cbb-ffff504f94107b08': '{}', '1846aa0c-03b0-7cbc-ffff504f94107b08': '{}', '9846af5b-02ee-fa08-ffff0553893824a5': '', '9847449a-001b-3df3-ffffe20673d42b65': '', '1846a96f-012a-1d5e-ffff504f94107b08': ''}
> 2023-07-19 14:30:53.125 DEBUG (MainThread) [custom_components.loxone.api] message [type:7]):{}
> 2023-07-19 14:31:04.877 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
> 2023-07-19 14:31:24.891 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
> 2023-07-19 14:31:44.892 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
> 2023-07-19 14:32:04.907 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
> 2023-07-19 14:32:24.923 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
> 2023-07-19 14:32:44.926 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
> 2023-07-19 14:33:04.941 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
> 
> 2023-07-19 14:33:24.957 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}
> 2023-07-19 14:33:44.971 DEBUG (MainThread) [custom_components.loxone.api] message [type:1]):{}

**Log with manual sensor configuration via yaml:**

> 2023-07-19 13:29:07.711 DEBUG (MainThread) [custom_components.loxone] starting loxone sensor...
> 2023-07-19 13:29:07.711 DEBUG (MainThread) [custom_components.loxone] starting loxone binary_sensor...
> 2023-07-19 13:29:07.711 DEBUG (MainThread) [custom_components.loxone] starting loxone switch...
> 2023-07-19 13:29:07.711 DEBUG (MainThread) [custom_components.loxone] starting loxone cover...
> 2023-07-19 13:29:07.712 DEBUG (MainThread) [custom_components.loxone] starting loxone fan...
> 2023-07-19 13:29:07.712 DEBUG (MainThread) [custom_components.loxone] starting loxone light...
> 2023-07-19 13:29:07.712 DEBUG (MainThread) [custom_components.loxone] starting loxone climate...
> 2023-07-19 13:29:07.712 DEBUG (MainThread) [custom_components.loxone] starting loxone alarm_control_panel...
> 2023-07-19 13:29:08.038 DEBUG (MainThread) [custom_components.loxone.api] try to read token
> 2023-07-19 13:29:08.038 DEBUG (MainThread) [custom_components.loxone.api] try to get_token_from_file
> 2023-07-19 13:29:08.039 DEBUG (MainThread) [custom_components.loxone.api] try to get public key: http://192.168.0.11/jdev/sys/getPublicKey
> 2023-07-19 13:29:08.207 DEBUG (MainThread) [custom_components.loxone.api] get_public_key successfully...
> 2023-07-19 13:29:08.543 DEBUG (MainThread) [custom_components.loxone.api] init_rsa_cipher successfully...
> 2023-07-19 13:29:08.546 DEBUG (MainThread) [custom_components.loxone.api] generate_session_key successfully...
> 2023-07-19 13:29:09.307 DEBUG (MainThread) [custom_components.loxone.api] parse_loxone_message successfully...
> 2023-07-19 13:29:09.307 DEBUG (MainThread) [custom_components.loxone.api] acquire_tokend
> 2023-07-19 13:29:09.314 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
> 2023-07-19 13:29:19.941 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
> 2023-07-19 13:29:19.943 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
> 2023-07-19 13:29:19.945 WARNING (MainThread) [homeassistant.setup] Setup of schedule is taking over 10 seconds.
> 2023-07-19 13:29:19.947 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
> 2023-07-19 13:29:19.949 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
> 2023-07-19 13:29:19.950 WARNING (MainThread) [homeassistant.setup] Setup of input_button is taking over 10 seconds.
> 2023-07-19 13:29:19.952 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
> 2023-07-19 13:29:19.954 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
> 2023-07-19 13:29:19.956 WARNING (MainThread) [homeassistant.setup] Setup of application_credentials is taking over 10 seconds.
> 2023-07-19 13:29:19.957 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform integration is taking over 10 seconds.
> 2023-07-19 13:29:19.959 WARNING (MainThread) [homeassistant.setup] Setup of script is taking over 10 seconds.
> 2023-07-19 13:29:20.261 DEBUG (MainThread) [custom_components.loxone.api] parse_loxone_message successfully...
> 2023-07-19 13:29:20.266 DEBUG (MainThread) [custom_components.loxone.api] hash_credentials successfully...
> 2023-07-19 13:29:20.268 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
> 2023-07-19 13:29:20.270 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/loxone/__init__.py", line 361, in async_setup_entry
>     res = await miniserver.start_ws()
>   File "/config/custom_components/loxone/miniserver.py", line 126, in start_ws
>     res = await self.api.async_init()
>   File "/config/custom_components/loxone/api.py", line 452, in async_init
>     res = await self.acquire_token()
>   File "/config/custom_components/loxone/api.py", line 731, in acquire_token
>     await self._ws.send(enc_command)
>   File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
>     await self.ensure_open()
>   File "/usr/local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
>     raise self.connection_closed_exc()
> websockets.exceptions.ConnectionClosedOK: received 1000 (OK) normally closed; then sent 1000 (OK) normally closed
> 2023-07-19 13:29:23.302 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform loxone
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
>     numerical_value = int(value)
> ValueError: invalid literal for int() with base 10: 'unknown'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
>     if (state := self.state) is None:
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
>     raise ValueError(
> ValueError: Sensor sensor.loxonetestpower has device class power, state class measurement unit kW and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)
> 2023-07-19 13:29:23.315 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
>     numerical_value = int(value)
> ValueError: invalid literal for int() with base 10: 'unknown'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
>     if (state := self.state) is None:
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
>     raise ValueError(
> ValueError: Sensor sensor.loxonetestpower has device class power, state class measurement unit kW and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)

**Comment by JoDehli** [comment]
@bittenauerchristoph  can you paste your manual setup for a socket?

**Comment by bittenauerchristoph** [comment]
@JoDehli see code below - thanks!

```
- platform: loxone
  name: loxpower1test
  uuidAction: "1846ae33-02df-b39d-ffff01a68ec01a26"
  unit_of_measurement: "kW"
  device_class: "power"
  state_class: "measurement"
```

**Comment by bittenauerchristoph** [comment]
I've also updated the firmware of the miniserver but I'm getting the same results / debug messages

**Comment by JoDehli** [comment]
Can paste the section of the loxone JSON for the entity. But only for the device. do you know what I mean?

**Comment by bittenauerchristoph** [comment]
@JoDehli here is the single entry for the energy and below all confgured entries from the json output:

```
    "1846ae33-02df-b3a8-ffff6f4bfad385ea": {
      "name": "VerbrauchszählerStecker1",
      "type": "Meter",
      "uuidAction": "1846ae33-02df-b3a8-ffff6f4bfad385ea",
      "room": "0b7341dd-01a9-03f0-ffff6f4bfad385ea",
      "cat": "1846a969-0067-1c83-ffff504f94107b08",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "restrictions": 0,
      "details": {
        "jLockable": false,
        "actualFormat": "%.3fkW",
        "totalFormat": "%.1fkWh"
      },
      "states": {
        "actual": "1846ae33-02df-b39d-ffff01a68ec01a26",
        "total": "1846ae33-02df-b39c-ffff01a68ec01a26"
      },
      "statistic": {
        "frequency": 11,
        "outputs": [
          {
            "id": 0,
            "name": "Gesamtverbrauch",
            "format": "%.1fkWh",
            "uuid": "1846ae33-02df-b39c-ffff01a68ec01a26",
            "visuType": 2
          },
          {
            "id": 1,
            "name": "Leistung",
            "format": "%.3fkW",
            "uuid": "1846ae33-02df-b39d-ffff01a68ec01a26",
            "visuType": 0
          }
        ]
      }
    },
```

All configured controls:

```
{
  "controls": {
    "1846ad77-00fe-a244-ffff6f4bfad385ea": {
      "name": "Temperatur Stecker1",
      "type": "InfoOnlyAnalog",
      "uuidAction": "1846ad77-00fe-a244-ffff6f4bfad385ea",
      "room": "0b7341dd-0189-035e-ffff6f4bfad385ea",
      "cat": "0b7341dd-014b-02dc-ffff6f4bfad385ea",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "defaultIcon": "IconsFilled/thermometer.svg",
      "restrictions": 0,
      "details": {
        "jLockable": false,
        "format": "%.1f°"
      },
      "states": {
        "value": "1846ad77-00fe-a244-ffff6f4bfad385ea",
        "error": "1846ad77-00fe-a243-ffff77baad11dd81"
      },
      "statistic": {
        "frequency": 11,
        "outputs": [
          {
            "id": 0,
            "name": "Temperatur Stecker1",
            "format": "%.1f°",
            "uuid": "1846ad77-00fe-a242-ffff77baad11dd81",
            "visuType": 0
          }
        ]
      }
    },
    "1846af5b-02ee-fa0f-ffff6f4bfad385ea": {
      "name": "SmartSoket1",
      "type": "Switch",
      "uuidAction": "1846af5b-02ee-fa0f-ffff6f4bfad385ea",
      "room": "0b7341dd-01a9-03f0-ffff6f4bfad385ea",
      "cat": "1846a969-007b-1c93-ffff504f94107b08",
      "defaultRating": 0,
      "isFavorite": true,
      "isSecured": false,
      "defaultIcon": null,
      "restrictions": 0,
      "details": {
        "jLockable": true
      },
      "states": {
        "jLocked": "9846af5b-02ee-fa08-ffff0553893824a5",
        "active": "1846af5b-02ee-fa0c-ffff0553893824a5",
        "lockedOn": "1b5e38d6-01a1-5124-ffff6f4bfad385ea"
      }
    },
    "1847449a-001b-3df1-ffffe20673d42b65": {
      "name": "SmartSoket2",
      "type": "Switch",
      "uuidAction": "1847449a-001b-3df1-ffffe20673d42b65",
      "room": "0b7341dd-01a9-03f0-ffff6f4bfad385ea",
      "cat": "1846a969-007b-1c93-ffff504f94107b08",
      "defaultRating": 0,
      "isFavorite": true,
      "isSecured": false,
      "defaultIcon": null,
      "restrictions": 0,
      "details": {
        "jLockable": true
      },
      "states": {
        "jLocked": "9847449a-001b-3df3-ffffe20673d42b65",
        "active": "1847449a-001b-3df7-ffffe20673d42b65",
        "lockedOn": "1b5e38d6-01a1-514e-ffffe20673d42b65"
      }
    },
    "1846ae33-02df-b3a8-ffff6f4bfad385ea": {
      "name": "VerbrauchszählerStecker1",
      "type": "Meter",
      "uuidAction": "1846ae33-02df-b3a8-ffff6f4bfad385ea",
      "room": "0b7341dd-01a9-03f0-ffff6f4bfad385ea",
      "cat": "1846a969-0067-1c83-ffff504f94107b08",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "restrictions": 0,
      "details": {
        "jLockable": false,
        "actualFormat": "%.3fkW",
        "totalFormat": "%.1fkWh"
      },
      "states": {
        "actual": "1846ae33-02df-b39d-ffff01a68ec01a26",
        "total": "1846ae33-02df-b39c-ffff01a68ec01a26"
      },
      "statistic": {
        "frequency": 11,
        "outputs": [
          {
            "id": 0,
            "name": "Gesamtverbrauch",
            "format": "%.1fkWh",
            "uuid": "1846ae33-02df-b39c-ffff01a68ec01a26",
            "visuType": 2
          },
          {
            "id": 1,
            "name": "Leistung",
            "format": "%.3fkW",
            "uuid": "1846ae33-02df-b39d-ffff01a68ec01a26",
            "visuType": 0
          }
        ]
      }
    },
    "1846b189-0143-1b3a-ffff81611c8663aa": {
      "name": "VerbrauchszählerStecker2",
      "type": "Meter",
      "uuidAction": "1846b189-0143-1b3a-ffff81611c8663aa",
      "room": "0b7341dd-01a9-03f0-ffff6f4bfad385ea",
      "cat": "1846a969-0067-1c83-ffff504f94107b08",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "restrictions": 0,
      "details": {
        "jLockable": false,
        "actualFormat": "%.3fkW",
        "totalFormat": "%.1fkWh"
      },
      "states": {
        "actual": "1846b189-0143-1b45-ffff81611c8663aa",
        "total": "1846b189-0143-1b44-ffff81611c8663aa"
      },
      "statistic": {
        "frequency": 11,
        "outputs": [
          {
            "id": 0,
            "name": "Gesamtverbrauch",
            "format": "%.1fkWh",
            "uuid": "1846b189-0143-1b44-ffff81611c8663aa",
            "visuType": 2
          },
          {
            "id": 1,
            "name": "Leistung",
            "format": "%.3fkW",
            "uuid": "1846b189-0143-1b45-ffff81611c8663aa",
            "visuType": 0
          }
        ]
      }
    },
    "1846b153-0200-1229-ffff6f4bfad385ea": {
      "name": "Temperatur Stecker2",
      "type": "InfoOnlyAnalog",
      "uuidAction": "1846b153-0200-1229-ffff6f4bfad385ea",
      "room": "0b7341dd-01a9-03f0-ffff6f4bfad385ea",
      "cat": "0b7341dd-014b-02dc-ffff6f4bfad385ea",
      "defaultRating": 0,
      "isFavorite": false,
      "isSecured": false,
      "defaultIcon": "IconsFilled/thermometer.svg",
      "restrictions": 0,
      "details": {
        "jLockable": false,
        "format": "%.1f°"
      },
      "states": {
        "value": "1846b153-0200-1229-ffff6f4bfad385ea",
        "error": "1846b153-0200-1228-ffffc31badd89fa5"
      },
      "statistic": {
        "frequency": 11,
        "outputs": [
          {
            "id": 0,
            "name": "Temperatur Stecker2",
            "format": "%.1f°",
            "uuid": "1846b153-0200-1227-ffffc31badd89fa5",
            "visuType": 0
          }
        ]
      }
    }
```

**Comment by JoDehli** [comment]
@bittenauerchristoph can you manually update your pyloxone installation by downloading the source and extract it you your custom components folder? Do you know how to do that? I changed the default value of the custom sensor. Now it should work for your setup. Hopefully I does not screw up other users setup. ;-)

**Comment by bittenauerchristoph** [comment]
@JoDehli it worked - thank you very much!
I just changed the one line of code of your last commit in my custom components folder (PyLoxone version 0.4.3)
**
![image](https://github.com/JoDehli/PyLoxone/assets/95166878/09992c1f-395d-4c76-97df-f66f34f11ea0)
**
