### ISSUE TITLE
Intercom

### ISSUE THREAD

**Issue by 40federico** [JoDehli/PyLoxone#186]
Hi
I have loxone and your integration up and running. I cannot read entities related to the intercom v2. May I ask for your help how to find it?
Thanks.

**Comment by JoDehli** [comment]
@40federico Intercom is not supported out of the box. You can try to integrate it manually.
What Infos does a intercom send?

**Comment by 40federico** [comment]
Hi
it provides sound, open door mechanism and video.
https://www.loxone.com/dede/kb/sprechanlage/

**Comment by JoDehli** [comment]
@40federico and what infos do you expect in HA?

**Comment by 40federico** [comment]
I want to do some game with a pulse in a touch panel. Additionally I want to have a button to open the door of the intercom.
Regarding this subject, open the door, I don't know how to have running a service in home assitant with it. I can directly with the link https://192-168-1-xx.xxxxxxxxxxx.dyndns.loxonecloud.com/dev/sps/io/I3/Pulse open the door in a browser. But I couldn't using rest-api call from home assistant (it doesn't produce an action)

**Comment by JoDehli** [comment]
@40federico have you tried it?

**Comment by 40federico** [comment]
Thanks for your email. I am out by holidays, no have possibility for it.

Just a question. I want to send service to Loxone -I will try what you mention- but I would like in the other way. I mean I want to activate scenes in HA when some device is pushed on Loxone. How should be the way?

**Comment by claudiobertsch** [comment]
with the intercom v2 there is also the possibility to mute the bell.  I've already set this up with the websocket-direct-command.  now i can send the command to the intercom.  how can I query the attribute "muted" so that I can also see on the HA if it was muted directly in Loxone?

**Comment by JoDehli** [comment]
@claudiobertsch First of all you should get your LoxAPP3.json. There you can find your entry for your intercom v2.
There you search for the states field. This must be a list like this:

![grafik](https://github.com/JoDehli/PyLoxone/assets/32484282/a183d773-dde6-46ba-a796-f0f18234f59d)

This example is not from the intercom it is from another device. But I do not have a intercom. 
In your section you search for the uuid for "muted". 

Then you can make a custom sensor like this in your configuration.yaml:

```yaml
binary_sensor:
  - platform: loxone
    name: "Muted"
    uuidAction: "1a1cb29a-?????-?????-?????????"
    device_class: "None"
```

**Comment by claudiobertsch** [comment]
@JoDehli Perfect, works fine!!
