### ISSUE TITLE
HA not connecting to Loxone since 2023.8

### ISSUE THREAD

**Issue by jdenver13** [JoDehli/PyLoxone#188]
**Which Model do you use from loxone? Gen 1

**Which software version does your loxone use?** 14.2.6.16

**How did you install HomeAssistant? Over Hassio or manual install?** Hassio

**Which Version do you use of HomeAssistant?** 2023.8

**Describe the bug**

**Paste the error log with the following settings:**
Logger: homeassistant.config_entries
Source: helpers/device_registry.py:165 
First occurred: 8:21:35 pm (1 occurrences) 
Last logged: 8:21:35 pm

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/__init__.py", line 228, in async_setup_entry
    await miniserver.async_update_device_registry()
  File "/config/custom_components/loxone/miniserver.py", line 223, in async_update_device_registry
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 511, in async_get_or_create
    device_info_type = _validate_device_info(config_entry, device_info)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 165, in _validate_device_info
    raise DeviceInfoError(
homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info {'configuration_url': 'http://192.168.1.60:80', 'connections': {('mac', '192.168.1.60')}, 'default_manufacturer': 'Loxone', 'identifiers': {('loxone', '504F9410A2DE')}, 'manufacturer': 'Loxone', 'model': 'Miniserver (Gen 1)', 'name': 'Miniserver', 'sw_version': '14.2.6.16'} for 'loxone' config entry: device info needs to either describe a device, link to existing device or provide extra information.

**Comment by TheChristan** [comment]
Got the same issue, with a Gen 2 miniserver

My log:  (This shows up for 8 times and I also got the indivual ones, those show up 2 times, what makes 4 :) )
`Logger: homeassistant.config_entries
Source: helpers/entity_component.py:187
First occurred: 9:33:31 PM (8 occurrences)
Last logged: 9:33:31 PM

Error setting up entry PyLoxone for cover
Error setting up entry PyLoxone for fan
Error setting up entry PyLoxone for light
Error setting up entry PyLoxone for climate
Error setting up entry PyLoxone for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 132, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!`

**Comment by TheChristan** [comment]
@jdenver13 I updated PyLoxone on HACS, and that fixed it for me!

**Comment by rosch99** [comment]
@jdenver13 I can confirm, updating PyLoxone fixed the problem.
Many thanks to @JoDehli for the quick fix!

**Comment by jdenver13** [comment]
Thank you, updates just come through and problem solved.

**Comment by I-am-OK-86** [comment]
I have still the same issue even after updating to 0.4.6. Any ideas why?

**Comment by JoDehli** [comment]
@I-am-OK-86 that is another error. Not the same as the other users had. There is something wrong with your setup? 

Unexpected error importing loxone/system_health.py
Unexpected error importing loxone/logbook.py
Unexpected error importing loxone/cast.py
Unexpected error importing loxone/significant_change.py
Unexpected error importing loxone/hardware.py

This errors are very strange. In my binding there are no such files used. I do not know why they should be imported. please uninstall pyloxone completely and reinstall it. And if you still has this problem make another issue and describe completely what setup you use and how you installed your system. Docker, bare or Hassio ....

**Comment by I-am-OK-86** [comment]
Thanks, still the same issue after deleting the whole installation. I created ticket #191. Thanks or your support.
