### ISSUE TITLE
issue with HACS integration

### ISSUE THREAD

**Issue by vicfalls** [JoDehli/PyLoxone#19]
Hi

adding the repository via HACS, I get following Message:

An error occurred while processing
Exception: HacsException 
Message: GitHub returned 404 for https://api.github.com/repos/JoDehli/PyLoxone.git 
Could not add this repository, make sure it is compliant with HACS.

Log says:
Log Details (ERROR)
Logger: hacs.repository.integration.JoDehli.PyLoxone.git
Source: custom_components/hacs/helpers/validate_repository.py:36 
First occurred: 7:14:24 AM (3 occurrences) 
Last logged: 8:53:30 AM

What am I doing wrong?

Thanks
Vic

**Comment by JoDehli** [comment]
It was a mistake in the documentation.
Please add: 
https://github.com/JoDehli/PyLoxone
not 
https://github.com/JoDehli/PyLoxone.git
to hacs (without ending .git) and try it again.

**Comment by vicfalls** [comment]
> https://github.com/JoDehli/PyLoxone

@JoDehli works!!! Thanks
