### ISSUE TITLE
The Gate / Garage Door is not available anymore

### ISSUE THREAD

**Issue by AndreWeberHH** [JoDehli/PyLoxone#190]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen 2

**Which software version does your loxone use?**
14.2.6.16

**How did you install HomeAssistant? Over Hassio or manual install?**
Hassio

**Which Version do you use of HomeAssistant?**
2023.8.0

**Describe the bug**
The Gate / Garage Door is not available anymore. I updated to the newest PyLoxone but it doesn't help.

**Paste the error log with the following settings:**
<img width="574" alt="image" src="https://github.com/JoDehli/PyLoxone/assets/31306551/927bb4e2-5b3e-49ad-a5b1-49125d5bd704">

**Comment by arjenvrh** [comment]
Same here 0.5.0b8, only with the Garage cover, all others are working. 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'type'

**Comment by JoDehli** [comment]
@arjenvrh and @AndreWeberHH please update to the newest release. I have forgotten those covers as I do not use them.

**Comment by arjenvrh** [comment]
@JoDehli Works like a charm, thanks!

**Comment by AndreWeberHH** [comment]
@JoDehli Works perfect now. Thanks for the fast response and fix.

**Comment by AndreWeberHH** [comment]
@JoDehli Works perfect now. Thanks for the fast response and fix.
