### ISSUE TITLE
Shutdown of lights sends incorrect command to lightscontrollerv2

### ISSUE THREAD

**Issue by lukaskroczek** [JoDehli/PyLoxone#193]
Hi @JoDehli,

during testing of integration between ha and I found an issue with the shutdown of lights.

Current behavior:
After the shutdown light in ha, the light in Loxone app is shown as "manual".

Expected behavior:
When the light in ha is shutdown, the light in Loxone app is shut down

Problem:
`async def async_turn_off(self, **kwargs) -> None:
        self.hass.bus.async_fire(SENDDOMAIN, dict(uuid=self.uuidAction, value="off"))
        self.async_schedule_update_ha_state()`

should be:

`async def async_turn_off(self, **kwargs) -> None:
        self.hass.bus.async_fire(SENDDOMAIN, dict(uuid=self.uuidAction, value="changeTo/0"))
        self.async_schedule_update_ha_state()`

PS: if you allow me as a contributor, I will be able to make PRs with fixes and new features (I am missing Audio Player).

**Comment by lukaskroczek** [comment]
also, from my point of view, to turn on light "changeTo/99" should be used.

**Comment by JoDehli** [comment]
@lukaskroczek I think you can make a Pull Request without being a contributor.

**Comment by JoDehli** [comment]
@lukaskroczek or are you interested to do more on the development of Pyloxone?

**Comment by lukaskroczek** [comment]
see https://github.com/JoDehli/PyLoxone/pull/195

And yes, I am interested to make more development on PyLoxone

**Comment by JoDehli** [comment]
Of course you can not merge it. This is not permitted. But you can create a pull request I think?

**Comment by JoDehli** [comment]
Of course you can not merge it. This is not permitted. I saw you already made the pull request. 

Merging is not allowed only for admins. And please understand I give the admin rights not right away. But I am glad to review and merge the pull requests. I think this is a common practice.

Of course when we work more together I can give you more privileges and also a merge privilege.

And I am very glad when you help.me with the development.

**Comment by lukaskroczek** [comment]
@JoDehli : no problem, I am use to using pull requests. But I am not use to use forks, so I have a small issue with it ...

So, https://github.com/JoDehli/PyLoxone/pull/197 is new 195.

Also, I add AC Control - https://github.com/JoDehli/PyLoxone/pull/196.

Now, I will take look on audio player
