### ISSUE TITLE
temperature sensor issue

### ISSUE THREAD

**Issue by elmattt** [JoDehli/PyLoxone#194]
Hello,
i'm using a temp sensor with the 1 wire extension, it works great on loxone, but with home assistant it does this 👍 
<img width="567" alt="Capture d’écran 2023-08-14 à 09 24 27" src="https://github.com/JoDehli/PyLoxone/assets/56804333/40216a76-da9a-4480-a0a0-5ff149361a3d">

any idea why ?
another 1 wire sensor looks great, already check the pinout ...

**Comment by JoDehli** [comment]
@elmattt I do not know how loxone displays the values. Seams for me that your values changes very often. What you can try is to filter it for da graph by using a template sensor and apply the filter to it. This should give a much better graph.    You can do that on the loxone side make a filtered virtual sensor and display this in homeassistant

**Comment by JoDehli** [comment]
@elmattt any progress with this problem?
