### ISSUE TITLE
How to use Alarm Control Panel?

### ISSUE THREAD

**Issue by tanker11** [JoDehli/PyLoxone#199]
Hi,

Checked the existing issues and description, but could not find out the following:
I have a Burglar Alarm blcok within Loxone Config, and respectively I have the alarm entity in Home Assistant.
Putting in on an Alarm Control Panel card, the card has no PIN keypad nor I found how to define the codes.
If I make a manual Alarm in configuration.yaml, it works, but for the entitty it creates.
How to make the entity of Loxone integration requesting code within Home Assistant?

**Comment by JoDehli** [comment]
My Alarm looks like this 

![grafik](https://github.com/JoDehli/PyLoxone/assets/32484282/a2bc5432-b23f-4804-9327-69fd6529e52a)

I do not know why your code field is not defined. Did you set the code in Loxone for the alarm. Did you see a Alarm Panel in the Loxone App?

**Comment by tanker11** [comment]
Sorry, I did not assume the SW was so sophisticated that brings the code
defined by LoxConfig. :) Wrong assumption.
I will look into it!

Joachim D. ***@***.***> ezt írta (időpont: 2023. szept. 14.,
Cs, 18:43):

**Comment by tanker11** [comment]
Hello,

I needed some time to try it out.
It is not obvious where to set the PIN/password, actually.

Notes:
1.) The admin password for Loxconfig works with the HA Alarm card
2.) The normal user's passwords don't
3.) It would be good to define PIN code instead of passwords, as on some
interfaces thara are no keyboards, and in case of PIN, HA card offers the
number digits, in case of password, just an input field...

Can you provide an insight on this please? At least how/where to correctly
define the users's passwords/PINs under Loxconfig and if and how the user
is identified when uses the password to arm/disarm the system.

Thanks,
Robert



Róbert Tanka ***@***.***> ezt írta (időpont: 2023. szept. 15.,
P, 8:51):

**Comment by JoDehli** [comment]
@tanker11 of course the password of the user which is used for pyloxone will work. But you can also define s user interface password for that user. But you can not us a user password for a different user. Only the user's password or visual password for the user which is used for the pyloxone connection.

**Comment by tanker11** [comment]
Okay, noted with thanks.
Is there any way to develop towards any user code defined in the Loxconfig
could be used?
I would not let other users to use one such important password shared.


Joachim D. ***@***.***> ezt írta (időpont: 2023. szept. 26.,
K, 13:35):

**Comment by JoDehli** [comment]
@tanker11 the standard alarm panel has only the password field now field for username. So for now there is the only way to use the user which you have defined in the pyloxone. And you can choose a user with limited access if you want to share your homeassistant with others. then homeassisant has only the rights of the user. And you can define a visual password only for the alarm which can be different then the username. If you do not want that the users can activate the alarm you can keep this key secret.
