### ISSUE TITLE
Feature Request: Option to invert binary sensors

### ISSUE THREAD

**Issue by pasqual-artif** [JoDehli/PyLoxone#200]
Based on Issue #152 

An Option would be nice, so it won't be neccassary to define an additional inverted sensor

**Comment by JoDehli** [comment]
@pasqual-artif you can invert it direct in loxone itself. Why would you invert it on homeassistant and not on loxone side? If you do that you have 2 different states or am I wrong?

**Comment by pasqual-artif** [comment]
because the loxone hasn't changed, but pyloxone got the update.. I updated from 0.3.X to 0.4.7 and suddenly "sensors." became "binary_sensors." and open/closed were switched. (open became closed and closed became opened) So I assume it's on pyloxone's side..

I know I could switch it there, but other systems relying on the continuity..

what do you mean by different states?

**Comment by JoDehli** [comment]
@pasqual-artif can you show me a concrete example. What value does the binary sensor has in loxone config and in home assistant.

Because it's should be like the value 1 is on and value 0 is off.

**Comment by pasqual-artif** [comment]
It is "0=open 1=closed"

**Comment by pasqual-artif** [comment]
But I switched it to "0=off 1=on" but nothing changes

**Comment by pasqual-artif** [comment]
![image](https://github.com/JoDehli/PyLoxone/assets/116809107/938ef747-89f7-4a38-a991-8d1e1c7f36c6)
![image](https://github.com/JoDehli/PyLoxone/assets/116809107/1298f7ec-1566-4344-9b9a-cd3cf725fb04)

**Comment by JoDehli** [comment]
@pasqual-artif Ok again I looked at it. The value for on is always 1 if you not invert it on the loxone side. So on homeassistant there is always the same value for on or off state. On is 1 and off is 0. 

The text which is displayed on the the Loxone App can be changed as you can see here:

![grafik](https://github.com/JoDehli/PyLoxone/assets/32484282/dc54fd06-0e0f-450b-9249-d79eb96fd914)

So now you have at least 2 options:

1. you create a addional output which is inverted in loxone
2. or you create a template sensor on home assistant side

I can not give you extra attributes for this sensor.

**Comment by pasqual-artif** [comment]
Well... I don't say it's a bug :D 
And that's why I wrote it as "Feature Request" since it could be changed in python based on an option ^^

**Comment by JoDehli** [comment]
@pasqual-artif I think you have Window contacts. Am I right?

**Comment by pasqual-artif** [comment]
What do you mean with window contacts?

**Comment by JoDehli** [comment]
@pasqual-artif Binary sensor is it for window contacts? Or Door contacts

**Comment by pasqual-artif** [comment]
ah.. they are litterally binary contacts... circuit closed / circuit open

but they apply on windows and doors as well as the garage and the acover of the alarm

**Comment by JoDehli** [comment]
@pasqual-artif You can change the text by choosing the right binary sensor type:
![grafik](https://github.com/JoDehli/PyLoxone/assets/32484282/739e4fd9-b1b3-44e1-ae6d-be2fdfad4fb1)

**Comment by JoDehli** [comment]
@pasqual-artif If you choose there the right one or the one which is the closest to you sensor the text should be displayed right.

**Comment by JoDehli** [comment]
@pasqual-artif did It work?

**Comment by pasqual-artif** [comment]
What do you mean with the closest to my sensor?
In Loxone itself it says "Category: Alarm" - "Input Type: Key/Button" (Taste auf Deutsch :D)

**Comment by JoDehli** [comment]
@pasqual-artif have you tried a window sensor or a something else.

**Comment by pasqual-artif** [comment]
Yes I did... But I don't think you misunderstanding what I opened the thread for..
Independent of my specific problem, I asked for a feature. An option which simply inverts the signal, got from loxone..
An option, like a checkmark which simply is asked for in the code, and if it's 1 or true, then the input from loxone gets inverted.
example:

```python3
from typing import Union

def invertSignal(signal: Union[int, bool]):
    # import checkmark as checkmark
    checkmark: Union[int, bool]
    if checkmark is True or checkmark == 1:
        return not signal
    else:
        return signal
```

**Comment by JoDehli** [comment]
@pasqual-artif I did not misunderstood you. But to in my option this has nothing to do with pyloxone. This is a homeassistant thing to change states that are different from the real state. The real state is display right if you choose the right type of binary sensor in homeassistant. 

So if you want a "wrong" or inverted state this should be done with homeassistant direct by using a template sensor.

**Comment by JoDehli** [comment]
@pasqual-artif have you tried the different types of binary sensors? Do you have the same state now as it is displayed in loxone? 

And where do you want to implement the invert function? And how do you want to set it? You have now config for a sensor which is automatic generated?
