### ISSUE TITLE
I´m dump. How to send values to Loxone?

### ISSUE THREAD

**Issue by hallerdavid** [JoDehli/PyLoxone#202]
Hey Joachim,

i need some help.. i am not sure how to connect things. :-) 

I successfully installed PyLoxone to home assistant and also added my sensors from shellys and other things to HA. I came from iobroker so i´m really new to HA.

I have a virtual input from loxone (analog) for my photovoltaic-value (shelly sensor energy). 

I can see the value from the shelly in HA and its working correctly and updating every few seconds.
I can also see the virtual input as a sensor in HA but it has the constant same value from "112" (its the last value send from iobroker, which no longer exist now.

So how can i update this value? Most of my things i added to home-assistant are just values that i need to get into Loxone.. so if i have a small example i can make it on my own for the other things.

Thank you! :-)

**Comment by JoDehli** [comment]
@hallerdavid pyloxone is not stable so send a lot of data to the loxone. You should use nodered for example.

**Comment by hallerdavid** [comment]
for what is pyloxone made and stable? just for controlling the real standard things?

also i want to have some things in home-assistant like when someone rings the doorbell, then should Sonos do some things.. connected via homeassistant. Is that also something for nodered?

**Comment by JoDehli** [comment]
@hallerdavid it is in the first place for my system. And I do not send data. You are welcome to extend it. If not you better stay with iobroker.
