### ISSUE TITLE
Alarm control panel shows NIGHT feature (SUPPORT_ALARM_ARM_NIGHT)

### ISSUE THREAD

**Issue by lukaskroczek** [JoDehli/PyLoxone#207]
**Describe the bug (Required)**
The alarm control panel has support for NIGHT mode, but this night mode is never used in code but showed on FE.

To fix behavior, remove SUPPORT_ALARM_ARM_NIGHT on lines 10 and 110 in alarm_control_panel.py 

Used states are visible in method state on line 248 (STATE_ALARM_ARMED_HOME for not used presence and STATE_ALARM_ARMED_AWAY for used presence)

**Comment by JoDehli** [comment]
@lukaskroczek I also try to make the changes with your pull request.

**Comment by JoDehli** [comment]
@lukaskroczek I removed the SUPPORT_ALARM_ARM_NIGHT.
