### ISSUE TITLE
Automatic Shading block with Shading type "Roller blind" gets reflected as device class blinds with tilt UI

### ISSUE THREAD

**Issue by rolandpj** [JoDehli/PyLoxone#208]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2? (Required)**
Gen1

**Which firmware versio version does your loxone use? (Required)**
14.4.9.25

**How did you install HomeAssistant? Over Hassio or manual install?  (Required)**
I used HA image from Raspberry Pi Imager

**Which Version do you use of HomeAssistant?  (Required)**
Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0 - latest

**Which Version of Pyloxone do you use? (Required)**
0.4.8

**Did you try to update pyloxone to the latest version (Required)**
I am using the latest version

**Describe the bug (Required)**
In Loxone I use an Automatic Shading block, configured as Shading type 1 (=Roller blinds). So the block has no slats and tilt position
In HA Assistant this entity is shown with device_class blinds and has a tilt position in the visualization.

I think the Tils position should not be shown in HA GUI.

I also have an Alexa integration (without HA Cloud), and Alexa also shows Tilt position of slats. 

Entity in Homeassistant:

current_position: 99
**current_tilt_position: 100**
device_typ: Jalousie
platform: loxone
room: EG Wohnzimmer
category: Rollläden
current_shade_mode: ' '
current_position_loxone_style: 1
automatic_text: Automatik Beschattung wegen 'O1139' gesperrt.
auto_state: 'on'
**device_class: blind**
friendly_name: Gartentüre
supported_features: 191
![image](https://github.com/JoDehli/PyLoxone/assets/26387147/00485add-23ac-4348-bb84-a7831c851eea)

**Comment by JoDehli** [comment]
@rolandpj I changed the jalousie to that the tilt option is only visible for shading type 0. Can you try the latest source code from the master branch?

**Comment by rolandpj** [comment]
Hi @JoDehli 

Thanks for your answer!
I just replaced the cover.py and restarted the system.
Now the tilt option is gone :-) THANKS!

I recognized that if the cover is closed the position is 0%, if its opened the position is 100%. This logic is inverted to the Loxone logic.
Is there a way to change this behaviour to match the Loxone logic? (0% -> OPEN, 100% -> CLOSED)

**Comment by JoDehli** [comment]
@rolandpj I do not know if this is possible. This is a general home assistant question. Maybe you can ask on the home assistant forum.

**Comment by rolandpj** [comment]
okay Thanks
I found in the meantime a workaround
For the Loxone integration its good now with your change. Thanks a lot!
