### ISSUE TITLE
Can not connect pyloxone with server: 

### ISSUE THREAD

**Issue by JackyHallo** [JoDehli/PyLoxone#211]
### Describe the bug

Can not connect pyloxone with MS Gen 2. Check log book is the description

### Firmware of your Miniserver

14.4.9.25

### HomeAssistant install method

Manual

### Version of HomeAssistant

Home Assistant Operating System 11.1
Home Assistant Core Home Assistant Core

### Version of Pyloxone

Don't find what version I have or how to update it? 

### Update pyloxone

Don't find what version I have or how to update it? Please explain..

### Log

ERROR (MainThread) [frontend.js.latest.202308021] http://192.168./frontend_latest/15664-2R3AuA7BqSA.js:1:78492 Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener')
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/__init__.py", line 195, in async_setup_entry
    if not await miniserver.async_setup():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/miniserver.py", line 140, in async_setup
    request_code = await self.lox_config.getJson()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/api.py", line 122, in getJson
    api_resp = await client.get("/jdev/cfg/apiKey")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1703, in _send_handling_redirects
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    await hook(response)
  File "/config/custom_components/loxone/api.py", line 84, in raise_if_not_200
    raise LoxoneHTTPStatusError(
custom_components.loxone.api.LoxoneHTTPStatusError: Miniserver response code 307
ERROR (MainThread) [frontend.js.latest.202308021] http://192.168./frontend_latest/15664-2R3AuA7BqSA.js:1:78492 Uncaught TypeError: Cannot read properties of null (reading 'removeEventListener')

**Comment by JoDehli** [comment]
@JackyHallo the gen2 does only work with local access. There are many solved issues with the same problem. There you can find informations. Try local access with your local IP address. Port do not use 80 as we had problems in the past with this port.

**Comment by JackyHallo** [comment]
Does that mean that I can't connect with my app on my phone when I'm not home?

**Comment by JoDehli** [comment]
@JackyHallo I do not know. You must try it if you can still access your miniserver from outside if you allow local access for homeassistant. I would say that are 2 different things but I have never tried it as my miniserver is not reachable from outside. I only use VPN as it is much safer.

**Comment by JoDehli** [comment]
@JackyHallo have you tried the local access?

**Comment by JackyHallo** [comment]
Yes, but still didn't work..

**Comment by JoDehli** [comment]
@JackyHallo have you read thru the already closed issues ? 

https://github.com/JoDehli/PyLoxone/issues/203 


you have to connect thru your local address. if you can access it via browser you are nearly there.

**Comment by JackyHallo** [comment]
It's working!

But I want to control my lights with Google Home.
I tried to add some automation and as trigger 'use sentence', but I think that's not the right way?

**Comment by JoDehli** [comment]
@JackyHallo I would define a scene in homeassistant first and configure it that it does what you want. Then I would try to get the scene activated from google home. 

Which integration do you use for google home? The nabu casa integreation or the manual setup over a developer account from google.

**Comment by JackyHallo** [comment]
I use the google assistant, or is that not a integreation?

**Comment by JoDehli** [comment]
@JackyHallo I have setup Google assistant manually and not vis nabucasa. After the installation, which is not very easy to understand as the developer console from Google is really a pain, I have chosen to 3xpose only a view devices to Google home. And this devices I can control without a problem. 

Please explain more of your problem. Do you see the devices which you want to control in Google home? And which devices do you want to control? Or do you stuck with getting the loxone devices in homeassistant.
