### ISSUE TITLE
After update not all sensors loaded

### ISSUE THREAD

**Issue by Dohnalradek** [JoDehli/PyLoxone#216]
### Describe the bug

I make an upgrade of HA (from 2023.07 to 2023.11) and after that a upgrade PyLoxone (from 0.3.13 to 0.4.10).
After this update, binary sensor dissappear (PIR sensor, magnetic contacts, etc).
Try to uninstall PyLoxone from Devices&Services, remoce Pyloxone from HACS integration, restart HA. No Looxne files left in HACS folder. Also remove this binary sensor from "core.entity_registry" file (was in section Deleted_entities). Still no binary_sensors...

Try to rename one binary sensor in Loxone, but also didn show in Home Assistant...

### Firmware of your Miniserver

miniserver 1gen, fw. 9.3.3.26

### HomeAssistant install method

intel NUC, virtual box (linux)

### Version of HomeAssistant

2023.11.2

### Version of Pyloxone

0.4.10

### Update pyloxone

yes

### Log

https://codefile.io/f/vEFtcBxl7F

**Comment by JoDehli** [comment]
@Dohnalradek do you use some smoke detectors? if so can you paste the sections from your structure file where I can see what states your device has? only the part with the smoke detector. you can delete some digits from the uuids if you want.

**Comment by JoDehli** [comment]
@Dohnalradek I know what is wrong. You must update your miniserver. 

The integration is only valid for newer miniserver firmwares

The problem causes a attribute which was introduced in 10.3

This is from the Doku:

areAlarmSignalsOff
○ State if all alarm signals are disabled (by confirming alarm)
■ available since 10.3

**Comment by Dohnalradek** [comment]
I read about speed problem with newer version of fw on miniserver gen. 1 (esp. with modbus extension) - thats the reason why I stay with older fw (9.3).
But it works with older pyloxone (0.3.13). So is it possible to install this older pyloxone version and it will works again?

**Comment by JoDehli** [comment]
@Dohnalradek I think it will not work with newer home assistant installation.

**Comment by Dohnalradek** [comment]
Wow, I erese block fire and water leak (in loxone) - replace by mail notofication. Restart HA and 50 new binary sensors appears! Thats perfect, thank you very much to point where is the problem.
So Loxony 9.3, HA 2023.11 and Pyloxone 0.4.10 can work together!
