### ISSUE TITLE
Integration for  ac control air loxone

### ISSUE THREAD

**Issue by krasi-georgiev** [JoDehli/PyLoxone#217]
### Describe the bug

I want to control the ac using this module. It is a better alternative than the universal ir control options.

Without the loxone server

Happy to sponsor the integration.

### Firmware of your Miniserver

.

### HomeAssistant install method

.

### Version of HomeAssistant

.

### Version of Pyloxone

.

### Update pyloxone

.

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@krasi-georgiev what do you mean without the miniserver? 

Which loxone type is your entity which you want to control by pyloxone?
The list of supported entities are listed on the main page. 

Loxone has such a big amount of different types but only a few of them are supported out of the box by this binding. But with a little bit of coding nearly every
device can be controlled via the websocket service which I added to homeassistant. But first you must tell me which type of device your are interested to control. Can you supply the part of the LoxAPP3.json from your installation.

Here is a guide to get the LoxApp3.json from your Miniserver:

https://github.com/JoDehli/PyLoxone/tree/master#how-do-you-get-the-uuid

But please do only paste the entry you want to control as there are many sensible data in this json for example your location etc.

**Comment by JoDehli** [comment]
@krasi-georgiev this binding connects via web socket to the miniserver. So you need a miniserver to control the devices which were connected to the miniserver. Is that what you you meant?
