### ISSUE TITLE
[Bug]: Can't see phisical switch

### ISSUE THREAD

**Issue by RossiNIT** [JoDehli/PyLoxone#218]
### Describe the bug

I just integrated Loxone into my HomeAssistant, I can see all controllable devices (like light, electrical plug, ecc...), but I can't see any sensor: phisical button, presence sensor and so on...

### Firmware of your Miniserver

14.4.9.25

### HomeAssistant install method

Ready to use container for VMware ESXi

### Version of HomeAssistant

2023.11.3

### Version of Pyloxone

0.4.11

### Update pyloxone

Yes

### Log

Logger: custom_components.loxone
Source: custom_components/loxone/__init__.py:149
Integration: PyLoxone (documentation, issues)
First occurred: 09:14:26 (5 occurrences)
Last logged: 09:14:26

Can't create group 'Loxone Switches' with error: 'group_registry'
Can't create group 'Loxone Covers' with error: 'group_registry'
Can't create group 'Loxone LightControllers' with error: 'group_registry'
Can't create group 'Loxone Dimmer' with error: 'group_registry'
Can't create group 'Loxone Group' with error: 'group_registry'

**Comment by JoDehli** [comment]
@RossiNIT do you see the missing entities in you offical loxone app?

You can ignore the errors for the group creation. This has nothing to do with the missing entities.

What types are the missing entities? I mean loxone types. The following types are supported by this binding:

-     InfoOnlyAnalog and InfoOnlyDigital
-     Switch, TimedSwitch and Pushbutton
-     Jalousie, Window and Gate
-     Intercom
-     LightControllerV2
-     Alarm
-     Fan
-     RoomControllerV2 
-     AudioZoneV2

Every other entities will not show up in home assistant.
