### ISSUE TITLE
[Bug]: Loxone integration flooding logs, preventing HA from responding

### ISSUE THREAD

**Issue by pissten** [JoDehli/PyLoxone#219]
### Describe the bug

Unable to start Home Assistant after updating to newest version of Loxone integration.
The logs are flodded with the same message, preventing the HA core to operate.

This has also happend in earlier version, but when switching to beta version 0.5.0B12 it has worked fine for my installation, previous. Now I can't seem to get either working :/ 

### Firmware of your Miniserver

14.4.9.25

### HomeAssistant install method

Container (docker)

### Version of HomeAssistant

2023.11.3

### Version of Pyloxone

0.5.0b13

### Update pyloxone

this is the latest, and are causing errors.

### Log

``
ERROR (MainThread) [custom_components.loxone.pyloxone_api.miniserver] Expected a bytes header, but received 257. Try to ignore error! 
``

**Comment by pissten** [comment]
Update: Version 0.4.11 is working for now

**Comment by pissten** [comment]
Were you able to find the cause of this? Is it addressed in the latest release?
Best regards
Christian

**Comment by JoDehli** [comment]
@pissten No I could not get this error. The beta branch will be closed in the future. So please use the main branch. If this works it should be ok.

**Comment by johny-mnemonic** [comment]
I got this issue on 0.5.0b13 as well today, completely braking the HA, which was unable to start.
It's weird that I had that version installed since it came out and it only started crashing HA today 🧐 
Going back to master branch fixed it.

@JoDehli you are planning to abandon the rewrite idea and drop the beta branch?
