### ISSUE TITLE
[Bug]: PyLoxone installed and conencted fine but unable to control from HA

### ISSUE THREAD

**Issue by daveo2k** [JoDehli/PyLoxone#220]
### Describe the bug

PyLoxone is installed and connected to my gen2 miniserver, it's setup most if not all devices but unable to control from HA.  HA also does not see updates, example I control something via the Loxone app HA does not update with the status change.

### Firmware of your Miniserver

14.4.9.25

### HomeAssistant install method

HA installed on VMware exsi using the vmdk HDD image.

### Version of HomeAssistant

Core
2023.12.0
Supervisor
2023.11.6
Operating System
11.2
Frontend
20231206.0

### Version of Pyloxone

Stable github release

### Update pyloxone

Not sure how...

### Log

Complete noob to HA, unsure as to how to get this information...

**Comment by JoDehli** [comment]
@daveo2k gen2 is only supported via local access. Make sure you enable local access and use your local IP address. Also do not use port 80. 

And for the log files you can enable log messages for all integration over home assistant.

**Comment by daveo2k** [comment]
it's connected via loacl IP so that side seems ok...
i think I under played my noob status - i'll check out HA logging and come back to you...
