### ISSUE TITLE
[Bug]: SmartActor RGBW on LightController V2 Turn on issue

### ISSUE THREAD

**Issue by geppertm86** [JoDehli/PyLoxone#227]
### Describe the bug

When turning on an SmartActor RGBW Device connected to a Light Controller V2 via Apple HomeKit the Brightness Value is always 2%. No Matter what that value before was

### Firmware of your Miniserver

14.5.12.7

### HomeAssistant install method

HA Docker via HACS

### Version of HomeAssistant

2023.12.1

### Version of Pyloxone

0.4.12

### Update pyloxone

Yes,Latest Version 

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@geppertm86 do you still have the problem with the newest release
