### ISSUE TITLE
HA deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by elRadix** [JoDehli/PyLoxone#228]
### Describe the bug

Warning in home assistant  that needs some attention

### Firmware of your Miniserver

14.5.12.7

### HomeAssistant install method

Hassio

### Version of HomeAssistant

Core 2024.1.1
Supervisor 2023.12.0
Operating System 11.3

### Version of Pyloxone

0.4.12

### Update pyloxone

yes

### Log

Entity None (<class 'custom_components.loxone.climate.LoxoneRoomControllerV2'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use **<ClimateEntityFeature.TARGET_TEMPERATURE|PRESET_MODE: 17**>, please create a bug report at https://github.com/JoDehli/PyLoxone/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**PRECIPITATION_MILLIMETERS** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPrecipitationDepth.MILLIMETERS instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SPEED_KILOMETERS_PER_HOUR** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**TEMP_CELSIUS** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**TEMP_FAHRENHEIT** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**FORMAT_NUMBER** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**FORMAT_TEXT** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.TEXT instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_ALARM_ARM_AWAY** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_ALARM_ARM_HOME** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_PRESET_MODE** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_SET_POSITION** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_STOP** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_OPEN_TILT** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN_TILT instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_CLOSE_TILT** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE_TILT instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_SET_TILT_POSITION** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_TILT_POSITION instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**SUPPORT_TARGET_TEMPERATURE** was used from loxone, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/JoDehli/PyLoxone/issues

**Comment by elRadix** [comment]
updated to the lastest pyloxone version today

all other warning are fixed only the ones  below

> Entity None (<class 'custom_components.loxone.light.LoxonelightcontrollerV2'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.EFFECT: 4> and color modes, please create a bug report at https://github.com/JoDehli/PyLoxone/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
> 
> Entity None (<class 'custom_components.loxone.light.LoxoneDimmer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 1> and color modes, please create a bug report at https://github.com/JoDehli/PyLoxone/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
> 
> Entity None (<class 'custom_components.loxone.light.LoxoneColorPickerV2'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 19> and color modes, please create a bug report at https://github.com/JoDehli/PyLoxone/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by elRadix** [comment]
@JoDehli  updated to version 6

still one warning left



`Entity None (<class 'custom_components.loxone.light.LoxoneColorPickerV2'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 19> and color modes, please create a bug report at https://github.com/JoDehli/PyLoxone/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

**Comment by JoDehli** [comment]
@elRadix we have enough time to fix it. There are a lot more deprecated warnings coming in the future. This is really annoying in homeassistant that they change these things so often. 

So I will remove them from time to time.

**Comment by elRadix** [comment]
no worries, thank you anyhow for all the effort
maintaing it is not easy, home assistant is moving too fast lately
