### ISSUE TITLE
[Question]: Change text of virtual text input in loxone?

### ISSUE THREAD

**Issue by brechtvhb** [JoDehli/PyLoxone#231]
### Describe the bug

I created a virtual text input in loxone and would like to set the text content of it with home assistant.
In home assistant it gets converted to a regular text sensor wih these attributes

```
Uuid: 1c452304-0061-4e74-ffffeb5c57ac4c41
Device typ:TextInput
Platform: loxone
```

Is it possible to set the text of the input or is a change in PyLoxone needed to make this possible?

### Firmware of your Miniserver

14.5

### HomeAssistant install method

HASS

### Version of HomeAssistant

2024.1

### Version of Pyloxone

0.6.1

### Update pyloxone

Yes

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@brechtvhb if you have such a question you can look in the so-called structure file document. You will find the latest version on the loxone home page. There you can find all possible commands for all the entities.
