### ISSUE TITLE
[Request]: Add room to entity id

### ISSUE THREAD

**Issue by Chrone86** [JoDehli/PyLoxone#232]
### Describe the bug

I have several rooms in loxone with the same light-object. To find the right entity id in the dashboard config, it would be very usefull, when the room name would be included into the entity id. Something like sensor.light_livinroom

### Firmware of your Miniserver

14

### HomeAssistant install method

VM

### Version of HomeAssistant

Latest

### Version of Pyloxone

Latest

### Update pyloxone

Latest version

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@Chrone86 I understand your problem but to change it would be difficult. It would mean, that all sensors would be renamed. This would mean that all previous automations and scripts would no longer work. 

What you can do is to filter by room under developer tools --> stats in the attributes column. Then you will see only 
the entities for this room.

**Comment by JoDehli** [comment]
@Chrone86 of course you can also rename your entities in loxone direct that you can differentiate your lights.

**Comment by Chrone86** [comment]
That‘s what I did. 
Maybe it would be a nice feature to have a button, which would rename the entities. This would be usefull when starting from scratch.

**Comment by JoDehli** [comment]
@Chrone86 what do you mean with button to rename it?
