### ISSUE TITLE
Error with 0.6.2 - Downgrade to 0.6.1

### ISSUE THREAD

**Issue by KurtKeunen** [JoDehli/PyLoxone#237]
### Describe the bug

Updating to the latest version of Loxone config/miniserver and the latest version of Pyloxone in Hac i got the 2 errors and non of the climate entities load

### Firmware of your Miniserver

14.5.12.7

### HomeAssistant install method

Hacs

### Version of HomeAssistant

Core
2024.1.6
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

### Version of Pyloxone

0.6.2

### Update pyloxone

yes

### Log

_______________________________________________________________________________________________________
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 9:21:18 PM (2 occurrences)
Last logged: 9:21:18 PM

Unable to prepare setup for platform 'loxone.climate': Platform not found (Exception importing custom_components.loxone.climate).
_______________________________________________________________________________________________________
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 9:21:18 PM (2 occurrences)
Last logged: 9:21:18 PM

Unexpected exception importing platform custom_components.loxone.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/loxone/climate.py", line 108, in <module>
    class LoxoneRoomControllerV2(LoxoneEntity, ClimateEntity, ABC):
  File "/config/custom_components/loxone/climate.py", line 114, in LoxoneRoomControllerV2
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF
_______________________________________________________________________________________________________

**Comment by estragonator** [comment]
I am having the same issue, I think the problem is that the newest release of PyLoxone implemented features that are based on the dev version of homeassistant and have not been released yet through the stable release channel.

As you can see the release 2024.1.6 does not have the "TURN_OFF" flag yet: https://github.com/home-assistant/core/blob/2024.1.6/homeassistant/components/climate/const.py#L165
It was only added here: https://github.com/home-assistant/core/commit/bc720b48b476d2fa1ad754166d6aca72e0d180cf and included in pre-release https://github.com/home-assistant/core/releases/tag/2024.2.0b2

**Comment by funbirdcas** [comment]
same here

**Comment by JoDehli** [comment]
@KurtKeunen 
@estragonator 
@funbirdcas 
Ok I saw it. I tested only against my dev environment which is already using the new features. I disabled the release as long as homeassistant is not updated.

**Comment by KurtKeunen** [comment]
2024.2.0 has been released, this 0.6.2 probably works now?

**Comment by estragonator** [comment]
I can confirm 0.6.2 works with 2024.2.0 in my setup.
