### ISSUE TITLE
[Bug]: Loxone AC Controle only showing temperature and on/off

### ISSUE THREAD

**Issue by MaartenProvo** [JoDehli/PyLoxone#239]
### Describe the bug

Hello

I'm not sure this is actually a bug or me configuring not correctly. I have a Daikin AC unit which I'm trying to link to loxone via HomeAssistant.

I created a function block AC Controle which has options for:
- Mode: Auto, heat, cool, dry, ventilate
- Temperature
- Fan Speed: Auto, 1,2,3,4,5, swing, swing off
- Air flow: Auto Position 1,2,3,4,5, swing, swing off

However in Hass I only have control over on/off and the temperature. It's unclear why I can't control any of the other options? These options are available in the Hass-Daikin-integration.

Regards

### Firmware of your Miniserver

14.5.12.7

### HomeAssistant install method

Hassio

### Version of HomeAssistant

2024.1.6

### Version of Pyloxone

0.6.1

### Update pyloxone

already the latest version

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@MaartenProvo sorry but I I have not implemented (and I do not use) the AC Modul.
