### ISSUE TITLE
Intelligent room controller V1

### ISSUE THREAD

**Issue by MaartenMees** [JoDehli/PyLoxone#24]
Maybe an integration for the intelligent room controller? :)

Nice job so far, works great!

**Comment by JoDehli** [comment]
You can easily convert the v1 to V2. It is the recommended controller. Why do you prefer the v1 over the v2?

**Comment by MaartenMees** [comment]
Hi,
We have an old heating system that apparently doesn't work with V2 according to our electrician.

**Comment by MaartenMees** [comment]
Is V2 supported? Otherwise I will find a way to convert them...

**Comment by JoDehli** [comment]
I started with a integration but I stopped it. I have no climate controller in my house which I can test it. 
I can integrate it when I have time. But we should go with the v2 as it is the better one.

**Comment by MaartenMees** [comment]
It would be great as you can integrate V2. I am working on a way to convert my V1.

Keep me posted!

**Comment by MaartenMees** [comment]
I know this is far fetched, but I am looking for a way to integrate my weather station (loxone compatible). Any ideas, sugestions?

**Comment by MaartenMees** [comment]
Solved the weather station problem
