### ISSUE TITLE
[Bug]: Pushbutton in automation not forwarded

### ISSUE THREAD

**Issue by billeranton** [JoDehli/PyLoxone#241]
### Describe the bug

Loxone Pushbutton toggle works in UI. But triggered via automation does not.

Log states that button was toggled, but Pushbutton in Loxone does not perform associated action/output.

Tried to increase the Pushbutton duration to 0.5 sec. in Loxone config, but no avail.

This issue arose in the past after update of hassio or pyloxone, but cannot reproduce it on demand, or tell what causes the problem to go away after a while.

### Firmware of your Miniserver

14.5.12.7

### HomeAssistant install method

Hassio

### Version of HomeAssistant

2024.2.1

### Version of Pyloxone

0.6.1

### Update pyloxone

yes

### Log

![Screenshot from 2024-02-14 16-01-27](https://github.com/JoDehli/PyLoxone/assets/28869614/86a7a439-f9c4-49a9-961c-47d5b4ac0752)

**Comment by JoDehli** [comment]
@billeranton I think it is the wrong way to do it. Better way to do it is to call the a websocket command to the loxone in your automation. With this approach you bypass any ui problems with homeassistant. You can look on the main page how to implement a websocket command. And you can find all possible commands in the structure file from loxone.

**Comment by billeranton** [comment]
The weird thing is, after a few hours/a day later, the problem went away on its own.


In my opinion, the main motivation to use this add-on, should be to use the provided abstractions, and not to write the lower level stuff by one self.

Sure this will work, have some websocket commands for other stuff in place. But to have devices exposed in HomeAssistant invites to use them like other devices in HA.
