### ISSUE TITLE
[Suggestion]: Populate devices for service calls

### ISSUE THREAD

**Issue by gigatexel** [JoDehli/PyLoxone#242]
### Describe the bug

I noticed in the source code that as a starting point the LoxAPP3.json is parsed.

Wouldn't it be a great idea to use the parsed UUID's to populate a drop-down in the `event_websocket_command` service all?
This would make calling this service a lot easier, since you don't need to copy the .json, beautify it, search the UUID's and paste the correct value in the service call?

If there would be reasons why this is complicated, one can also use the device's name as I have shown in my own Blueprint: https://community.home-assistant.io/t/sending-data-from-home-assistant-to-loxone/625396

### Firmware of your Miniserver

*

### HomeAssistant install method

*

### Version of HomeAssistant

*

### Version of Pyloxone

*

### Update pyloxone

*

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@gigatexel thanks for you idea. Maybe I can take a look in the near future. At the moment I do not have enough time. I hope it gets better.

**Comment by gigatexel** [comment]
Implemented
