### ISSUE TITLE
[suggestion]: keypad for alarm card

### ISSUE THREAD

**Issue by elmattt** [JoDehli/PyLoxone#245]
### Describe the bug

is it possible to tell ha to show the numeric keypad on the alarm card if the code is only numeric ?

### Firmware of your Miniserver

latest

### HomeAssistant install method

hacs

### Version of HomeAssistant

latest

### Version of Pyloxone

latest

### Update pyloxone

yes

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@elmattt I do not know. A possible solution would be to make a template alarm panel. There you can specify if the code is digit only. 
For commands you can use websocket commands from pyloxone. This should be ok for one entity. I think you have only one alarm panel or not much more. If this works you can customise the behaviour as you like.
