### ISSUE TITLE
[Bug]: Scene are not available

### ISSUE THREAD

**Issue by Ch0112** [JoDehli/PyLoxone#246]
### Describe the bug

Hi,

is this a bug? How can I restore the scenes? I pressed "Restore" and re-stratified Py, reloaded Yaml and also restarted HASS - all without success.

any ideas?

Greetings Christian
![py1](https://github.com/JoDehli/PyLoxone/assets/149192047/1c23addf-4e25-46ad-8d11-63883de81be5)
![py2](https://github.com/JoDehli/PyLoxone/assets/149192047/46d8ad0e-1287-40ea-9d03-6eebaa856712)

### Firmware of your Miniserver

Version 14.5.12.7

### HomeAssistant install method

Hassio

### Version of HomeAssistant

2024.02.1

### Version of Pyloxone

0.6.2

### Update pyloxone

no

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@Ch0112 is there a error message in the log? Did you change something else?

**Comment by JoDehli** [comment]
@Ch0112 the name of the scene is generated from the loxone name. Did you change a entity in loxone

**Comment by Ch0112** [comment]
> @Ch0112 the name of the scene is generated from the loxone name. Did you change a entity in loxone

I have 75 Scenes in PyL and all are not available.
Maybe i changed 2 names bute not 75.

**Comment by Ch0112** [comment]
> @Ch0112 is there a error message in the log? Did you change something else?

I see no error.
To rule out an error on my side, I would reinstall. What do I have to delete to do this?

**Comment by JoDehli** [comment]
@Ch0112 a reinstall should not be needed as pyloxone generates the scenes every time it connects. 

what you can do is disable pyloxone. Then restart homeassistant. Then delete all pyloxone entities and again restart. Then enable pyloxone and restart again.

**Comment by Ch0112** [comment]
Okay, i tried it, but i cant delete all entities - there comes this message:
![py3](https://github.com/JoDehli/PyLoxone/assets/149192047/71d4829a-d6f6-46be-a8a6-d017d41af90b)

**Comment by Ch0112** [comment]
save_token successfully...
2024-03-03 19:48:01.262 DEBUG (MainThread) [custom_components.loxone.api] get_new_aes_chiper successfully...
2024-03-03 19:48:01.317 DEBUG (MainThread) [custom_components.loxone] **starting loxone scene...**
2024-03-03 19:48:13.888 DEBUG (MainThread) [custom_components.loxone.api] message [type:2]):{'18ba610a-0374-e4fe-ffff7e1b3a2ae3c8': 9.0, '18ba610a-0380-e510-ffff7e1b3a2ae3c8': 428.0, '18ba610a-0382-e513-ffff7e1b3a2ae3c8': 1088.0, '1c356a3c-00c1-37e8-ffff7e1b3a2ae3c8': 0.0, '1c356a3c-00c1-37e9-ffff7e1b3a2ae3c8': 0.0, '


On that line with scenes, there is no successfully

**Comment by JoDehli** [comment]
@Ch0112  I checked the current version and it should work. Have you increased the timeout for the scene generation? If not increase it step by step from 3 to maybe 20 seconds. The delay is for bigger installations. All other platforms must be ready before generating the scenes. Otherwise they will not show up. 

And there is no success message for the scenes. So this is not a problem.

**Comment by Ch0112** [comment]
Okay, so is set the delay step by step to 15 an now are 74 more etinitys. 
Tomorrow i am at home an check it out. Maybe this can be the solution for this problem.

I will write here again if i have checked it.

**Comment by Ch0112** [comment]
> @Ch0112 I checked the current version and it should work. Have you increased the timeout for the scene generation? If not increase it step by step from 3 to maybe 20 seconds. The delay is for bigger installations. All other platforms must be ready before generating the scenes. Otherwise they will not show up.
> 
> And there is no success message for the scenes. So this is not a problem.

Now!!
It works!! This was the problem! 
The Scenes are usable and make no misstakes again!

Thank you verry much - good work!!
