### ISSUE TITLE
Error message since HA 0.110.0

### ISSUE THREAD

**Issue by Shogun1978** [JoDehli/PyLoxone#25]
After moving to the newest HA version I get an error message all entities:

Light is deprecated, modify LoxonelightcontrollerV2 to extend LightEntity
Light is deprecated, modify LoxoneColorPickerV2 to extend LightEntity
Light is deprecated, modify LoxoneDimmer to extend LightEntity

CoverDevice is deprecated, modify LoxoneGate to extend CoverEntity
CoverDevice is deprecated, modify LoxoneWindow to extend CoverEntity
CoverDevice is deprecated, modify LoxoneJalousie to extend CoverEntity

SwitchDevice is deprecated, modify LoxoneTimedSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify LoxoneSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify LoxoneIntercomSubControl to extend SwitchEntity

Covers still work, dimming of lights also. But switches are just working "one-way" (just switching on, off is no longer working). Would be great if PyLoxone could support the newest HA version.

**Comment by JoDehli** [comment]
Try the new release. Does the switch work now as expected? If not please give me details which kind of switch. Mine are working as expected.

**Comment by Shogun1978** [comment]
I upgraded to 0.23, HA 0.110.1 (and .2) so switches work, but light entities just switch on, not off. No more error messages are visible in the developer log (and also nothing on console, I use HA as docker container).

**Comment by JoDehli** [comment]
I tested it on my system. No problems. Can you sent some screenshots of your light configuration in the loxone config that I can make some test lights like in your configuration.

**Comment by Shogun1978** [comment]
Seems like I am coming closer to the issue. Your last post gave me another idea, what to test. If I use a normal switch, cover or light entity (light controller), everything works! 

If I use a single item (like one digital output of the Miniserver, e.g. Esstisch (which works fine inside of a light controller scene), I can't switch this digital output anymore. Just on, not off. Using the light controller entity and the light control in HA, it works! So it must be connected with the digital output itself. That worked before very well (I use a wall mounted display to control scenes and single light like Leselicht or Esstischlicht).

**Comment by JoDehli** [comment]
Please try the Dev branch. Hope I screwed nothing else up 😬

**Comment by Shogun1978** [comment]
You didn't screwed up anything - I am happy that there is a loxone integration at all (moved from Loxone 8.3 to 10 just because of your integration). Maybe stupid question, but how can I get the dev branch?

**Comment by JoDehli** [comment]
You must copy it by hand over your custom_component folder from the git Dev branch.

**Comment by Shogun1978** [comment]
Tried it, works excellent :-) Thank you for that fast fix!
