### ISSUE TITLE
[Request]: Intercom 

### ISSUE THREAD

**Issue by sebastiankern84** [JoDehli/PyLoxone#254]
### Describe the bug

Any Ideas or Plan to integrate the intercom - i did not found anything about this

### Firmware of your Miniserver

no

### HomeAssistant install method

install

### Version of HomeAssistant

hs

### Version of Pyloxone

pyl

### Update pyloxone

today

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@sebastiankern84 I do not have a intercom but as I know the intercom switches should populate as switches in ha. What does not work is the camera and audio.

**Comment by JoDehli** [comment]
@sebastiankern84 do you see the switches? The audio and the camera will not be integrated.

**Comment by sebastiankern84** [comment]
ok the switches i have - i cotroll the door opener with a shelly so it was easy to integrate - but i would like to get the video and ring in ha ;)

**Comment by JoDehli** [comment]
@sebastiankern84 sorry but this will not be added.

**Comment by gigatexel** [comment]
> @sebastiankern84 sorry but this will not be added.

Correction: this cannot be integrated :-)
You should use a more open solution that features a RTSP(S) stream, like the Unifi Doorbell G4 Pro
