### ISSUE TITLE
how-to documentation: offer to help

### ISSUE THREAD

**Issue by maglub** [JoDehli/PyLoxone#26]
Hi,

If you would like to start a wiki page in this repo, I offer to help writing a quick "hello world" on how to set this up (i.e with HACS) and how to quickly get the Loxone Demo Case working in Homeassistant.

I just got this integration up and running and am able to control things through the mini server outputs.

![image](https://user-images.githubusercontent.com/2961018/82997189-584e5d00-a006-11ea-8e0d-97405df4592b.png)

**Comment by JoDehli** [comment]
Hi,
of course it would be great if you can help. A good documentation helps a lot. What do you need? If I can help let me know.

**Comment by Saviq** [comment]
Hey, I agree documentation could be improved… I'm trying to integrate with a [Touch Surface](https://www.loxone.com/enen/new-touch-surface/), I can see it and configure within Loxone Config, but I can't seem to get anything out of it inside Home Assistant… I only get the Loxone groups, but no devices… Maybe there's a step I'm missing, I tried to follow the code in [`__init__.py`](https://github.com/JoDehli/PyLoxone/blob/master/custom_components/loxone/__init__.py), but couldn't find where the devices are discovered at all…

**Comment by JoDehli** [comment]
Do you see your devices on your Loxone App? Can you provide log files? 
Do you use port 80? If so please change it to a other port.

**Comment by Saviq** [comment]
@JoDehli I moved this to a new issue (#31), I shouldn't have jumped with my problems on this one in the first place.
