### ISSUE TITLE
phisical button, presence sensor etc...

### ISSUE THREAD

**Issue by RossiNIT** [JoDehli/PyLoxone#263]
### Describe the bug

I just integrated Loxone into my HomeAssistant, I can see all controllable devices (like light, electrical plug, ecc...), but I can't see any sensor: phisical button, presence sensor and so on...
It is possible to read the state of the presence sensor or the phisical switch on the wall to make some automation in home assistant?

### Firmware of your Miniserver

14.4.9.25

### HomeAssistant install method

Ready to use container for VMware ESXi

### Version of HomeAssistant

Core 2024.4.3
Supervisor 2024.04.0
Operating System 12.2

### Version of Pyloxone

0.6.4

### Update pyloxone

Yes

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by gigatexel** [comment]
No. A button, nor a presence sensor is a Loxone-block. The structure file (https://www.loxone.com/wp-content/uploads/datasheets/StructureFile.pdf) lists all blocks that are supported by the API and what information is available/controllable.
