### ISSUE TITLE
[Bug]: cover do not react after Homeassistant update to 2024.05

### ISSUE THREAD

**Issue by elaiel** [JoDehli/PyLoxone#265]
### Describe the bug

Cover do not react after Homeassistant update to 2024.05:
Fehler beim Aufrufen des Diensts cover/close_cover. Detected that custom integration 'loxone' calls async_fire from a thread at custom_components/loxone/cover.py, line 591: self.hass.bus.async_fire(. Please report it to the author of the 'loxone' custom integration.

### Firmware of your Miniserver

14.4.9.25

### HomeAssistant install method

VM in Proxmox 

### Version of HomeAssistant

    Core 2024.5.0
    Supervisor 2024.04.4
    Operating System 12.2
    Frontend 20240501.0

### Version of Pyloxone

0.6.3

### Update pyloxone

yes - I downloaded version 0.6.4 - but after restarting HA multiple times, it is still 0.6.3 

### Log

Fehler beim Aufrufen des Diensts cover/close_cover. Detected that custom integration 'loxone' calls async_fire from a thread at custom_components/loxone/cover.py, line 591: self.hass.bus.async_fire(. Please report it to the author of the 'loxone' custom integration.

**Comment by JoDehli** [comment]
@elaiel at the moment it is not compatible with the the newest HA . Please downgrade.

**Comment by Lesani** [comment]
![image](https://github.com/JoDehli/PyLoxone/assets/5182104/42456daf-ec5a-4c00-b3d4-03d93620e580)

Also on the latest beta 0.6.5

Above is an Info Message I get when trying to actuate covers. Lights are working.
Downgrading
Have never downgraded, looking into that for now, hopefully not for long...

**Comment by Lesani** [comment]
> I also did it the first time and had to search :-) you only need to use this command in the terminal:
> 
> ha core update --version 2024.4.4
> 
> ![image](https://private-user-images.githubusercontent.com/26387147/327371816-51b09adf-e6d9-402f-8f36-b501af5453fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTUxNTgsIm5iZiI6MTcxNDY1NDg1OCwicGF0aCI6Ii8yNjM4NzE0Ny8zMjczNzE4MTYtNTFiMDlhZGYtZTZkOS00MDJmLThmMzYtYjUwMWFmNTQ1M2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEzMDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZTQwMDVjNTgwNTI5NWUxMmU5MWRkZjYwMmRiMzc2MWRlMmM1MmExOWFiNjc4Yjk5ZTM2YzdhZGE2ZjIzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O21j0Sf8gZF7WKy1hAOnvz78DXOMqw35aBGY3Wqp7Iw)

Thanks! hopefully the plugin is fixed soon, 2024.5 has some nice features
