### ISSUE TITLE
[Bug]:  switch/turn_on not possible

### ISSUE THREAD

**Issue by Stijnvdj** [JoDehli/PyLoxone#270]
### Describe the bug

When I want to call a switch/turn_on on a switch I created within Loxone, I get this message; 
Kan service switch/turn_on niet aanroepen. Detected that custom integration 'loxone' calls async_fire from a thread at custom_components/loxone/switch.py, line 257: self.hass.bus.async_fire(. Please report it to the author of the 'loxone' custom integration.

### Firmware of your Miniserver

14.7.2.23

### HomeAssistant install method

Directly on a Raspberry Pi (without Docker, or another container)

### Version of HomeAssistant

Core: 2024.5.2
Supervisor: 2024.04.4

### Version of Pyloxone

0.4.11

### Update pyloxone

Yes

### Log

Kan service switch/turn_on niet aanroepen. Detected that custom integration 'loxone' calls async_fire from a thread at custom_components/loxone/switch.py, line 257: self.hass.bus.async_fire(. Please report it to the author of the 'loxone' custom integration.

**Comment by Stijnvdj** [comment]
I think I found the solution in a previous bug. Is it correct that I have to downgrade home assistant to an older version?

**Comment by Ch0112** [comment]
Ich habe das selbe Problem mit dem aktuellen Version von Home Assistant und habe ein Backup eingespielt, damit alles wieder funktioniert.
![Fehlermeldung PyLoxone HA](https://github.com/JoDehli/PyLoxone/assets/149192047/25579309-51bd-4f1f-b8c2-e6e378052a9b)

**Comment by Lesani** [comment]
That was fixed in 0.6.5 by JoDehli,
However for some reason PyLoxone does not show up in the default HA updates available list, you need to go into HACS and redownload it to get the newest version

**Comment by JoDehli** [comment]
@Stijnvdj the 0.4.11 is from Nov 18, 2023. It is really old. Please update as soon as possible.

**Comment by Stijnvdj** [comment]
Thank you all for the help!
