### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cooki537** [JoDehli/PyLoxone#272]
### Describe the bug

I get the error (see log), when i want to switch on a light, which is provided from pyloxon integration. I only have changed the type from switch to light.
I run this round about 1 year without any problems.
I installed loxone config 14.7.3.6 and the issue raised.

### Firmware of your Miniserver

14.7.3.6

### HomeAssistant install method

HASSOS on a Proxmox VE Cluster

### Version of HomeAssistant

2024.5

### Version of Pyloxone

0.6.3

### Update pyloxone

latest

### Log

Fehler beim Aufrufen des Diensts light/turn_on. Detected that custom integration 'loxone' calls async_fire from a thread at custom_components/loxone/switch.py, line 257: self.hass.bus.async_fire(. Please report it to the author of the 'loxone' custom integration.

**Comment by cooki537** [comment]
I tried the same with the actual version of Loxone Config 15.0.5.11.
No success.

**Comment by JoDehli** [comment]
@cooki537 please update pyloxone before reporting an issue.

**Comment by cooki537** [comment]
Hello Jo,
sorry, I didn't saw that there were new versions. Its working with the latest version. 
Since I changed to the new HACS Version, the update Infos for components seems to be not really reliable.
Thank you for your great work and the for the fast response....
Stefan
