### ISSUE TITLE
[Bug]: Switch error - Failed to call service switch/turn_on. Detected that custom integration 'loxone - 240515' calls async_fire ...

### ISSUE THREAD

**Issue by DSew20** [JoDehli/PyLoxone#273]
### Describe the bug

PyLoxone has been running until about 2 weeks ago. I have narrowed it down to Switch: Turn On action, which I note has been reported as an issue by other users.

I have read this could be a version issue.  I can confirm Loxone, Home Assistant, PyLoxone are all on the latest versions.

I get this error per below.

### Firmware of your Miniserver

15.05.11

### HomeAssistant install method

VM on Proxmox

### Version of HomeAssistant

Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

### Version of Pyloxone

0.6.9 (latest)
Manually installed

### Update pyloxone

Yes

### Log

Failed to call service switch/turn_on. Detected that custom integration 'loxone - 240515' calls async_fire from a thread at custom_components/loxone - 240515/switch.py, line 253: self.hass.bus.async_fire(. Please report it to the author of the 'loxone - 240515' custom integration.

**Comment by JoDehli** [comment]
@DSew20 this can not be correct. In your log is a code which is not in the newest version. So please delete everything and install pyloxone over hacs.

**Comment by DSew20** [comment]
Thanks.

So, remove folders:

/custom_components/loxone 
/www

And set up fresh from HACS?  Will all of the entities be preserver?

**Comment by DSew20** [comment]
OK. Thats fixed it. No idea why it was not showing the latest version with the files manually copied.

**Comment by DSew20** [comment]
Thank you
