### ISSUE TITLE
[Bug]: Can no longer set color temperature on RGBW lights

### ISSUE THREAD

**Issue by brechtvhb** [JoDehli/PyLoxone#274]
### Describe the bug

When trying to set the color temperature (using the slider in home assistant) I can no longer set the color temperature.
The temperature slider does not want to move. Other non-loxone lights still work as intended (Hue for example).

### Firmware of your Miniserver

14.5.12.7

### HomeAssistant install method

manual install

### Version of HomeAssistant

2025.05

### Version of Pyloxone

0.6.9

### Update pyloxone

Most recent version

### Log

No warnings or errors show up in the logs.

**Comment by JoDehli** [comment]
@brechtvhb I am on vacation. I have a look when I am back.

**Comment by JoDehli** [comment]
@brechtvhb the light components are complete rewritten maybe I missed one configuration. There are so many differen combinations in loxone. Can you tell me what lights exactly. Maybe with some pics from loxone config. My tested dimmers are working as expected

**Comment by brechtvhb** [comment]
@JoDehli 

This is the light that's is having issues: 
https://shop.loxone.com/enen/led-ceiling-light-rgbw-tree-anthrazit.html

Here's a picture in loxone config, not that much settings.
![image](https://github.com/JoDehli/PyLoxone/assets/330772/081628da-ecdd-48f0-b5d0-ed345d3cdd3d)

Any more info I can provide you to be able to troubleshoot the issue?

**Comment by brechtvhb** [comment]
@JoDehli 

It is part of a LightingCongtroller (v2):

![image](https://github.com/JoDehli/PyLoxone/assets/330772/6ca790be-e225-40b5-80d5-7bb62be1140d)

**Comment by JoDehli** [comment]
@brechtvhb then I do not understand why it is not working. Will take a look at the end of the week.

**Comment by JoDehli** [comment]
@brechtvhb can you change it locally and try it on your system.

**Comment by JoDehli** [comment]
@brechtvhb great. I change it as soon as possible and make a new version.

**Comment by JoDehli** [comment]
@brechtvhb can you confirm that this it the right change:

https://github.com/JoDehli/PyLoxone/pull/278/files
