### ISSUE TITLE
No Real Data

### ISSUE THREAD

**Issue by kordiakmikulas** [JoDehli/PyLoxone#275]
### Describe the bug

Hi, I install and configure your plugin, I see in HA all VI from Loxone and all digital inputs are "ON", when I change any in loxone or in HA, there is no interaction :(
![image](https://github.com/JoDehli/PyLoxone/assets/141869344/a67dc176-ade8-4d4e-ba55-de27945222e6)

I dont know, where is problem... 

### Firmware of your Miniserver

MS gen.1 FW: 15.0.5.11

### HomeAssistant install method

HASSIO

### Version of HomeAssistant

HA Core 2024.5.5
HA Super visor 2024.05.1
HA OS 12.3
HA Frontend 20240501.1

### Version of Pyloxone

0.6.9

### Update pyloxone

a have latest version

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@kordiakmikulas you need to provide logs for support. There must be some sort of error shown in the logs.

**Comment by kordiakmikulas** [comment]
> @kordiakmikulas you need to provide logs for support. There must be some sort of error shown in the logs.

Sorry, I don't see any logs anywhere... :(

**Comment by JoDehli** [comment]
@kordiakmikulas sorry at the moment imhave no time to support any user specific configuration issues. I concentrate on keeping the integration running.
