### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Ceylan-Geysemans** [JoDehli/PyLoxone#28]
Hi,
I am a new Home Assistant user before i used Homebridge and node red, a lot off my lights are controlled via the Loxone mini server i now have setup your integration with hacs but only my switches and sensors are showing up the lights with light controllers are not showing in home assistant can someone help me how to configure these. The Loxone lights group is empty in home assistant and i have a notification that says:The following integrations and platforms could not be set up: loxone.light please check your config

configuration.yaml file:

#Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#Text to speech
tts:
  - platform: google_translate

alexa:
  smart_home:
loxone:
  port: 80
  host: 192.168.0.30
  username: ***
  password: ***

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

**Comment by JoDehli** [comment]
First of all make sure that all light and light controllers are visible in the loxone app. Define for all entities a group and a room. Update to the latest pyloxone version if not already done. 

Pyloxone supports only the light controller V2 not the v1. So convert it if you have the old version. It should be easy in the loxone config software. 

Then you can temporarily change your log messages like I showed in https://github.com/JoDehli/PyLoxone/issues/27

**Comment by JoDehli** [comment]
Is it fixed? Than I can close this issue?

**Comment by Ceylan-Geysemans** [comment]
It is fixed thank you.
