### ISSUE TITLE
[Bug]: Opening and closing roller shutters no longer works

### ISSUE THREAD

**Issue by coaloaux** [JoDehli/PyLoxone#280]
### Describe the bug

I get an error message when I try to open or close the shutters. See below. All other entities are working.

### Firmware of your Miniserver

14.5.12.7

### HomeAssistant install method

Manual Install

### Version of HomeAssistant

2024.6.4

### Version of Pyloxone

0.6.3

### Update pyloxone

Yes, I did.

### Log

Fehler beim Aufrufen des Diensts cover/close_cover. Detected that custom integration 'loxone' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/loxone/cover.py, line 591: self.hass.bus.async_fire(. Please report it to the author of the 'loxone' custom integration.

**Comment by JoDehli** [comment]
@coaloaux you have a old version of pyloxone. Please update

**Comment by coaloaux** [comment]
Thank you! That fixed the problem :)
