### ISSUE TITLE
On initial setup all button show as on/off switches

### ISSUE THREAD

**Issue by PaulSinnema** [JoDehli/PyLoxone#281]
### Describe the bug

First off, nice job you did. On initial setup all switches show up as on/off switches. Many of my 'virtual inputs' are push buttons.

### Firmware of your Miniserver

15.0.5.29

### HomeAssistant install method

HACS

### Version of HomeAssistant

2024.3.3 (LinknLink iSG).

### Version of Pyloxone

0.6.10

### Update pyloxone

I downloaded if via HACS.

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@PaulSinnema I know this is a bug ehic I tried to fix but with no success. On initial setup you must restart once.

**Comment by PaulSinnema** [comment]
Hi Joachim,

 

I’m not a py developer but I can read code (I’m a .Net developer). In you switch.py I see this code:

 

        if switch_entity["type"] in ["Pushbutton", "Switch"]:

            switch_entity.update(

                {

                    "room": get_room_name_from_room_uuid(

                        loxconfig, switch_entity.get("room", "")

                    ),

                    "cat": get_cat_name_from_cat_uuid(

                        loxconfig, switch_entity.get("cat", "")

                    ),

                    "config_entry": config_entry,

                }

            )

            new_push_button = LoxoneSwitch(**switch_entity)

            entities.append(new_push_button)

 

 

Doesn’t cause all switches and pushbuttons to be the same?

 

Regards,

Paul Sinnema

**Comment by JoDehli** [comment]
@PaulSinnema now I understood what you meant. In home assistant we do not have push buttons. At least not when I started this integration. At that time we had only switches and no helpers etc. 

Does the switches work?

**Comment by PaulSinnema** [comment]
Yes the switch works

**Comment by PaulSinnema** [comment]
The switch goes on and off and triggers the event. I think it’s just the presentation of the switch that should change, see attached video.

**Comment by PaulSinnema** [comment]
Hoi Joachim,

 

Ok, I understand that. The thermostat looks like a bug to me.

 

Strange that no video is attached. I did send it as an .mp4. I’m sending it again but now as a .zip file.

 

Regards,

Paul Sinnema

**Comment by JoDehli** [comment]
@PaulSinnema please try the newest version of pyloxone. With the help of @gigatexel pyloxone should show the right representation of the entity.
