### ISSUE TITLE
Doorsensor - change icon according to state

### ISSUE THREAD

**Issue by chrisrock1984** [JoDehli/PyLoxone#29]
Hi,

Love your Loxone integration into HASSIO!
I have one question about door sensors. If I put them into Lovelace they show up as an "eye icon", with device type "digital_sensor". The problem I have is, that I would like the icon to be a door-open or door-closed icon. I tried a lot so far (e.g. template, customize..), but nothing changed.
Any idea what has to be done, that the icon changes according to the state?

Thank you very much in advance!!

BR
Chris

![Unbenannt](https://user-images.githubusercontent.com/22988621/86243567-e4741700-bba6-11ea-9478-0614d282aa9e.PNG)

**Comment by JoDehli** [comment]
Wie ich an deinen Screenshots erkennen kann sprichst du deutsch. Dann kann ich ja auch in deutsch antworten. 

Also das einfache überschreiben des Icons sollte normalerweise gehen. Ich mache das über die customize.yaml z.B. so:

sensor.fensterkontakt:
  icon: mdi:fire

Wenn du die aber nicht verwendest musst du es über da Frontend machen. 
![image](https://user-images.githubusercontent.com/32484282/86515157-62d6f000-be17-11ea-977e-9c7170c4a417.png)

![image](https://user-images.githubusercontent.com/32484282/86515170-784c1a00-be17-11ea-8ba3-a28eff04f230.png)

Was das Icon ändern je nach Status angeht sollte es eigentlich mit einem Template gehen. Aber das habe ich noch nie
gemacht. Da kann ich dir leider nicht weiterhelfen. Geht es denn mit einem Template bei anderen Home Assistant Komponenten? Oder ist das ein prinzipielles Problem?

**Comment by chrisrock1984** [comment]
Danke für deine Hilfe.
Da grundsätzliche ändern bzw. überschreiben des Icons funzt schon. Leider ändert es sich aber nicht dem Status entsprechend.
Versucht habe ich templates, if case und device class.
Ich schließe keine Fehler meinerseits aus, würde mir aber eine einfache Version wünschen das Icon dem Status entsprechend ändern zu können.

**Comment by JoDehli** [comment]
Also was ich machen würde, wäre einen Template Sensor mit einem Icon Template machen. Habe folgendes gerade
probiert und es funktioniert:

![image](https://user-images.githubusercontent.com/32484282/86530260-83568700-beb7-11ea-8937-6cf44d087754.png)

Vielleicht hilft dir das.

**Comment by chrisrock1984** [comment]
Vielen Dank!
Ich hätte noch eine Frage: kann ich das einfach im Lovelace Editor für ein Picture Element verwenden?

**Comment by JoDehli** [comment]
Das kann ich dir leider nicht sagen. Das musst du probieren.
