### ISSUE TITLE
Only current temperature on IRC2?

### ISSUE THREAD

**Issue by MaartenMees** [JoDehli/PyLoxone#296]
### Describe the bug

Before I could chose modes, Comfort etc.
No only current temperature is visible...

### Firmware of your Miniserver

Latest

### HomeAssistant install method

HAOS

### Version of HomeAssistant

Latest

### Version of Pyloxone

Latest

### Update pyloxone

Clean install

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by MaartenMees** [comment]
![Screenshot_20240815_001252_Chrome](https://github.com/user-attachments/assets/3bdf94ad-e178-4da3-ad39-144cfc6b7443)

The hvac modes are not the ones from loxone anymore..
Can't set temperature either

**Comment by JoDehli** [comment]
@MaartenMees can you provide a screenshot how you configured this entity. A screenshot from the loxone config so that I can add the same entity to my loxone. 

Maybe I can have a look. I know that something changed by purpose but I do not know it anymore.

**Comment by tgulikers** [comment]
I have the same issue. I used to be able to read the set temperature and use this in my dashboards, however it now does not contain this entity anymore.
my configuration is default thermostate function block in Loxone

**Comment by JoDehli** [comment]
@MaartenMees @tgulikers setting temperature is not supported anymore because I had weird behaviour when setting thru home assistant. For safety I disabled it. You can still switch between modes. Setting the temp should only be done thru loxone itself

**Comment by tgulikers** [comment]
@JoDehli Agree the logic should be controlled in Loxone and that's what I do in practice, yet I do read it in home assistant to visualise the set temperature. e.g. something like this, where there's an additional line per bar shown to indicate what the set temp is.

In case you don't intend to make this a read-only property, is there any modification I can do to bring this back in my own version?
![image](https://github.com/user-attachments/assets/f018aec2-4fe0-4e29-b65f-04e585a5597d)

**Comment by JoDehli** [comment]
@tgulikers if you only want to show the current set temp you can do it with a custom sensor. You can get all information from loxone into home assistant by using a custom sensor. There are already examples on the main GitHub page.

**Comment by Andre123123** [comment]
Before August, it was a nice feature that I could see the set and actual temperature and other information in a thermostat icon in hassio. Now you can only see the current temperature.  The window function is also no longer available... I use “betterthermostat” for visualization and now all functions are almost gone. Only the current temperature and the mode only work :(

**Comment by JoDehli** [comment]
@Andre123123 sorry but at the moment I support only this 2 values. If you want to set the temp make some more presets. This is the only workaround at the moment.

**Comment by hallerdavid** [comment]
i´m new to home assistant and also want to set the temp through homeassistant - i also want to add a timeplan later on.. can you describe what you mean with "make some more presets"? :-) I understand that you disabled this feature for security reasons. Thank you for your help!

**Comment by JoDehli** [comment]
@hallerdavid I meant you should use the loxone temperatures and timeplan for setting the climate. It is very powerful and configurable. More than you can do in homeassistant. That is why I do not implement the temperature setting. It fits not in the homeassistant component and we are not able to include all feature from loxone.

**Comment by hallerdavid** [comment]
Okay, i understand that - i think you and other PyLoxone users have differnet ways to use your integration :-) For my part, i want to replace the Loxone App with HomeAssistant App because i want more flexibility. For other users in my house i tried to integrate everything in Hass. For the moment i just have the problem with the thermostat.

Other idea: Is there a way to generate a "dummy" thermostat in Home Assistant? Then i can just send the "target value" to loxone and use this as input on the controller block there - but have the correct UI with target and actual temperature in Hass. 

I tried that with helper "generic thermostat" but this thing wants to controll a switch?? Maybe you can help me :-) 

Thank you!

**Comment by JoDehli** [comment]
@hallerdavid I do not want to force users to do it like I want it but it is the wrong way to replace all the logic or reimplent the logic from loxone into home assistant. The right way should be to make everything controllable from the home assistant. This is another approach. You can do everything with the current intention. You only need to think a bit differently. You can for example add additional elements in loxone to control your heatings.

**Comment by JoDehli** [comment]
> @MaartenMees @tgulikers setting temperature is not supported anymore because I had weird behaviour when setting thru home assistant. For safety I disabled it. You can still switch between modes. Setting the temp should only be done thru loxone itself

@Andre123123 @tgulikers 
I have added the ability for setting the target temp in manual mode back again. I do not use any of climate entities but I think this can be implemented with no risk. Maybe you can check it this works for your setup. You can find the small change in the branch: 
https://github.com/JoDehli/PyLoxone/tree/296-only-current-temperature-on-irc2

If you report that it is working as expected i will merge it in the next release.

**Comment by hallerdavid** [comment]
@JoDehli when you give me a short guid on how to implement the branch I can test it for you too :)

**Comment by JoDehli** [comment]
@hallerdavid download the branch and copy the source on your system.

**Comment by hallerdavid** [comment]
@JoDehli works as expected for me! :-) Thank you! 

When i set it to auto - everything is on the loxone timesheet. Set to heating, it is a fix value and is delivered perfectly to loxone. 

Not tested it a long time but i will switch one room and test it for a longer time. :-) 

When you published it to next release, do i have to delete the files manually or is it automatically overwritten by update process?

**Comment by JoDehli** [comment]
@hallerdavid I think they will be overwritten. But maybe you can keep an eye on it.

**Comment by hallerdavid** [comment]
i found one little point, maybe this is something you can fix - if not - it´s totally fine for me.:

when i switch to a preset (Voreinstellung) - comfort, eco, off - and then change the temperature in the ui from home assistant, the temperature timer in loxone is still set.

is there a way to "stop" the temperature timer in loxone when there is a manual override of the temperature?

**Comment by JoDehli** [comment]
@hallerdavid again a encountered strange behavior for setting the temperature and i will not include this feature until some solves it. Sorry but it is to important and I do not want to set strange temperatures.

**Comment by JoDehli** [comment]
@hallerdavid it has nothing got do with the stop timer. I encountered the bad behavior when I wanted to added the stop timer.

**Comment by hallerdavid** [comment]
i fixed it by switchting to "auto" and back to "heating" - so maybe you can implement it that way? A quick swap for one second to auto and back to heating.

**Comment by JoDehli** [comment]
@hallerdavid as I said o had another behaviour which has nothing to do with the timer. I tried to figure out why and what happened but I couldn't find the problem. For now it is better to control only the modus and leave the temperature in loxone.

**Comment by hallerdavid** [comment]
when i see your code right, its just the climate file what needs to be changed? So when i have some free time and find the error, and a solution for that, you can merge it? 

Can you describe what your error was so that i can find it?

**Comment by hallerdavid** [comment]
Do you want to find a solution in any way / with my help / without my help / should i search without you / ... - or do you say its not in your interest and you are not interested in finding a solution at the moment? :-) 

Its okay, if you don´t want to. Its you project and i love it. I understand that this is not your full time job and you don´t get money from this, so i´m totally fine when you say you don´t want to work on this at the moment. :-) 

Beside: Maybe it is an idea to set a checkbox with a warning in the configuration from the integration, where we can choose if we want to be able to set temperature and know that it can result in strange behaviors or not? So everybody could decide if they want to go the "risky not secure" way or the safer way? Don´t have to be a checkbox, a hidden option in the code or something could also be possible^^ - what do you think? Then we have the option for now and i can research and maybe find a solution for a future version with a fix.

**Comment by smarthomeagentur** [comment]
Hi, would be nice to solve that issue. I also don't think the ticket should be marked as "closed"

**Comment by Petahh** [comment]
> Hi, would be nice to solve that issue. I also don't think the ticket should be marked as "closed"

Create new virtual input and connect it to your thermostat and control temperature through that. It's a simple fix. I personally got rid of the thermostats all-together and use just virtual input.

**Comment by smarthomeagentur** [comment]
can you explain this a bit mire @Petahh ? I dont really understand. connect it to the loxone device or connect it to some loxone api? Thanks you so much

**Comment by pet3art** [comment]
@JoDehli seeing how many people miss the functionality of setting up the temps, would it be an option to release a fork with this enabled? So people that had a config with no issue, can continue using it. Just desperate... you know
thx

**Comment by pet3art** [comment]
@Petahh yeah, interested in your config as well, if you care to share the actual code ...
