### ISSUE TITLE
[Bug]: AttributeError: property 'unit_of_measurement' of 'LoxoneCustomSensor' object has no setter

### ISSUE THREAD

**Issue by bartn80** [JoDehli/PyLoxone#298]
### Describe the bug

Since the upgrade to HA 2024.8.1, I"m getting the "property 'unit_of_measurement' of 'LoxoneCustomSensor' object has no setter" again.

I've tried with and without unit of measurement and device class, all resulting into the same error. All of these custom sensors worked in the passed:

_#Loxone Power Sensors     
  - platform: loxone
    name: Actual Power Woning
    uuidAction: "18d9da90-023e-f0d2-ffff4d3205b8090d"
    device_class: "power"
    unit_of_measurement: "kW"
    state_class: "measurement"
  - platform: loxone
    name: Total Energy Woning
    uuidAction: "18d9da90-023e-f0d1-ffff4d3205b8090d"
    device_class: "energy"
    unit_of_measurement: "none"
    state_class: "total_increasing"_

### Firmware of your Miniserver

Firmware 15.1.8.5

### HomeAssistant install method

HACS

### Version of HomeAssistant

2024.8.1

### Version of Pyloxone

0.6.13

### Update pyloxone

Yes, this is currently the latest version. Also tried a full remove + reinstall.

### Log

_Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:364
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 21:17:31 (79 gebeurtenissen)
Laatst gelogd: 21:17:32

Error while setting up loxone platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/loxone/sensor.py", line 147, in async_setup_platform
    new_sensor = LoxoneCustomSensor(**config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/sensor.py", line 188, in __init__
    super().__init__(**kwargs)
  File "/config/custom_components/loxone/__init__.py", line 495, in __init__
    setattr(self, key, kwargs[key])
AttributeError: property 'unit_of_measurement' of 'LoxoneCustomSensor' object has no setter_

**Comment by JoDehli** [comment]
@bartn80 please update to 0.6.14 and try it. If it is fixed please close the issue.

**Comment by bartn80** [comment]
Fixed & closing this issue!
