### ISSUE TITLE
PushButton sends timestamp as state for both "pressed" and "unpressed" events

### ISSUE THREAD

**Issue by PavelPawlowski** [JoDehli/PyLoxone#299]
### Describe the bug

When a PushButton is Pressed in Loxone, the corresponding button object in HomeAssistant for both "Pressed" and "Unpressed" states have a timestamp in ithe state. So it is not possbile to distinguish those two events in any way as the current satate is nowehere available. (Previously when the PushButton was represented by switch in HA, it worked fine).

The state should be **on** /  **off** or **pressed** / **unpressed**. Or something what would allow to distinguish the two event types. Or Send only a single even on **Press** instaed of two events.

**Button Pressed Event Detail**
```JSON
{
  "payload": "2024-08-26T15:29:48.446374+00:00",
  "data": {
    "entity_id": "button.loxone_button_press_demo",
    "old_state": {
      "entity_id": "button.loxone_button_press_demo",
      "state": "2024-08-26T15:25:16.990973+00:00",
      "attributes": {
        "uuid": "182b9d23-01ca-2dda-ffffd1ffb7f86d13",
        "state_uuid": "182b9d23-01ca-2dd9-ffffa93911e485c3",
        "room": "Statusy",
        "category": "Ovládání",
        "device_type": "Pushbutton",
        "platform": "loxone",
        "friendly_name": "loxone_button_press_demo"
      },
      "last_changed": "2024-08-26T15:25:16.990994+00:00",
      "last_reported": "2024-08-26T15:29:48.370564+00:00",
      "last_updated": "2024-08-26T15:25:16.990994+00:00",
      "context": {
        "id": "01J67MN6SYP2S180BWVF1QJHSD",
        "parent_id": null,
        "user_id": null
      }
    },
    "new_state": {
      "entity_id": "button.loxone_button_press_demo",
      "state": "2024-08-26T15:29:48.446374+00:00",
      "attributes": {
        "uuid": "182b9d23-01ca-2dda-ffffd1ffb7f86d13",
        "state_uuid": "182b9d23-01ca-2dd9-ffffa93911e485c3",
        "room": "Statusy",
        "category": "Ovládání",
        "device_type": "Pushbutton",
        "platform": "loxone",
        "friendly_name": "loxone_button_press_demo"
      },
      "last_changed": "2024-08-26T15:29:48.446550+00:00",
      "last_reported": "2024-08-26T15:29:48.446550+00:00",
      "last_updated": "2024-08-26T15:29:48.446550+00:00",
      "context": {
        "id": "01J67MXFTFQ2HJ8NR7WNZS1C1Q",
        "parent_id": null,
        "user_id": "5244dadddac14f1b9c220a7741163d8a"
      },
      "timeSinceChangedMs": 15
    }
  },
  "topic": "button.loxone_button_press_demo",
  "_msgid": "ed64071f15c2f2c8"
}
```
**Button UnPressed Event Detail**
```JSON
{
  "payload": "2024-08-26T15:29:49.411075+00:00",
  "data": {
    "entity_id": "button.loxone_button_press_demo",
    "old_state": {
      "entity_id": "button.loxone_button_press_demo",
      "state": "2024-08-26T15:29:48.446374+00:00",
      "attributes": {
        "uuid": "182b9d23-01ca-2dda-ffffd1ffb7f86d13",
        "state_uuid": "182b9d23-01ca-2dd9-ffffa93911e485c3",
        "room": "Statusy",
        "category": "Ovládání",
        "device_type": "Pushbutton",
        "platform": "loxone",
        "friendly_name": "loxone_button_press_demo"
      },
      "last_changed": "2024-08-26T15:29:48.446550+00:00",
      "last_reported": "2024-08-26T15:29:48.446550+00:00",
      "last_updated": "2024-08-26T15:29:48.446550+00:00",
      "context": {
        "id": "01J67MXFTFQ2HJ8NR7WNZS1C1Q",
        "parent_id": null,
        "user_id": "5244dadddac14f1b9c220a7741163d8a"
      }
    },
    "new_state": {
      "entity_id": "button.loxone_button_press_demo",
      "state": "2024-08-26T15:29:49.411075+00:00",
      "attributes": {
        "uuid": "182b9d23-01ca-2dda-ffffd1ffb7f86d13",
        "state_uuid": "182b9d23-01ca-2dd9-ffffa93911e485c3",
        "room": "Statusy",
        "category": "Ovládání",
        "device_type": "Pushbutton",
        "platform": "loxone",
        "friendly_name": "loxone_button_press_demo"
      },
      "last_changed": "2024-08-26T15:29:49.411206+00:00",
      "last_reported": "2024-08-26T15:29:49.411206+00:00",
      "last_updated": "2024-08-26T15:29:49.411206+00:00",
      "context": {
        "id": "01J67MXFTFQ2HJ8NR7WNZS1C1Q",
        "parent_id": null,
        "user_id": "5244dadddac14f1b9c220a7741163d8a"
      },
      "timeSinceChangedMs": 13
    }
  },
  "topic": "button.loxone_button_press_demo",
  "_msgid": "c546c35ad793d131"
}
```

### Firmware of your Miniserver

11.1.9.14

### HomeAssistant install method

HACS

### Version of HomeAssistant

2024.8.3

### Version of Pyloxone

0.6.14

### Update pyloxone

Yes, updated to the latest version:

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by PavelPawlowski** [comment]
It would be fine with the timestamp in the state, if only one event would be sent to HA, but there are two events behing sent to HA within several milliseconds.

**Comment by JoDehli** [comment]
@PavelPawlowski no it should behave exactly like other buttons. I see no solution to change that.

**Comment by JoDehli** [comment]
@PavelPawlowski see also https://github.com/JoDehli/PyLoxone/issues/294#issuecomment-2272765678

**Comment by JoDehli** [comment]
The button entity is stateless. https://developers.home-assistant.io/docs/core/entity/button/

**Comment by PavelPawlowski** [comment]
I understand that it is stateless. Then it is fine when the button is pressed and as a state a timestamp is sent.

But the problem is that a single press of the button in loxone sends two events into HA, so like two presses in a row.

line in the code example above:

**With Single Press of button:**

First event received in HA:

```JSON
{
  "payload": "2024-08-26T15:29:48.446374+00:00"
}
```
Second event received in HA a second later
```JSON
{
  "payload": "2024-08-26T15:29:49.411075+00:00"
}
```

**Comment by gigatexel** [comment]
> I understand that it is stateless. Then it is fine when the button is pressed and as a state a timestamp is sent.
> 
> But the problem is that a single press of the button in loxone sends two events into HA, so like two presses in a row. (with original switch implementation it was fine, butecause first event was "on" and second event was "off". But with the PushButton, two events with timestamp arrive instead of single event.)
> 
> Like in the code example I've reported.
> 
> **With Single Press of button:**
> 
> First event received in HA:
> 
> ```json
> {
>   "payload": "2024-08-26T15:29:48.446374+00:00"
> }
> ```
> 
> Second event received in HA a second later
> 
> ```json
> {
>   "payload": "2024-08-26T15:29:49.411075+00:00"
> }
> ```
> 
> Other PressButtons in HA when pressed, theye send single event with timestamp as state.

As you state in your reply: the problem is that Loxone Miniserver sends two events. There should be only one.
Your loggings confirm that there is no way do distinguish between the Loxone Button-down and Loxone Button-up. This is something that Loxone should fix.

What are you trying to accomplish? Maybe we can help.

**Comment by JoDehli** [comment]
@gigatexel thanks for your explanation. 

@PavelPawlowski I think at the moment we can not improve it.

**Comment by brechtvhb** [comment]
When rebooting Loxone the pushbuttons also trigger automations that listen for "button pressed" events. Is here a way to make sure this does not happen?

**Comment by gigatexel** [comment]
> When rebooting Loxone the pushbuttons also trigger automations that listen for "button pressed" events. Is here a way to make sure this does not happen?

As far as I know, the Loxone MS sends a full refresh on each reboot.
But since buttons are stateless by convention, it is not a great idea to trigger HA automations based on a button state.
Buttons are entities that need to be pushed, not to be used as a state-trigger in an automation.

**Comment by brechtvhb** [comment]
Not really using a state trigger. Guess I'll have to change my push buttons to switches in loxone.

```
  - platform: device
    device_id: 37766f907e435fb51b172c63309e6164
    domain: button
    entity_id: f3f6afffbd7409c8aef47b05db4edd4e
    type: pressed
```

**Comment by gigatexel** [comment]
> Not really using a state trigger. Guess I'll have to change my push buttons to switches in loxone.
> 
> ```
>   - platform: device
>     device_id: 37766f907e435fb51b172c63309e6164
>     domain: button
>     entity_id: f3f6afffbd7409c8aef47b05db4edd4e
>     type: pressed
> ```

I understand what you are trying to do, but due to the implementation on the miniserver this would indeed cause false triggers.

**Comment by gigatexel** [comment]
Did you try using a switch to circumvent this implementation error in the miniserver?

**Comment by PavelPawlowski** [comment]
> Did you try using a switch to circumvent this implementation error in the miniserver?

But it is not an error in miniserver. It is how miniserver works. The push Button has two states in loxone, pressed and released.  It is like physical push button, when you press it down and hold, it will have state pressed until you release your finger form the button. When you release your finger from the push button, its state will change to not pressed. 

In loxone it is not a state less event. It is really button which state is either pressed or released, while in home assistant a button is a stateless object which sends pressed notification.

Loxone config flow work with states only, there is nothing like stateless event. Even 1 second tick in loxone is sequent of binary 1 and binary 0 followed. 

For my purpose  I have handled that in node red with rate limiter and dropping the additional event, but in general the Button implementation in pyLoxone for the pushbutton is useless.

The previous implementation in form of switch was working as expected for the loxone push button.

Or if it would be possible to send the real loxone state on/off in the payload of the button press to HA instead of timestamp, then it would be also fine, as yo can distinguish those two events.

if the timestamp is automatically filled by HA in the hass.bus.fire method, then "Switch" is much better implementation of the Loxone PushButton than the Button implementation.

**Comment by JoDehli** [comment]
@PavelPawlowski @gigatexel the previous implementation was also ok for me.  It I think now we made the switch and we should not go back. So many users had converted there automations and switch back and forth is not a good solution.

@PavelPawlowski I think there is a helper to convert entities to different types. Maybe you can try this.

**Comment by PavelPawlowski** [comment]
> @PavelPawlowski @gigatexel the previous implementation was also ok for me. It I think now we made the switch and we should not go back. So many users had converted there automations and switch back and forth is not a good solution.

But if people have converted from swtch to butrton, how they are handlig the button press? Now you are always receiving two mesages and you are not able to distinguish betwen them. So for each usage you need to implement a workaround in Home Assistenat.

If you crate whatevenr automation on top the but button press, it is fired two time, if you do not implement a rate limiter.  But the rate limiter is only a workaround as it can limit real quick multiple presses of the push button.

With the swith implementation, when you needed to "press" the button, you could utilize the swith.toggle and it worked bort from UI and automations. And when listening on the button pres, you could listen for the the swith "on" event. 

**What about adding another binary_sensor entity under the Loxone Button Device? Would this be doable? When you need to listen for evets from loxone you could use that binary_sensor and when you need to perform an action from Home Assistant or would like to put it into the UI, you would use the existing Button?**

**Comment by PavelPawlowski** [comment]
@JoDehli this would be fine. 

Btw what about, creating the binary_sensor under the device side by side with the Button?

As mentioned, when you need to listen to events from Loxone then you could utilize the binary_sensor and in other cases use the button, which is fine for other cases.
