### ISSUE TITLE
Error in log viewer file

### ISSUE THREAD

**Issue by jdenver13** [JoDehli/PyLoxone#3]
'''
WARNING (MainThread) [homeassistant.helpers.service] Unable to find services.yaml for the loxone integration
'''
Any ideas how to correct this error please.

**Comment by JoDehli** [comment]
This is only a warning an can be ignored. In the newer versions of hassio components need a service.yaml which can be empty. Then the error will be gone.

**Comment by JoDehli** [comment]
Should be fixed. Added service.yaml.
