### ISSUE TITLE
[Bug]: HACS 2.0 Update - Websocket not working anymore

### ISSUE THREAD

**Issue by Eng-7** [JoDehli/PyLoxone#300]
### Describe the bug

After updating of HACS to version 2.0, the websocket service no longer available and Home Assistant throws following error in the console:

Logger: homeassistant.components.script.loxone_websocket
Quelle: helpers/script.py:2030
Integration: Skript (Dokumentation, Probleme)
Erstmals aufgetreten: 13:17:53 (114 Vorkommnisse)
Zuletzt protokolliert: 13:25:17

Loxone Websocket: Error executing script. Service not found for call_service at pos 1: Action loxone.event_websocket_command not found

Unfortanly I already loaded a backup of Home Assistant and so I could not change the log level to debug for more information. 
Here are the breaking changes from HACS:
https://github.com/hacs/integration/releases

Thx for the help!

### Firmware of your Miniserver

15.1.8.5

### HomeAssistant install method

Manual: Script for Proxmox

### Version of HomeAssistant

2024.8.3

### Version of Pyloxone

0.6.14

### Update pyloxone

Already on the latest version

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@Eng-7 I think it has nothing to do with hacs. Have you tried to call the websocket command manually? If there occurs an error can you provide it. 

On my system with the newest hacs and pyloxone it works.

**Comment by Eng-7** [comment]
Strange, I updated again HACS to the newest version and now Pyloxone works without any problems. I tested the websocket over the developer tools and it also works fine. So
