### ISSUE TITLE
[Bug]: PyLoxone not working after Firmware Upgrade to

### ISSUE THREAD

**Issue by PatchPaladin** [JoDehli/PyLoxone#301]
### Describe the bug

After the Upgrade to the newest firmware the Integration is not working.  All entities are showing as unavailable. 

### Firmware of your Miniserver

15.1.8.20

### HomeAssistant install method

Hacs

### Version of HomeAssistant

2024.8.3

### Version of Pyloxone

0.6.14

### Update pyloxone

Already latest

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@PatchPaladin update hacs reinstall pyloxone and restart.

**Comment by PatchPaladin** [comment]
Worked! Sorry and thank you!

**Comment by PatchPaladin** [comment]
Update, reinstall fixed the issue.
