### ISSUE TITLE
Already solved in the newest Version of Pyloxone: Integration calls async_forward_entry_setup for integration which is deprecated and will stop working in Home Assistant 2025.6

### ISSUE THREAD

**Issue by tegner23** [JoDehli/PyLoxone#307]
### Describe the bug

Home Assistant Core Protocol shows warning messages with following text:

Message 1:
Detected that custom integration 'loxone' calls async_forward_entry_setup for integration, loxone with title: PyLoxone and entry_id: eb1b8dcbd3eeed8f438f98c2d4ee11af, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/loxone/__init__.py, line 191: hass.async_create_task(, please create a bug report at https://github.com/JoDehli/PyLoxone/issues
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:184
![image](https://github.com/user-attachments/assets/f8ddd6c7-5a7b-4db8-98e0-22455eeba923)

Message 2:
Detected that custom integration 'loxone' calls async_forward_entry_setup for integration, loxone with title: PyLoxone and entry_id: eb1b8dcbd3eeed8f438f98c2d4ee11af, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/loxone/__init__.py, line 385: hass.async_create_task(, please create a bug report at https://github.com/JoDehli/PyLoxone/issues
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:184
![image](https://github.com/user-attachments/assets/121f1c06-4501-4df7-b644-f0725d5476ec)

Message 3:
Detected code that calls async_forward_entry_setup for integration loxone with title: PyLoxone and entry_id: eb1b8dcbd3eeed8f438f98c2d4ee11af, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:151

### Firmware of your Miniserver

Firmware: 15.1.8.20

### HomeAssistant install method

PI5 8GB, NVME SSD

### Version of HomeAssistant

2024.9.3

### Version of Pyloxone

0.6.9

### Update pyloxone

No newer version available

### Log

Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:151
Erstmals aufgetreten: 20:55:57 (11 Vorkommnisse)
Zuletzt protokolliert: 20:55:57

Detected code that calls async_forward_entry_setup for integration loxone with title: PyLoxone and entry_id: eb1b8dcbd3eeed8f438f98c2d4ee11af, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by JoDehli** [comment]
@tegner23 for you detailed report. It is very helpful when you provide details. But your version of pyloxone is very old. This issue is solved a view versions ago. So please update to the newest version of pyloxone.
