### ISSUE TITLE
Can't see any devices with Touch Surface

### ISSUE THREAD

**Issue by Saviq** [JoDehli/PyLoxone#31]
Hey, I agree documentation could be improved… I'm trying to integrate with a [Touch Surface](https://www.loxone.com/enen/new-touch-surface/), I can see it and configure within Loxone Config, but I can't seem to get anything out of it inside Home Assistant… I only get the Loxone groups, but no devices… Maybe there's a step I'm missing, I tried to follow the code in [`__init__.py`](https://github.com/JoDehli/PyLoxone/blob/master/custom_components/loxone/__init__.py), but couldn't find where the devices are discovered at all…

_Originally posted by @Saviq in https://github.com/JoDehli/PyLoxone/issues/26#issuecomment-657197065_

**Comment by Saviq** [comment]
Do you see your devices on your Loxone App? Can you provide log files?
Do you use port 80? If so please change it to a other port.

_Originally posted by @JoDehli in https://github.com/JoDehli/PyLoxone/issues/26#issuecomment-658919081_

**Comment by Saviq** [comment]
> Do you see your devices on your Loxone App? Can you provide log files?

That's probably part of the problem - I have _zero_ experience with Loxone, and only have the two Touch Surfaces now (as those go under the tiles here). Here's the homeassistant logs with debugging enabled for loxone: [loxone.log](https://github.com/JoDehli/PyLoxone/files/4927361/loxone.log).

> Do you use port 80? If so please change it to a other port.

I am, will do.

**Comment by JoDehli** [comment]
You have absolutely no devices expect of the touch surfaces? Because I think the touch surface will not work. I can not test it because I can not add it to my loxone. I need a tree or air extension. So maybe this add-on is not working for your setup.

**Comment by Saviq** [comment]
> You have absolutely no devices expect of the touch surfaces? Because I think the touch surface will not work. I can not test it because I can not add it to my loxone. I need a tree or air extension. So maybe this add-on is not working for your setup.

I have the Miniserver Go, a Tree Extension and a couple Touch Surface Trees. It's working just fine, I was able to both control its LEDs and a Yamaha AVR over a virtual HTTP output, which is the primary use case here.

**Comment by Saviq** [comment]
I'm starting to learn how Loxone sees this and after configuring some entities in Loxone Config I can now see a Switch in the web interface, and expect that to show up in Home Assistant (just testing now).

**Comment by Saviq** [comment]
And yes, that's exactly it. I just didn't (don't) know enough about Loxone to have understood where are those entities supposed to be coming from :)

Thanks @JoDehli for nudging me to try some things out again.
