### ISSUE TITLE
Attributes removed from digital sensors

### ISSUE THREAD

**Issue by romerod** [JoDehli/PyLoxone#316]
### Describe the bug

In version 6.12 the extra_states_attributes was removed. I was using the uuid from the attributes to send a direct websocket command. This was pretty nice instead of hardcoding the uuid.
https://github.com/JoDehli/PyLoxone/pull/289/files#diff-8a90778eed853464afcad96a79137446b7172ff4319526a2d0d21fbf163e7757L133
Can this be added back?

### Firmware of your Miniserver

14.5.12.7

### HomeAssistant install method

docker

### Version of HomeAssistant

2024.10.4

### Version of Pyloxone

0.6.16

### Update pyloxone

yes

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@romerod can you try this branch https://github.com/JoDehli/PyLoxone/tree/316-bug-attributes-removed-from-digital-sensors

**Comment by JoDehli** [comment]
@romerod you must copy it manually. Hacs does not support branches only releases.

**Comment by JoDehli** [comment]
@romerod any success?

**Comment by romerod** [comment]
Was just able to check it now, works like a charm, thank you.
