### ISSUE TITLE
Input_number broken after activating PyLoxone

### ISSUE THREAD

**Issue by Shogun1978** [JoDehli/PyLoxone#32]
Hi,
I am using PyLoxone since some time. Now I wanted to set an input_number to define an alarm clock. The input_number can be set, but it doesn't change the value. If I disable PyLoxone (just # in front of the Loxone config lines in configuration.yaml) , the input_number works again.
Could you please take a look?
Regards,
Harald

**Comment by JoDehli** [comment]
Hi, 
the input number works for me without problems. Can you please post a configuration.yaml with a minimal example. Furthermore you can post the log output of the Pyloxone? Do you get any errors displayed?

**Comment by Shogun1978** [comment]
Sure, here is the configuration.yaml:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

#group: !include groups.yaml


#Home Assistant internals
homeassistant:
   time_zone: Europe/Berlin
   packages:
       alarm_1: !include alarm_bedroom.yaml

#Loxone
loxone:
  port: xxxx
  host: xxx.xxx.xxx.xxx
  username: username
  password: password
  generate_scenes: false # default is true

Unfortunately, I don't get any errors. It doesn't matter, if I create an input_number within a file (in this example I define an alarm clock in a separate file) or as a helper in the UI. The moment I comment all PyLoxone parts, the input_number works again.

Tested in HA supervised install and HA docker. The issue is reproducable.

**Comment by JoDehli** [comment]
Hi,

yes I can reproduce it. It is the EntityComponent for the Input_selects in the file switch.py.
When I comment the lines from 67-95 out like in the code below. Then the inputs work but you lost the 
inputs from loxone. I have no solution for it now. Maybe someone else knows a solution. 

```python
        # elif switch_entity['type'] in ['LeftRightAnalog', 'UpDownAnalog', 'Slider']:
        #     switch_entity.update({'uuidAction': switch_entity['uuidAction'],
        #                           'name': switch_entity['name'],
        #                           'initial': switch_entity['details']['min'],
        #                           'min': switch_entity['details']['min'],
        #                           'max': switch_entity['details']['max'],
        #                           'step': switch_entity['details']['step'],
        #                           'cat': get_cat_name_from_cat_uuid(loxconfig, switch_entity.get('cat', '')),
        #                           'room': get_room_name_from_room_uuid(loxconfig, switch_entity.get('room', ''))
        #                           })
        #
        #     if switch_entity['type'] == 'UpDownAnalog':
        #         switch_entity.update({'mode': 'box'})
        #     else:
        #         switch_entity.update({'mode': 'slider'})
        #
        #     new_loxone_input_select = LoxoneInputSelect(**switch_entity)
        #     hass.bus.async_listen(EVENT, new_loxone_input_select.event_handler)
        #     entities.append(new_loxone_input_select)

    # component = EntityComponent(_LOGGER, 'input_number', hass)
    # component.async_register_entity_service(SERVICE_INCREMENT, {}, "async_increment")
    # component.async_register_entity_service(SERVICE_DECREMENT, {}, "async_decrement")
    # component.async_register_entity_service(
    #     SERVICE_SET_VALUE,
    #     {vol.Required('value'): vol.Coerce(float)},
    #     "async_set_value",
    # )
    # await component.async_add_entities(entities)
```

**Comment by Shogun1978** [comment]
Yeah, I also saw that there is just an input_number in the switch file. But I am not a programmer. Is there a way for a workaround? I will try to define the inout_number before and after the installation of pyloxone. Maybe it makes a difference. How did you make it work in your environment?

**Comment by Shogun1978** [comment]
Ok, seems like it doesn't matter when I create the input_number before or after setting up the PyLoxone integration. Pity that I can't make it work :-(

**Comment by JoDehli** [comment]
I do not know how to solve it without breaking the loxone input. But of course I will try it. Maybe I ask in the forum for help. What you can do is comment out the lines  from my last comment. You lose the loxone input and sliders but you can get the alarm input to work.

**Comment by Shogun1978** [comment]
Right now I just use one input_number slider (due to the issue) but six or seven dimmer from Loxone (which rely on your implementation). I hope, you can solve the issue, but I won't break your great implementation (as Loxone bothers me more and more ;-) ).

**Comment by JoDehli** [comment]
I asked in the Forum:

**Comment by Shogun1978** [comment]
That would be awesome. Your integration really allowed me to move away from the Loxone frontend. So thank you for all you work you put in here!

**Comment by Shogun1978** [comment]
I managed to build a workaround. Maybe not the best solution, but it works:
I installed a second HA instance (docker, supervised, whatever) and used the "Remote Home-Assistant" integration from HACS. Then I just linked my main HA instance to the second instance and installed on the second instance just PyLoxone as integration. The rest is installed on my main HA instance. Even though it's not the most elegant solution, it works for me :-)

**Comment by JoDehli** [comment]
@Shogun1978 I removed the support for the Input_number because they are not supported to generate dynamically. I asked for a solution in the forum and on discord and they told me that I can not get it to work properly. You can stick with the old version on your  second HA instance. Maybe they implement the Input_numbers as normal component. Then it would be a easy task to integrate it. They already discuss that. Maybe we have luck and in future I can implement this feature.

**Comment by JoDehli** [comment]
@Shogun1978 I also updated the documention for integrating the inputs via a loxone websocket command. Maybe you can use this. 
Please see here:
https://github.com/JoDehli/PyLoxone#example-2-with-a-updownanalog
