### ISSUE TITLE
[Bug]: unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by 4jandals** [JoDehli/PyLoxone#324]
### Describe the bug

I've restored a backup of home assistant onto a new server and am having trouble with PyLoxone. The error I'm seeing in the log is `unexpected keyword argument 'timeout'`. I've attached the log below. I've tried removing the library from HACS and reinstalling but that hasn't helped. PyLoxone is still working as expected on my old home assistant server. 

```
home-assistant  | 2024-11-09 20:47:19.398 DEBUG (MainThread) [custom_components.loxone.api] get_public_key 
...
home-assistant  | 2024-11-09 20:47:19.582 DEBUG (MainThread) [custom_components.loxone.api] init_rsa_cipher successfully...
home-assistant  | 2024-11-09 20:47:19.591 DEBUG (MainThread) [custom_components.loxone.api] generate_session_key successfully...
home-assistant  | 2024-11-09 20:47:19.604 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
home-assistant  |     result = await component.async_setup_entry(hass, self)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/loxone/__init__.py", line 415, in async_setup_entry
home-assistant  |     res = await miniserver.start_ws()
home-assistant  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
home-assistant  |     res = await self.api.async_init()
home-assistant  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/loxone/api.py", line 426, in async_init
home-assistant  |     self._ws = await wslib.connect(
home-assistant  |                ^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 441, in __await_impl__
home-assistant  |     self.connection = await self.create_connection()
home-assistant  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 367, in create_connection
home-assistant  |     _, connection = await loop.create_connection(factory, **kwargs)
home-assistant  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  | TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'timeout'
```

### Firmware of your Miniserver

12.0.2.24

### HomeAssistant install method

Docker

### Version of HomeAssistant

2024.11.1

### Version of Pyloxone

0.6.16

### Update pyloxone

Yes

### Log

```
home-assistant  | 2024-11-09 20:47:19.398 DEBUG (MainThread) [custom_components.loxone.api] get_public_key 
...
home-assistant  | 2024-11-09 20:47:19.582 DEBUG (MainThread) [custom_components.loxone.api] init_rsa_cipher successfully...
home-assistant  | 2024-11-09 20:47:19.591 DEBUG (MainThread) [custom_components.loxone.api] generate_session_key successfully...
home-assistant  | 2024-11-09 20:47:19.604 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PyLoxone for loxone
home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
home-assistant  |     result = await component.async_setup_entry(hass, self)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/loxone/__init__.py", line 415, in async_setup_entry
home-assistant  |     res = await miniserver.start_ws()
home-assistant  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
home-assistant  |     res = await self.api.async_init()
home-assistant  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/loxone/api.py", line 426, in async_init
home-assistant  |     self._ws = await wslib.connect(
home-assistant  |                ^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 441, in __await_impl__
home-assistant  |     self.connection = await self.create_connection()
home-assistant  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 367, in create_connection
home-assistant  |     _, connection = await loop.create_connection(factory, **kwargs)
home-assistant  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  | TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'timeout'
```

**Comment by JoDehli** [comment]
@4jandals try deinstall and install again.

**Comment by Ofensepp** [comment]
Think a had also a Problem with "Unexpected keyword argument"

Error happend after switch to a new server with a backup.. i tried reinstall, new User in Loxone.. without success. Today i reinstalled HA and start without backup.. Only Addon was PyLoxone... same issue.


Logger: homeassistant.config_entries
Quelle: config_entries.py:635
Erstmals aufgetreten: 17:53:47 (1 Vorkommnisse)
Zuletzt protokolliert: 17:53:47

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/loxone/init.py", line 415, in async_setup_entry
res = await miniserver.start_ws()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
res = await self.api.async_init()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/loxone/api.py", line 426, in async_init
self._ws = await wslib.connect(
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 441, in await_impl
self.connection = await self.create_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 367, in create_connection
_, connection = await loop.create_connection(factory, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'timeout'

**Comment by prophylaxe** [comment]
Same for me, but in my case after updating from Core 2024.10.4 to Core 2024.11.1


`Logger: homeassistant.config_entries
Quelle: config_entries.py:635
Erstmals aufgetreten: 16:39:03 (4 Vorkommnisse)
Zuletzt protokolliert: 16:50:51

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/__init__.py", line 415, in async_setup_entry
    res = await miniserver.start_ws()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
    res = await self.api.async_init()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/api.py", line 426, in async_init
    self._ws = await wslib.connect(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 441, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 367, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'timeout'`

**Comment by 4jandals** [comment]
Thanks @JoDehli ! - that fixed the issue for me
