### ISSUE TITLE
[Bug]: Pyloxone requires websockets==11.0

### ISSUE THREAD

**Issue by kl4ver** [JoDehli/PyLoxone#334]
### Describe the bug

Pyloxone requires websockets==11.0 and ring requires websockets>=13.0

this may also effect other integrations that use websockets

See this issue here - https://github.com/home-assistant/core/issues/130725

### Firmware of your Miniserver

Na

### HomeAssistant install method

Na

### Version of HomeAssistant

2024.11.2

### Version of Pyloxone

Latest

### Update pyloxone

Yes

### Log

Settings for the log can be found on the main page under the section Log Configuration

**Comment by JoDehli** [comment]
@kl4ver should be fixed with the merge https://github.com/JoDehli/PyLoxone/pull/336
