### ISSUE TITLE
[Bug]: pushbuttons after HA restart

### ISSUE THREAD

**Issue by hallerdavid** [JoDehli/PyLoxone#343]
### Describe the bug

I have some pushbuttons (Taster) in Loxone, which are triggerd by other things in Loxone.

I use them in Homeassistant to trigger some automations (pushbutton in my room for light on -> loxone -> pyloxone -> automation) 

everytime when i restart homeassistant the pushbutton is "pressed" (HA thinks it is pressed) but it isnt! So everytime i restart HA the automation gets triggerd.

Is there something i made wrong? Can you help?

### Firmware of your Miniserver

15.1.8.20

### HomeAssistant install method

HA OS

### Version of HomeAssistant

Core
2024.11.2
Supervisor
2024.11.3
Operating System
13.2
Frontend
20241106.2

### Version of Pyloxone

actual

### Update pyloxone

actual

**Comment by JoDehli** [comment]
@hallerdavid  please read thru already closed issues before opening a new one. I think it is already discussed.

**Comment by hallerdavid** [comment]
Sorry you are right. I have done this after submitting the ticket.

So if I understood it right, the Pushbutton has no state expect the time and the time changes after reboot and that triggers the automation.

Two questions:

Is there a workaround with the pushbutton (not using the automation after reboot for 60 seconds or something like that)? 

Or

Is it an workaround to use a switch and set it on loxone side to "on" and directly to "off" 0,3seconds later?

Thank you for your great work and sorry for my dumb newbie questions 😖 I will try to do more research before opening tickets in the future ☺️

**Comment by JoDehli** [comment]
@hallerdavid you can use a normal switch and run the automation when the switch is triggered. In the automation you can incidentally turn it off again.

**Comment by hallerdavid** [comment]
Thank you! I did it with resetting the switch directly in loxone, its easier to use double tab now on a few pushbuttons. Where it wasnt needed to use doubletap i reset it in HA. 

Thank you very much for your help. I will close this. :-)
