### ISSUE TITLE
Too old Homeassistent Version for newest Pyloxone 

### ISSUE THREAD

**Issue by jlmadrugac** [JoDehli/PyLoxone#347]
### Describe the bug

From 10 days ago, my integration is failed... not sure if its because an update of the miniserver or the PyLoxone or the ha
Im pasting the log file
[home-assistant_2024-11-26T22-08-08.620Z.log](https://github.com/user-attachments/files/17926367/home-assistant_2024-11-26T22-08-08.620Z.log)

### Firmware of your Miniserver

15.2.10.14

### HomeAssistant install method

Raspberry py via proxmox

### Version of HomeAssistant

2024.9.1

### Version of Pyloxone

0.7.1

### Update pyloxone

Yes

### Log

Settings for the log can be found on the main page under the section Log Configuration 
[home-assistant_2024-11-26T22-08-08.620Z.log](https://github.com/user-attachments/files/17926383/home-assistant_2024-11-26T22-08-08.620Z.log)

**Comment by JoDehli** [comment]
@jlmadrugac the newest pyloxone works only with the newest Homeassistent version.

**Comment by JoDehli** [comment]
@jlmadrugac any success?

**Comment by jlmadrugac** [comment]
Yes, I had problems with the update to the latest version of Homeassistant, but was related to the free space.
With the new version all works perfect.

Thanks!
