### ISSUE TITLE
RuntimeError: Attribute hass is None

### ISSUE THREAD

**Issue by PavelPawlowski** [JoDehli/PyLoxone#39]
Buch of  RuntimeError: Attribute hass is None is appearing in log 

2020-11-23 14:17:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/loxone/sensor.py", line 212, in event_handler
self.schedule_update_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state
assert self.hass is not None
AssertionError

2020-11-23 14:17:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/loxone/light.py", line 399, in event_handler
self.async_schedule_update_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 441, in async_schedule_update_ha_state
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 289, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Hlavní tlačítko: off>

**Comment by JoDehli** [comment]
What Version of HA do you have installed? I can not reproduce this error?

**Comment by PavelPawlowski** [comment]
I have latest version of the HA 0.118.2

System Health

Home Assistant Core Integration

version: 0.118.2
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.77
arch: x86_64
timezone: Europe/Prague

Hass.io

host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
healthy: true
supported: true
board: intel-nuc
supervisor_api: ok
version_api: ok

**Comment by PavelPawlowski** [comment]
I only add, the everything seems to be running as expected, only buch of those errors in the log...

**Comment by PavelPawlowski** [comment]
Looks like I have found when it happens.

Looks like the errors are occurring for entities which I have disabled in the GUI, so they do not appear in HA.. And looks like when PyLoxone tries to update their status, then error is fired (as those are not active in HA).

I will do additional checks and will confirm.

**Comment by PavelPawlowski** [comment]
Now I can confirm the problem is related to the disabled entities.

For example I have light controllers with moods. The PyLoxone creates entities for each mood as well as the Central switch for that light controller. In my setup I do not need the central switch so I disabled it in the HA so it does not appears in the lists.

Once the entity is disabled, PyLoxone it causes the above errors to appear when PyLoxone states are refreshed.

After re-enabling and restarted HA the errors disappeared. So as mentioned above some problem with refresh of entities when they are disabled in HA.

**Comment by JoDehli** [comment]
Ok thanks for your time you spent to find out whats wrong. But I can not reproduce it on my system. 
I found a similar thread: 
https://github.com/StyraHem/ShellyForHASS/issues/341
My system is very small and my load is not so high.

Sorry but I will keep in mind this problem. Maybe I can force this error somehow.
