### ISSUE TITLE
Show state of lights (sensors)

### ISSUE THREAD

**Issue by lvstb** [JoDehli/PyLoxone#40]
In home assistant my sensors only show a short pulse (push button) but not the correct state of my lights. 
Is it possible to retrieve the state of lights via loxone and show them in Home assitant?

**Comment by JoDehli** [comment]
What sensors? Please give me more informations about your setup on the loxone side? What sensors typs in loxone? Sensor or lights?

**Comment by lvstb** [comment]
The outputs is what i mean (the lights). I would like to have them as a sensor in home assistant. If i do a GET on LOXONE-IP/dev/sps/io/OUTPUT_LOXONE/state the state is visible.

**Comment by JoDehli** [comment]
Do you see your lights in your loxone App. Maybe Log the startup of home assistant.

**Comment by JoDehli** [comment]
it is best to set the log settings so that only the log entries of the Loxone are output.

**Comment by lvstb** [comment]
I only now realised your integration makes uses of my loxone app configuration. I just enabled the output in the loxone app and now i see the status of my lights in home assistant.
Thanks!
Keep up the great work.
