### ISSUE TITLE
Sensor values drop to 0 when restarting HA

### ISSUE THREAD

**Issue by MrIncredible007** [JoDehli/PyLoxone#42]
Hi,

When I restart HA, all my sensors (InfoOnlyAnalog) drop to 0 when PyLoxone is initialising. Is there someting I can do to avoid this behaviour?

![image](https://user-images.githubusercontent.com/24842474/101899656-7482a780-3bae-11eb-8902-c7a95cbf66a0.png)

**Comment by JoDehli** [comment]
I can try to fix it in the next release

or 

you can try a Filter: https://www.home-assistant.io/integrations/filter

when you do not have a lot of sensors.

**Comment by JoDehli** [comment]
@MrIncredible007 try the new release and please give me feedback if the 0 are gone.

**Comment by MrIncredible007** [comment]
@JoDehli Problem solved! Thanks for the quick reply. Thank you for this amazing binding!
