### ISSUE TITLE
Add repository.json

### ISSUE THREAD

**Issue by zathras777** [JoDehli/PyLoxone#44]
From a new install of HA I am unable to add this as a new add-on repository due to a missing repository.json file. Can you add one?

**Comment by JoDehli** [comment]
This is not a add-on this is only a custom component. I do not understand why I need a repository.json?

**Comment by zathras777** [comment]
Ok. While being new to HA I tried to follow your instructions in the
README, then google and was led to the add-on repository rather than HACS.
Apologies.
