### ISSUE TITLE
Ability to specify Unit of Measurement for sensors?

### ISSUE THREAD

**Issue by duarteveiga** [JoDehli/PyLoxone#46]
Is it possible to specify the Unit of Measurement for the sensors that Pyloxone provides to HA? My scenario is that I can see for instance my temperature sensor and the right values in Home Assistant, however when I try to put them on history graphs, instead of a proper line graph I get a bars graph because home assistant says that the related sensors do not have a specified unit of measure.

Is this something that I should already be able to do or a new feature required on PyLoxone?

Thanks!

**Comment by JoDehli** [comment]
My sensors show up perfectly in home assistant when I define the unit on the loxone side. I use metric units. What unit system do you use? 

Can you provide some pics from your loxone sensor configuration and some more informations of the values on the home assistant side? 

You can also customize any entity in home assitant: 

For example I tested this stupid example:

sensor.cpu_temperatur_loxone_extension:
  unit_of_measurement:  meter

Read more on: 
https://www.home-assistant.io/docs/configuration/customizing-devices/

**Comment by JoDehli** [comment]
@duarteveiga a little note I expect a white-space before the unit. For example on the loxone side a temperature format for the display should be: 
<v.1> °C and not <v.1>°C  (with a white space between <v.1> and °C !!!

**Comment by duarteveiga** [comment]
Hi,

This was the actual issue, the space between the value and the unit of measurement within Loxone's configuration! Now Home Assistant correctly plots line history graphs instead of an horizontal bar chart.

Thanks!
