### ISSUE TITLE
Dimmer entities are not detected anymore

### ISSUE THREAD

**Issue by Govarowski** [JoDehli/PyLoxone#47]
Hello!

First off, thanks for building this great integration!
I'm having some issues with the latest version where "dimmer" entities can no longer be controlled.
I used to just control the "actuator" to turn on/off individual lights attached to the lightingcontroller without a problem.

Previous version I was using was 2.8 I think then it was working fine, now running your latest version.
I saw there is a known issue related to the dimmer, not sure if this is the same rootcause?

Kind regards!

**Comment by JoDehli** [comment]
I expected problems with the new light controller. Because I redesigned it completely. Do you use the dimmer alone or in the the lightcontroller. Can you provide informations how you configured the light controller? I can only test it when I have the same outputs defined as in your configuration. 

You know that you can suppress all subcontrols from the light controller and it creates only one device for one light controller. The dimmer and master color or brightness should be controllable via this main light.

**Comment by MrIncredible007** [comment]
Hi Joachim! I think I'm having the same problem.

This lightcontroller config generates a dimmer entity in home assistant for AQ1 (spots).
![lightcontroller-config](https://user-images.githubusercontent.com/24842474/105962756-7b8f4780-6080-11eb-8951-e819e1e95d8d.png)

The dim level and on/off state don't get updated anymore. I'm able to control the light with it, but the state keeps resetting to 0% / off.
![dimmer-hass](https://user-images.githubusercontent.com/24842474/105962907-a7123200-6080-11eb-8c4d-9dd4bcc1175a.png)

**Comment by JoDehli** [comment]
@MrIncredible007  Thanks for your help. Try the new release. Hope this time it works.

@Govarowski also try the new release from the Hacs Repo

**Comment by Huweh** [comment]
@JoDehli Thanks for the release/change! The dimmer works now and is not in a faulty state. I was checking for a fix but just have seen your push. Thanks you!

**Comment by MrIncredible007** [comment]
@JoDehli Thanks for the quick response! The dimmer works as expected.

**Comment by Govarowski** [comment]
Hello JoDehli,
I found the solution for my problem, was a bit different than the solution for Huweh.
I just had to tick the box "Generate subcontrols for lightcontrolerV2" not sure if it's a new addition to the integration? 
Just reporting in case someone else experiences the same!
Thanks again for this great integration, it has replaced my Loxone app!!

**Comment by JoDehli** [comment]
@Govarowski yes this is a new feature. It was requested from some users.
