### ISSUE TITLE
Setup failed for loxone: Integration not found

### ISSUE THREAD

**Issue by DSew20** [JoDehli/PyLoxone#50]
Hello,

I am trying to set-up PyLoxone in HA (under ProxMox) following the manual process.  But, when I restart, I get the error:

Setup failed for loxone: Integration not found
Logger: homeassistant.setup
Source: setup.py:138

Any idea how to fix this issue?

**Comment by JoDehli** [comment]
Do you install it with a normal Linux OS on proxmox with home assistant manual Installation? Ot is it a hassio install over docker. 

I used proxmox before with manual install and it worked the same as on my main machine. 

If you have a env install you must be sure that it uses the env environment when it starts. And the custom components folder must be in same folder where your configs are.

**Comment by DSew20** [comment]
Thank you for the reply.  I found the issue.  To get this working the 'www' and 'custom_components' folders need to be located directly under config.  I had them in the folder that was extracted from the zip.

After fixing this and a reboot, seems to be working.

A quick tweak to the manual guidance and others will not have the same issue.

Thank you for your great work on this.
