### ISSUE TITLE
Loxone Light Controler V2 - Scenes disappearing

### ISSUE THREAD

**Issue by ThePhantom79** [JoDehli/PyLoxone#51]
The scenes from my Light Controller V2 are disappearing all the time. Sometimes - after creating them, and after reboot the HA server and Loxne, they are there for some minutes, but after that, they disappear. 
I rebooted several times, I deletes PyLoxone, but nothing helps. 
The box for creating scenes in the (GUI) configuration is set - also on config file the varibale   generate_scenes is set to true.

**Comment by JoDehli** [comment]
Can you edit the source code for testing? 

If so can you increase the delay of the scene generation in the scene.py:

[This Line hier](https://github.com/JoDehli/PyLoxone/blob/master/custom_components/loxone/scene.py#L49)

Increase it from 0.5 to maybe 2.0 or 3.0.

**Comment by JoDehli** [comment]
I could reproduce it on a very slow raspberry pi. I increased the value to 10 and I could restart without problems. Maybe this fixes this issue. I try to put this value in the config menu so that each user can edit this value if similar problems occur.

**Comment by ThePhantom79** [comment]
I tested it, and it works for me (with a value of 3).
I dont think, thats a problem with the power of the HA-Installation - my installation is on VM in an powerfull ESXi-Server. Maybe the Miniserver itself is to slow.

**Comment by JoDehli** [comment]
Hmmm I do not had any problems on my Dev machine and it is an old pc :-) 

It is hard to debug for me. I try to make the value configurable until I have a better solution.

**Comment by ThePhantom79** [comment]
Fo me its fine - itr worked and you can close the issue.
Thanks!

**Comment by johny-mnemonic** [comment]
I seem to have the same issue and I would bet it is not your plugin, but my slow Miniserver.
I have pretty big program, that would deserve some clean-up ;-), and my Miniserver is pretty slow thanks to that. Raising the time for scene generation to 5.0 fixed it for me.
I fist enabled debug, but  the only interesting thing I found was, that your plugin is downloading all the event logs from Loxone, which in my case is pretty big part of the debug log output and feels superfluous...

Regardless, it seems like making this timeout configurable or trying the scene generation again after some time, when it fails during startup, would be great.

**Comment by JoDehli** [comment]
@johny-mnemonic I released a new version where you can define the delay for the scene generation.: 
![image](https://user-images.githubusercontent.com/32484282/108624800-6de29d00-7447-11eb-92de-92c79fad4593.png)


For the big log. The Loxone sends every device and all information once a client (here pyloxone or the android/ios app) connects. You can disable the log but it will sent it anyways.

**Comment by johny-mnemonic** [comment]
Thanks a lot @JoDehli !
I didn't know that it sends everything all the time. That at least partly explains, why the app start is so slow I guess...
