### ISSUE TITLE
Manual installation: Can't find Pyloxone under integrations.

### ISSUE THREAD

**Issue by Rubeast** [JoDehli/PyLoxone#52]
I followed the steps, but for step 4 I can't seem to find Pyloxone under integrations..

**Comment by JoDehli** [comment]
![image](https://user-images.githubusercontent.com/32484282/109410985-02488480-799f-11eb-8cb9-4ad31e1bd8a3.png)

Have you copied the loxone folder from the zip to the custom_components folder like in the screenshot? Have you restart home assistant?

**Comment by Rubeast** [comment]
Yes I did everything like you described.
But I left it alone after and now it shows up under integrations.
Strange. I probably needed to wait longer for HA to load after the restart.

Another question, since I'm new to HA. How are updates handled for PyLoxone? Do I manually need to replace the files with each update?

**Comment by JoDehli** [comment]
You can try hacs. It it is the best way to install additional components to home assistant. There you can update the components with one click. Otherwise you have to copy it over like on the first install.
