### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by zhooley** [JoDehli/PyLoxone#54]
Hi!

I try a loxone binding in Home Assistan on a Synology docker.
A fill the ip, port, username and password and i get this error in log:
Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:785
First occurred: 2:47:28 (1 occurrences)
Last logged: 2:47:28

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/loxone/__init__.py", line 131, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 128, in async_setup
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 347, in async_init
    res = await self.acquire_token()
  File "/config/custom_components/loxone/api.py", line 541, in acquire_token
    key_and_salt.read_user_salt_responce(message)
  File "/config/custom_components/loxone/api.py", line 785, in read_user_salt_responce
    self.key = value['key']
TypeError: string indices must be integers

Please help me!
Thank You

**Comment by JoDehli** [comment]
Have you tried it on a normal installation without docker?

**Comment by zhooley** [comment]
I haven't tried, I'm not that professional :)

Joachim ***@***.***> ezt írta (időpont: 2021. márc. 16., K,
10:13):

**Comment by JoDehli** [comment]
Have you got access thru the official loxone app?

**Comment by zhooley** [comment]
Yes, but my loxone port is 80 not 8080.

I also tried with wrong password, and then it was in the log:
ERROR (MainThread) [custom_components.loxone.miniserver] Error connecting to loxone miniserver.

I don't know what the problem might be

**Comment by JoDehli** [comment]
@zhooley I started a little gui program to check to connection. https://github.com/JoDehli/LoxGui
What OS do you use? Windows? I need to pack it as executable first. 
Then you can test it. If this program can access and you use the same in the synology then it is a problem with the synology 
docker environment. I let you know when and where you can download the executable.

**Comment by zhooley** [comment]
I use Windows.


Joachim ***@***.***> ezt írta (időpont: 2021. márc. 21., V,
10:42):

**Comment by JoDehli** [comment]
@zhooley here you can try this little gui for the connection to the loxone. 

https://github.com/JoDehli/LoxGui/releases/tag/v0.1

Download the zip and unpack it and start the exe file. It is so big because I packed the whole python installtion into
this file. If you can you can only download the source and install the python and the needed packages
by yourself.

**Comment by zhooley** [comment]
A get the same error:

[image: image.png]

Joachim ***@***.***> ezt írta (időpont: 2021. márc. 21., V,
19:33):

**Comment by zhooley** [comment]
I have gen1 loxone miniserver.

Here is the error:

Try to connect...
Got Config from Loxone. Port and Host ok.
Traceback (most recent call last):
  File "main.py", line 87, in connect_to_loxone
  File "C:\Users\Joachim\Desktop\gui\LoxGui\api.py", line 364, in async_init
  File "C:\Users\Joachim\Desktop\gui\LoxGui\api.py", line 559, in acquire_token
  File "C:\Users\Joachim\Desktop\gui\LoxGui\api.py", line 803, in read_user_salt_responce
TypeError: string indices must be integers

**Comment by JoDehli** [comment]
Ok this good. Because it is something with your credentials not with the synology. 

can you paste one line from the config data tab:
the miniserver type:

"miniserverType": 0,

What type do you have?

**Comment by zhooley** [comment]
"miniserverType": 0,

Joachim ***@***.***> ezt írta (időpont: 2021. márc. 22., H,
8:20):

**Comment by zhooley** [comment]
This program have joined to miniserver because I see my devices in the
config data :)

Zoltán Kovács ***@***.***> ezt írta (időpont: 2021.
márc. 22., H, 8:26):

**Comment by JoDehli** [comment]
can you sent me the file which was generated in the same folder of the Main.exe. 
The lox_token.cfg but by EMAIL at joachim.dehli@gmail.com
