### ISSUE TITLE
no communication 

### ISSUE THREAD

**Issue by vicfalls** [JoDehli/PyLoxone#56]
Hi @JoDehli 

since I updated your PiLoxone to version 0.3.3 the communication between HASS and Loxone doesn't work.
could you be so kind and send me the link to version 0.3.2? 
It worked fine with the old version.

Thanks
Vic

**Comment by JoDehli** [comment]
Can you post the eeoro message?

**Comment by vicfalls** [comment]
sorry, here we go

Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:362 
First occurred: 16:11:23 (1 occurrences) 
Last logged: 16:11:23

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/loxone/__init__.py", line 131, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 111, in async_setup
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 362, in async_init
    _ = await self._ws.recv()
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), reason = normally closed

**Comment by JoDehli** [comment]
Maybe I know what's the problem but I can not fix it today. Maybe tomorrow. You can go back in hacs to the version before or?

**Comment by JoDehli** [comment]
You can go to reinstall and then you can choose the version before.

**Comment by vicfalls** [comment]
Thanks, didn't know that it is possible to downgrade versions via reinstall...

**Comment by JoDehli** [comment]
I try to fix it and them maybe you can try it again. It is an python 3.8 issue. I have python 3.9.

**Comment by JoDehli** [comment]
@vicfalls can you try it again by reinstall the 0.3.3 version? Can you give me feedback if it worked?

**Comment by vicfalls** [comment]
Hi Joachim, works fine.... Vielen Dank
