### ISSUE TITLE
Pyloxone not at integration list

### ISSUE THREAD

**Issue by noveriaonline** [JoDehli/PyLoxone#57]
Hello,
I have new installation of HASS 64bit on Pi4. HACS installed, PyLoxone repository added, server restarted... but still I can not see Pyloxone in configuration > add integration list.

How to solve it please?

**Comment by JoDehli** [comment]
Can you paste the URL which you enter in hacs?

**Comment by noveriaonline** [comment]
This one from manual:

https://github.com/JoDehli/PyLoxone

Dne ne 28. bře 2021 18:46 uživatel Joachim ***@***.***>
napsal:

**Comment by JoDehli** [comment]
It should work but you can also try this one: https://github.com/JoDehli/PyLoxone.git
I tried it with both urls. Do you see it in the hacs repro section?

**Comment by noveriaonline** [comment]
Yes, I see in HACS > Integrations  Python Loxone binding... But not in
Configuration  > Integrations > Add list

New link doesnt help :/

Dne ne 28. bře 2021 20:38 uživatel Joachim ***@***.***>
napsal:

**Comment by JoDehli** [comment]
Install samba addon and look if pyloxone is installed. If not you can try to install it manually.

**Comment by noveriaonline** [comment]
Hello, I dont sleep at night at Now it works! Issue was MacOs and browser
cache. Cache must be deleted after every new intg. is added.

Thanks for you support.

Dne út 30. bře 2021 8:00 uživatel Joachim ***@***.***> napsal:
