### ISSUE TITLE
Improve sensor creation

### ISSUE THREAD

**Issue by Juxz** [JoDehli/PyLoxone#60]
We can see in sensor.py that all sensors from Loxone are created equally:
```
   for sensor in get_all_analog_info(loxconfig):
        sensor.update({'typ': 'analog',
                       'room': get_room_name_from_room_uuid(loxconfig, sensor.get('room', '')),
                       'cat': get_cat_name_from_cat_uuid(loxconfig, sensor.get('cat', ''))})

        sensors.append(Loxonesensor(**sensor))

    for sensor in get_all_digital_info(loxconfig):
        sensor.update({'typ': 'digital',
                       'room': get_room_name_from_room_uuid(loxconfig, sensor.get('room', '')),
                       'cat': get_cat_name_from_cat_uuid(loxconfig, sensor.get('cat', ''))})
        sensors.append(Loxonesensor(**sensor))

    for sensor in get_all(loxconfig, "TextInput"):
        sensor.update({'room': get_room_name_from_room_uuid(loxconfig, sensor.get('room', '')),
                       'cat': get_cat_name_from_cat_uuid(loxconfig, sensor.get('cat', ''))})
        sensors.append(Loxonesensor(**sensor))
```

That would be great if you could leverage Home Assistant model, as described here:
https://www.home-assistant.io/integrations/sensor/
https://www.home-assistant.io/integrations/binary_sensor/

So instead of creating a "sensor" entity with a "device_typ=analog_sensor or digital_sensor", you could instantiate either a sensor or a binary_sensor in HASS.
The cherry on the cake would be to populate the "device_class" attribute based on Loxone's config.

**Comment by JoDehli** [comment]
Which device class from loxone? I never seen a device class on a sensor. Of course you could guess it from the unit but I know no other attribute or device class definition.

**Comment by Juxz** [comment]
I was about to write an idea using the "category" attribute, but it's not reliable due to multiple languages and custom implementations on the loxone side. Eventually, the category-to-device_class mapping table could be a user setting?

But units would be already a good start indeed. Then each of us can "customize" the device_class attributes according to the situation (note: we cannot customize an entity type from sensor to binary_sensor, we can only customize the attributes and this is the reason why this ticket exists ;)

**Comment by robinheymans** [comment]
I was just about to open a ticket and found this one. It would indeed be great if Loxone's digital sensors would be defined as binary_sebsor in Home Assistant!

**Comment by tom301080** [comment]
I tried to make some sensors also available in the iOS Home APP but the Homekit integration only forwards my temperature sensors from loxone. All digital sensors like the motion and door sensors etc are not visible. My hue motion sensors work but they are type binary_sensor.

**Comment by tom301080** [comment]
Just wanted to check again on this topic? Any plans here? Wouldn't it be possible to set all sensor with "type": "InfoOnlyDigital" as HA binary sensors?

**Comment by JoDehli** [comment]
Difficult to say if it makes problems on other installations. Can I install homekit myself? I have a MacBook Pro but I never use it :-) i do not like the Mac OS or iPhone OS but maybe I can install it to test it. I never used homekit. I think it is a apple protocol.

**Comment by tom301080** [comment]
Yes, homekit is an apple protocol. There is the HOME app on macOS available but unfortunately you need an iOS device to set it up so no luck here :-( Something I question myself is why HomeAssistant have splitted sensors into sensors and binary_sensors a while ago. I assume they haven't done this just for homekit but also for standard HA features?

https://www.home-assistant.io/integrations/sensor/
https://www.home-assistant.io/integrations/binary_sensor/

Do you have in infos on this? On their sensors description page they only mentioned analog sensors but no digital...

**Comment by JoDehli** [comment]
@tom301080
Can you try this source? 
[loxone.zip](https://github.com/JoDehli/PyLoxone/files/9078749/loxone.zip)

Extract everything into the folder custom_components -> loxone. 

Maybe make a zip copy of you existing folder. 

I implemented the digital info sensors as binary sensors. For my small installation it worked but I can not estimate what problems occur on other installations.

**Comment by tom301080** [comment]
@JoDehli Just checked it, WORKS for me. MANY THANKS! Will this be part of future updates that I can still use HACS?

**Comment by JoDehli** [comment]
I have a error message which I get rid of it. And I think I can implement like this. The question would be of if I make a config option to keep the old generation. Maybe a option like:

1 old generation like it is
2 only new generation
3 generate both  ( then you have 2 sensor entities for one loxone sensor)

Or o use only the new version.

**Comment by tom301080** [comment]
Option might be the most flexible way but I guess using the binary_sensor version will be the most HA compliant.

**Comment by JoDehli** [comment]
@Juxz and @robinheymans can you also check the changes for the binary sensor in the zip file which I uploaded?

**Comment by JoDehli** [comment]
@Juxz 
@robinheymans 
@tom301080 
@arjenvrh 

I published a pre-release with the mentioned changes for digital sensor creation. May you can look and report any issues before I mark it as stable.

**Comment by robinheymans** [comment]
@JoDehli I'm currently on holiday and won't be back home until the end of augustus. I'll be happy to test the change when I'm back! Many thanks

**Comment by tom301080** [comment]
@JoDehli I installed the latest version with HACS and its working for me THANKS again for your great work!

**Comment by Juxz** [comment]
Works great! Thanks @JoDehli

**Comment by JoDehli** [comment]
I think it works as expected.
