### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by vicfalls** [JoDehli/PyLoxone#62]
Hi @JoDehli,

by installing the new PyLoxone Version 0.3.4, I get following error massage:

Logger: homeassistant
Source: custom_components/loxone/sensor.py:274 
First occurred: 5:52:38 (4 occurrences) 
Last logged: 5:52:38

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/loxone/sensor.py", line 274, in state
    return self._format % float(self._state)
TypeError: not all arguments converted during string formatting

Cheers Vic

**Comment by JoDehli** [comment]
@vicfalls This is because I changed the formating which was a pull request https://github.com/JoDehli/PyLoxone/pull/61

What format string do you use for this sensor in loxone? Does all the other sensors work?

**Comment by JoDehli** [comment]
@vicfalls can you check the dev branch?

**Comment by vicfalls** [comment]
@JoDehli, sorry that I haven't respond earlier to your request. I did't have time to do so. The dev branch version works perfect.
