### ISSUE TITLE
Separating API into its own module

### ISSUE THREAD

**Issue by lawrenceakka** [JoDehli/PyLoxone#66]
Hi,

Thank you for the great HA component! 

I am interested in separating out the code which communicates with the Loxone API into its own standalone module. That would be one step towards (at some stage, maybe in the far future!) integrating the component into HA itself, and also allowing people to use it for systems other than HA. I have it working already, with minimal changes. 

Is that something you would be interested in?  If so, I will clean it up and submit a pull request.

**Comment by JoDehli** [comment]
I already started it but I had no time to finish it. I wanted to rewrite it completely because the code is not very clean. But of course this would be the first step. My plan was to create a pip package and keep it completely separate. Maybe with support of mqtt for use in other projects.  

Of course it would be really create if I can get support for the binding. I made a separate branch: https://github.com/JoDehli/PyLoxone/tree/api_separation

Feel free to submit a pull request. If you have experience to create a pip package we can do it to together. But I think it is 
a long way to get it in the home assistant official repo. But lets try it. 

Thanks for your help!!!

**Comment by lawrenceakka** [comment]
That’s great. A package is pretty easy using something like [Poetry](https://python-poetry.org), but I can certainly help with that.

I think that the best/easiest way to do all this is:

1) You need to get an account at https://pypi.org

2) You need to decide on the name for the API package which is not already taken! (pyloxone-api, loxoneapi ???)

3) You need to set up a new empty GitHub repository for the new api module. I think it is probably possible to use the existing PyLoxone repo for both the API and the HA code, but its certainly not straightforward, and having separate repos will make it easier to track bugs/accept contributions etc separately.

4) I can then create a pull request to add my API code to the new API repo, and we can then upload it as a package to PyPI

5) When that is working, we can start to remove the existing API code from PyLoxone, and make it depend on the new API package instead

6) PROFIT


Does that sound OK?

**Comment by JoDehli** [comment]
Sounds good. I have already an account on PyPi. I made a repo for the loxone api: https://github.com/JoDehli/pyloxone-api

I have started already based on the https://github.com/escalate/python-loxone-ws-client source code. 
It is based on autobahn which makes the connection handling a bit easier. 

Here is the source code. Maybe want to look into the code. 
[started.zip](https://github.com/JoDehli/PyLoxone/files/6477514/started.zip)

**Comment by JoDehli** [comment]
Can I give you access to the repo? Do you want to help as a co-developer?

**Comment by lawrenceakka** [comment]
I have submitted a PR in the pyloxone-api repo as the first step to creating a package. The next step will be to make a few changes here, to PyLoxone.

I am very happy to have access to the repo if you would like me to have it, but I should say that I won't have a huge amount of time. But if I can help, I will.

**Comment by JoDehli** [comment]
@lawrenceakka thanks for all the work you have done on the https://github.com/JoDehli/pyloxone-api repo. 

My suggestion now would be to create a pip version and integrate it into the branch api_seperation. What do you mean?

**Comment by JoDehli** [comment]
@lawrenceakka do you have discord? maybe we can chat over discord?

**Comment by JoDehli** [comment]
I made my first discord server :-) Maybe you can join. https://discord.gg/gCWMxcPx

**Comment by JoDehli** [comment]
@lawrenceakka I also released the first pip package. Thanks for your awesome work. It was only a publish command and everything worked perfect. I also updated the api_separation branch with the requirements to pyloxone-api. So it should now install everything on the fly.
