### ISSUE TITLE
Light controller with multiple outputs

### ISSUE THREAD

**Issue by somm15** [JoDehli/PyLoxone#7]
You are doing an amazing work over the past weeks.
I can finally use home assistant and homekit.
Thank you !

An because I can't create an issue just to say "thank you", I have a small feature request.
I use light controller v2 with multiple outputs. It would be cool if you could add them as independent "lights" as well (and if possible dimmable light when applicable).

**Comment by JoDehli** [comment]
Thank very much for your feedback. 

Of course I can help you but first I need to understand it. Because I do not use any of
the light features in Loxone. I have only shutters in my installation. 

Can you send me a screenshot from your loxone config where I can see how to connect the 
lights? Then I can look how we can integrate it.

**Comment by JoDehli** [comment]
Ok I got it! I understand what you mean. Great idea. What a shame that I have no automated lights in my house :-)

I will look what I can do. Should be no big deal.

**Comment by somm15** [comment]
Great. I can actually try as well when I'm done with the Viessmann integration.

Basically, I use Light Controller v2 with multiple output.
In the definition of the block, they can be on/off or dimmed. 

Amazing that you developed that without using the light components at home :-)

**Comment by JoDehli** [comment]
Try the dev branch. I added dimmers for the light controller. Only for the first try. 
Can you try it? Is this what you want?

**Comment by somm15** [comment]
For the dimming part this is exactly what I was looking for.
I have one Light controller v2 with 2 circuit in my living room and they now both appear as individual dimmer while the controller is still represented as an on/off light. Perfect. 

I also have 2 circuits in my kitchen (2 output of light controller v2) but they are not dimmed. It would be great to also have them as individual on/off lights while keeping the on off the the controller as well.

**Comment by JoDehli** [comment]
I also included the RGB outputs on the light controller. Maybe you can try it out. I have not lights to test it. : -)

Maybe I buy some Ikea Tradfri lights to test. 
It is in the dev branch.
