### ISSUE TITLE
Removing entities correctly

### ISSUE THREAD

**Issue by tanker11** [JoDehli/PyLoxone#76]
Hello,

I created a totally new project in Loxone and connected successfully, but the old entities are still there in HA.
What is the correct method to get rid of the old entities?
Do I need to remove the integration and install again, or delete some files?

Thanks.

**Comment by JoDehli** [comment]
this is a ha question not specific to loxone. you can delete all entities via the integrations -> entities tab.

**Comment by tanker11** [comment]
OK, thanks, I was not sure if there was any PyLoxone related thing to do.


Joachim ***@***.***> ezt írta (időpont: 2021. jún. 11., P,
10:36):

**Comment by tanker11** [comment]
Closed
