### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by chrisvd183** [JoDehli/PyLoxone#77]
Hello ,
can somebody help me ?

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:337
Integration: PyLoxone (documentation, issues)
First occurred: 23:02:46 (1 occurrences)
Last logged: 23:02:46

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websockets/http.py", line 139, in read_response
    status_line = await read_line(stream)
  File "/usr/local/lib/python3.8/site-packages/websockets/http.py", line 219, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websockets/client.py", line 101, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/local/lib/python3.8/site-packages/websockets/http.py", line 141, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/loxone/__init__.py", line 132, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 111, in async_setup
    res = await self.api.async_init()
  File "/config/custom_components/loxone/api.py", line 337, in async_init
    self._ws = await wslib.connect("{}/ws/rfc6455".format(new_url), timeout=TIMEOUT)
  File "/usr/local/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.8/site-packages/websockets/client.py", line 290, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/usr/local/lib/python3.8/site-packages/websockets/client.py", line 103, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response

**Comment by JoDehli** [comment]
Can you please give more details! OS version? HA version? With this log I can not see very much. Did you read the already closed issues?

**Comment by chrisvd183** [comment]
Hello JoDehli, thanks for the respons. Sorry for the bad respons :-). I was having a bad time and didn't know how to add more comments to the ticket. But I have solved the problem by installing the module pyscript into the HACS. From then on it didn't give a message anymore. But i also discover that the user must have admin rights on the loxone. From then it did create lightcontroller v2 and blinds. I was just not able to see the powermeter also installed on the loxone. We have not done all installations yet like fire alarm and so I hope we can see them also. Firmware on loxone was : 12.0.2.24 . today we did install 12.1.6.17 on the miniserver (gen2)

![image](https://user-images.githubusercontent.com/66533316/122740875-b2126c80-d284-11eb-83ae-65baf5f3e14f.png)

Information on HA:

## System Health

version | core-2021.6.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Brussels

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4890
Installed Version | 1.13.1
Stage | running
Available Repositories | 847
Installed Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.3
docker_version | 20.10.6
disk_total | 28.6 GB
disk_used | 4.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.1), SSH & Web Terminal (8.2.4), Visual Studio Code (3.4.1), Google Assistant SDK (2.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 8
views | 9
mode | storage

</details>

**Comment by JoDehli** [comment]
You can look under the read me page what components are supported. Fire alarm and also the Powermeter is not supported. I added some features from users that asked me. But for myself I did not need it. Because I have only blinds and nothing more. 
 But you maybe can get unsupported components to work by adding a custom sensor. You can also see a example of the main github site.
