### ISSUE TITLE
Error setting up entry PyLoxone for loxone

### ISSUE THREAD

**Issue by DSew20** [JoDehli/PyLoxone#78]
Hello,

For some reason, PyLoxone has stopped working and is giving this error:

`Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/loxone/__init__.py", line 122, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 73, in getJson
    _ = eval(_)
  File "<string>", line 1, in <module>
NameError: name 'false' is not defined`

I'm running Home Assistant core-2021.6.6 and supervisor-2021.06.03.

Was working ok a day or so ago.  Just stopped working and wont load.

Any pointers re what to do / how to get PyLoxone to load and run?

**Comment by JoDehli** [comment]
Have you updated your Firmware?

**Comment by DSew20** [comment]
Ah.  Yes, I have the newest firmware on the Miniserver.

How does one update PyLoxone?  Can this be done through Home Assistant or is this an FTP and copy process?

**Comment by DSew20** [comment]
To answer my own question - I replaced the files per the Manual installation process, and all seems well again:

- Download the zip file and extract all files.
- Copy the custom_components and www folder in the same folder where your configuration.yaml is located
- Restart Home-Assitant

**Comment by JoDehli** [comment]
@DSew20 you can install via hacs. If you do not know what hacs is search for it. It is perfect for installing components via GUI without manual extracting and downloading. There you can find thousands of components like mine. Really good.
