### ISSUE TITLE
Trigger next "mood"

### ISSUE THREAD

**Issue by rnovacek** [JoDehli/PyLoxone#79]
Is it possible to switch to a next "mood"? Similar to what happen when you click the middle button of Loxone Touch light switch.

My use case is to use non-loxone button (zigbee using zigbee2mqtt) as additional light switch.

**Comment by JoDehli** [comment]
You can implement it yourself like I showed herer:

https://github.com/JoDehli/PyLoxone#example-2-with-a-updownanalog

**Comment by JoDehli** [comment]
@rnovacek 
You can do it with a service call on the uuid from the lightcontroller like this:

![image](https://user-images.githubusercontent.com/32484282/125165038-7e48a980-e195-11eb-8a4d-f6c5703560a8.png)

If this works for your light controller you can combine this service with a script which you can trigger from the zigbee device.

Can you close the issue if it works?

**Comment by rnovacek** [comment]
Awesome, I'll give it a try this week and will report back.

**Comment by rnovacek** [comment]
It works! Thank you very much. This automation does the trick for me:

![image](https://user-images.githubusercontent.com/618886/125354666-5c515180-e364-11eb-85b1-fd91209f7222.png)

For the reference, all I had to do is to open `http://<loxone-ip>:<port>/data/LoxAPP3.json`, find the room by name in `rooms` top level object, use the `uuid` of that room to find `LightControllerV2` with `room` equal to that `uuid` and use the `uuid` of `LightControllerV2` in the action. And `value: plus` means next mood.

Shall I open a PR to add this comment to the readme?

**Comment by JoDehli** [comment]
@rnovacek If you want you can add your problem and your solution as a 3rd example to the main page with a PR.
