### ISSUE TITLE
Loxone to HA

### ISSUE THREAD

**Issue by di3t0** [JoDehli/PyLoxone#8]
It's possible to send commands from Loxone to HA over Virtual Out? How?

**Comment by JoDehli** [comment]
What exatly should be sent? You can create a Marker and you can observe the value in ha. Therefore you can react on a value change.

**Comment by di3t0** [comment]
I want to control the Xiaomi Philips Hue Downlight with the Touch Pure. The lights are only controllable via HA. https://www.home-assistant.io/integrations/light.xiaomi_miio/

**Comment by JoDehli** [comment]
Ok I see. Is you main system loxone or HA? 

 I would first connect the Touch Pure to a light controller output. The light controller is 
supported by me binding. You should then see the light in HA and you should be able
to turn on and of the light by pressing the Touch Pure.

Then you can make a automation from the loxone controlled light in HA to the light from
the xiaomi philips light and vice versa.

If you have accomplished that you can go to the rgb stuff. 

I can integrate the Touch Pure in my binding then you have the touch pure direct in HA without 
go over the light controller.

**Comment by di3t0** [comment]
My main system is Loxone. I'll try it as you described it. I hope it works :-)

**Comment by JoDehli** [comment]
@hallerdavid can you send a part of your loxone config (of course with fake uuid) so that I see how they look. I do not  have any touch switches to test

**Comment by hallerdavid** [comment]
Can I send you a direct message somewhere? Then I don't have to delete so much data 😁

**Comment by JoDehli** [comment]
@hallerdavid Do you use discord? If yes send me your username and I will send you a message.
