### ISSUE TITLE
Sensor temperature missing unit of measure 

### ISSUE THREAD

**Issue by elRadix** [JoDehli/PyLoxone#80]
I am running the latest pyloxone with latest firmware 12.1.6.17 and for the temperature sensor the unit of measure is missing hence its not showing a graph in home assistant
no issues with the humidity sensor. 

see screenshot below of temperature sensor 

![SmartSelect_20210710-160250_Home Assistant](https://user-images.githubusercontent.com/6258894/125165817-e64cbf00-e198-11eb-9bd2-666743069946.jpg)
![Screenshot_20210710-160359_Home Assistant](https://user-images.githubusercontent.com/6258894/125165818-e6e55580-e198-11eb-8600-027fbbdf7e1e.png)

**Comment by JoDehli** [comment]
@elRadix 
Have you setup a unit in the loxone for the sensor like you did it with the hum sensor? 
you must leave a blank for the unit something like %.2f C°

**Comment by elRadix** [comment]
@JoDehli it is new brand new installation, all settings are default (<v.1>) for the temperature sensors, the humidity sensor is also set by default to  <v>%
I have changed these temperature units to <v.2>C° and its working now.

had to delete home assistant DB to get he new graphs direclty visible
