### ISSUE TITLE
Units of analog sensor

### ISSUE THREAD

**Issue by Dohnalradek** [JoDehli/PyLoxone#89]
I have a sensor for actual energy consumption (electricity) that show me i.e. 0,56kW (in loxone).
But in HA, I would like to have 560W. Is there any way to do this without creating new template sensor in HA?
I try to set "units" in loxone to <v.3 * 1000>W but it doesnt work - in HA it display 0,56<v.3*1000>W)...

**Comment by JoDehli** [comment]
You have two options. You can convert it in loxone but not using the format string. There are other options. You find a lot of examples on the web. 

Or you convert it on Homeassistant. For example with a template senor https://www.home-assistant.io/integrations/template/

I think this is a general problem no pyloxone issue.
