### ISSUE TITLE
PyLoxone on VirtualBox

### ISSUE THREAD

**Issue by Nico0W** [JoDehli/PyLoxone#94]
Hello, 

I'm using Home Assistant on a VirtualBox and it's impossible for me to add PyLoxone in the Integrations. 

According to the ReadMe page, I should put the custom_components and www folder in the same folder where configuration.yaml is located. Right ? It doesn't work for me. 
The ww folder should really be in the folder of the configuration.yaml and not in the loxone one? I've tried different ways but doens't work too.

Can you help me ?
![Capture](https://user-images.githubusercontent.com/96498657/147111200-e1b75943-2ed4-4371-949a-d90aba4d5f8b.JPG)

Thanks in advance.

**Comment by JoDehli** [comment]
Have you tried hacs as a installation option? 
Is it a python virtual environment installtion or is it a hassio installation.
