### ISSUE TITLE
Binary status 'on' vs 'On'

### ISSUE THREAD

**Issue by tanker11** [JoDehli/PyLoxone#95]
Hello,

I observed a strange behavior on the reported binary sensors state.
One of them says 'On' whilst others state is 'on'.
Creating conditions against it are confused by the inconsistent status string.
What could be the reason?

Example:
![image](https://user-images.githubusercontent.com/32165691/149307569-8e94c757-4e95-4548-84b6-9ac1a01ec07a.png)

HA version: 2021.12.9
PyLoxone version: 0.3.8

Thanks in advance

**Comment by JoDehli** [comment]
@tanker11 
I try to reproduce it. Are both sensors from the exact type? I mean are both from the same type on the loxone miniserver
or is there any different?

**Comment by tanker11** [comment]
Both of them are Memory flags, set to 'Used', but I found a difference:
sensor.heating_or_hmv_running related one has the default Display property
in Loxone config:
[image: image.png]
sensor.heater_running related one is modified due to displaying
requirements under Loxone UI:
[image: image.png]

And actually, this is what I did change recently.
So it seems, in this latter case the status string is on/off whilst in the
default case it is On/Off.

Hope this helps.

Joachim D. ***@***.***> ezt írta (időpont: 2022. jan. 13.,
Cs, 20:24):

**Comment by JoDehli** [comment]
I looked in the code. I use the on or off state when no status text is sent by the miniserver. Otherwise I use the text from the loxone. You have to options.

1. Change it in the status text in the loxone 
or
2. convert it to lowercase before use it in a condition or make to conditions for example: state == "on" or state == "On"

**Comment by tanker11** [comment]
Hello,

I checked it, and it is totally understandable if I select the status message, it is sent over.
But in this case, I select the 'User defined symbol' where the status text cannot be set at all.
So would it be possible to set it the same 'On' and 'Off' to be consistent with the default status texts?

Regards,
Robert

**Comment by tanker11** [comment]
Hello,

Tried what you suggested and it now reports 'on' and 'off' for both types,
so it is consistent with HA, too.

Thanks for the work and for the great project!

Joachim D. ***@***.***> ezt írta (időpont: 2022. jan. 20.,
Cs, 16:20):
