### ISSUE TITLE
Meter Integration

### ISSUE THREAD

**Issue by Lexorius** [JoDehli/PyLoxone#96]
Hi There, 

i would like to use a integration of the energy meter from my loxone system. 

"statistic":{"frequency":8,"outputs":[{"id":0,"name":"Leistung Produktion","format":"%.3f kW","uuid":"17298973-0185-56a4-ffffdd31cf902ab5","visuType":0},{"id":1,"name":"Leistung Verbrauch","format":"%.3f kW","uuid":"17298973-0185-56a9-ffffdd31cf902ab5","visuType":0},{"id":2,"name":"Leistung Energieversorger","format":"%.3fkW","uuid":"17298973-0185-56b9-ffffdd31cf902ab5","visuType":0},{"id":3,"name":"Leistung Batterie","format":"%.3f","uuid":"17298973-0185-56ba-ffffdd31cf902ab5","visuType":0},{"id":4,"name":"Ladestand Batterie","format":"%.3f %%","uuid":"17298973-0185-56bb-ffffdd31cf902ab5","visuType":0},{"id":5,"name":"Zähler Produktion","format":"%.3f kWh","uuid":"17298973-0185-56bd-ffffdd31cf902ab5","visuType":2},{"id":6,"name":"Zähler Verbrauch","format":"%.3f kWh","uuid":"17298973-0185-56be-ffffdd31cf902ab5","visuType":2},{"id":7,"name":"Zähler Lieferung","format":"%.3f kWh","uuid":"17298973-0185-56bf-ffffdd31cf902ab5","visuType":2},{"id":8,"name":"Zähler Bezug","format":"%.3f kWh","uuid":"17298973-0185-56c0-ffffdd31cf902ab5","visuType":2}

is there a easy way to use theys sensors ?

Tryed 

  - name: "Sensor Zähler Bezug"
    platform: loxone
    uuidAction: "17298973-0185-56c0-ffffdd31cf902ab5"
    unit_of_measurement: "kWh"     

but at energy config i've just got the error  "statistics_not_defined" on the sensor.

did you need some extra information to integrate meters like this ? 

greetings Thomas

**Comment by JoDehli** [comment]
Did you use the right uuid?
Use one of the state uuid
"states": {
    "actual": "xxxxxx-0361-3b4a-xxxxx",
    "total": "xxxxxxx-0361-3b49-xxxxxxx"
}

I tested it and it works like a charm without any problem.

**Comment by Lexorius** [comment]
hi Joachim,

the Values are Right in the Diagram (when you look at the sensor values alone). i couldn't set it as a energy sensor. 

greetings thomas

**Comment by JoDehli** [comment]
Have set the device type for the sensor like in the example described?

**Comment by JoDehli** [comment]
I pushed a new update to the main branch with a improvment. Please download it and override the existing files in the
custom_components folder. 

There you have the posibility to add a state_class attribute to the custom sensor like this:

```yaml
  - platform: loxone
    name: EneryCounter
    uuidAction: "xxxxxxxxx-xxxxx-xxxxxx-xxxxxxx"
    unit_of_measurement: "kWh"
    device_class: "energy"
    state_class: "total"
```
For more infos head over to the docu page: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

In my case the sensor showed up in the statistics section.

**Comment by Lexorius** [comment]
hi,
thank you very much . it works :))

and thnx for your greate work :)

greetings from germany 

thomas
