### ISSUE TITLE
Loxone sensor for radio8 buttons

### ISSUE THREAD

**Issue by hmahans** [JoDehli/PyLoxone#97]
Hi,

I am trying to create a sensor in my yaml file for my radio buttons from loxone. But the only thing I see is condition unknown. I guess I need to add some more to the sensors? But I have no idea what. Could you point me in the right direction?

thanks in advance

![afbeelding](https://user-images.githubusercontent.com/96912029/149845560-5e85f4b0-d42b-4beb-b137-e5d75a8d757f.png)
![afbeelding](https://user-images.githubusercontent.com/96912029/149845808-b3385646-a766-4e0b-8d0b-727487484408.png)
![afbeelding](https://user-images.githubusercontent.com/96912029/149845886-fc87bdfa-dae2-484b-9bf3-46f3cd9d5e5c.png)

**Comment by JoDehli** [comment]
I do not use the radio buttons but I think you need a different uuid in the uuidAction. For more infos check the stucture file docu on https://www.loxone.com/dede/wp-content/uploads/sites/2/2021/11/1202_Structure-File.pdf

I think you need the activeOutput uuid for the state. I think you will get an integer which output is selected.

**Comment by hmahans** [comment]
Thnx the active output gives a readout from 0.0 to 8.0.
