### ISSUE TITLE
Scenes not loading

### ISSUE THREAD

**Issue by johny-mnemonic** [JoDehli/PyLoxone#98]
Lately I am having an issue with loading light scenes into HA.
Most of the time when I restart HA scenes are not loaded, so I need to restart it multiple times and hope for some luck to get them loaded.
I tried to enable full debug log with the config below, but unless I missed something, I haven't found anything pointing to a trouble with scenes:
```
  logs:
    custom_components.loxone: debug
    loxoneclient: debug
    loxoneclient.loxminiserver: debug
```
It is hard to find anything in the log due to a huge number of warnings reported in https://github.com/JoDehli/PyLoxone/issues/91, but there are two errors in the log from PyLoxone, that could be potentially related:
```
Traceback (most recent call last):
  File "/config/custom_components/loxone/__init__.py", line 241, in loxone_discovered
    await group.Group.async_create_group(
  File "/usr/src/homeassistant/homeassistant/components/group/__init__.py", line 490, in async_create_group
    group = Group(
  File "/usr/src/homeassistant/homeassistant/components/group/__init__.py", line 436, in __init__
    self._set_tracked(entity_ids)
  File "/usr/src/homeassistant/homeassistant/components/group/__init__.py", line 582, in _set_tracked
    excluded_domains = self.hass.data[REG_KEY].exclude_domains
KeyError: 'group_registry'
```
and
```
2022-02-04 03:29:45 ERROR (MainThread) [homeassistant.components.scene] Platform loxone does not generate unique IDs. ID 1071d24e-001d-67a1-ffffd7846630eb23-1 already exists - ignoring scene.osvetleni_garaz_garaz
```

Could you please have a look and advice what to try to find the root cause?

**Comment by johny-mnemonic** [comment]
Hi Joachim. Thanks for quick reply.
Unfortunately switching to master branch didn't fix the issue with scenes (but all those warnings are gone). After the HA restart, all scenes are usually still in the state where it reports this:
```
This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.
```
Is there no way to define some form of dependency between the module loading lights and the one loading scenes?
I see all modules of PyLoxone are started together:
```
2022-02-09 22:57:47 DEBUG (MainThread) [custom_components.loxone] starting loxone sensor...
2022-02-09 22:57:47 DEBUG (MainThread) [custom_components.loxone] starting loxone switch...
2022-02-09 22:57:47 DEBUG (MainThread) [custom_components.loxone] starting loxone cover...
2022-02-09 22:57:47 DEBUG (MainThread) [custom_components.loxone] starting loxone light...
2022-02-09 22:57:47 DEBUG (MainThread) [custom_components.loxone] starting loxone climate...
2022-02-09 22:57:47 DEBUG (MainThread) [custom_components.loxone] starting loxone scene...
2022-02-09 22:57:47 DEBUG (MainThread) [custom_components.loxone] starting loxone alarm_control_panel...
2022-02-09 22:57:47 INFO (MainThread) [custom_components.loxone] loxone discovered
```

The single start when scenes were loaded successfully today was different from others in that it didn't contain the above mentioned traceback (await group.Group.async_create_group) in the log.

**Comment by JoDehli** [comment]
Have you tried to increase the time for the scene generation? It is only a delay for the generation. If your system needs mor time for the light generation you have to wait longer for the scene generation. 

On my small system 3 seconds are enough. But you can try a lager number. If it works you can adjust it for you system.

**Comment by johny-mnemonic** [comment]
Yep, I did. I had it for a long time set to 10 seconds and when I started to have these issues lately, I increased it to 30.
I just increased it to 60 but two restarts since that both produced `async_create_group` error and no scenes. 

Is that error a sign that it tried to load scenes before all the lights were loaded or could it be that after this error the loading from Loxone to HA crashes and hence can't finish loading these scenes? Or simply, is this error the root cause or the victim?

**Comment by JoDehli** [comment]
I think first goal should be to make the scene generation stable again. Of course the reload of certain platforms would be nice. But I must think about to generate the scenes completely separate from light generation. It this is not possible maybe the lights can create the scenes if they load.

My biggest problem is that I have no real support or something which I can ask from the core developers from home assistant. Maybe it is a complete wrong way to deal with such problems. Loxone is very special in some cases and very different to the mindest of Homeassistent. 

But I will try to make the scene generation separately from the lights this should be the best way.

**Comment by johny-mnemonic** [comment]
OK. In case you need a tester or anything, I am happy to help.

**Comment by JoDehli** [comment]
@johny-mnemonic ok can you try again the master branch. My problem is that I can not reproduce it on my system but 
maybe I found what could cause the problem. The scenes are handled completely different in loxone all other entitites because
the names are not known for me and the binding on the start. In the json which is sent on the start there are no scenes included. They will be sent from the miniserver with one of the first messages over websocket. And when the message comes later than the scene generation the scenes will not be generated. So I tried to fix it quick and dirty. I want first know that is the problem.
Please try from maybe 3 seconds up to 15 or 20 seconds if the scenes show not up every time.

**Comment by JoDehli** [comment]
I increased also the timeout on the config exchange from 10 to 30 seconds. Maybe that gives more time for larger systems to exchange the config json.

**Comment by johny-mnemonic** [comment]
I had successfully loaded scenes in HA three times in a row (first with 60s delay, then after reading your message back to 10s delay and update from master branch) so I thought it was fixed, but it was just a coincidence unfortunately. 
Next two restarts were with no scenes, but I think I can confirm, that the `async_create_group` error is inconclusive/unrelated as I got it multiple times with the scenes loaded...

BTW: Do you have any clue what could be the root cause of that `Platform loxone does not generate unique IDs` error mentioned in the OP?

**Comment by JoDehli** [comment]
I think you should disable the scene generation. Normally the scene could be controlled by the Light Controller itself. There 
is no need to have the scene seperatly defined. I will remove it in the next releases because I makes more problems than it solves. You can make manually scenes from HA. This is more work but I think then it works without problems. 

And I do not know it but do you still use the configuration over the yaml?

**Comment by johny-mnemonic** [comment]
Oh, I didn't know I can activate scene (called effect by HA) through the Light Controller. Thanks. One is always learning :-)

It has one big downside though. When you turn the Light Controller on, it turns on all the lights connected to the Light Controller at full brightness, which I would say is the last thing you want.
I tried to search for some lovelace card that would be able to activate specific effect as "turn on" action, but so far no success. The issue is, that the effects seem to be available only after you turn the Light Controller on, not before.
When I define the scene in HA, it sort of works as it activates the correct light, but in Loxone it is visible as Manual light, instead of active scene. Only when I then press "ACTIVATE" again in HA, it activates the scene in Loxone.
I guess this is again the issue of the effects not being available in HA till the Light Controller is turned on.

Only when I directly call the service "light.turn_on" with the effect I want, it correctly activates the scene in Loxone.

Is it possible to call the "+" button of the Light Controller from HA? Ideally I would expect that activating the Light Controller would do the equivalent of pushing that "+" button. As that activates the first scene, this is usually what you want when you don't select the specific scene through the app. At least I have it that way on all the physical buttons on the walls in my house...

Regarding scene generation, I agree it makes little sense to generate scenes at each HA start/restart, but it would still be very useful to have a button or script that would generate them on demand.
At least with the issues described above I don't see a viable alternative to the scenes generated from Loxone, as manually defined scenes in HA doesn't seems to work properly with Loxone Light Controller. Maybe I am doing something wrong though, so I would be grateful if you have some example of working HA scene or any other hint how to easily activate scenes through Light Controller in HA UI.

**Comment by johny-mnemonic** [comment]
I have found a way how to easily activate Loxone scenes from HA UI.
You can create button like this:
```
type: button
action_name: ACTIVATE
name: Office - night light
icon: mdi:lightbulb-outline
tap_action:
  action: call-service
  service: light.turn_on
  service_data:
    entity_id: light.osvetleni_pracovna
    effect: "Moon"
```
So with this solved, I am ready for your scenes removal I guess ;-)

The light controller turn-on behavior is still wrong IMHO, but with the ability to activate scenes it is not a big issue for me.
