### ISSUE TITLE
sensor value formatting

### ISSUE THREAD

**Issue by gsmember** [JoDehli/PyLoxone#99]
Hi!
First, thanks for your great module.

I would like to format the output value from my custom sensor:
```
  - name: "lounge_temperature"
    platform: loxone
    uuidAction: "13647f32-01f8-502f-ffff1173fe792577"
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "total"
```

The result is a very ugly number: `22,012564 °C`

I've tried to add the parameter `value_template` the same way I used them in my other sensors. But that gives me `Invalid config for [sensor.loxone]: [value_template] is an invalid option for [sensor.loxone].`

**Comment by JoDehli** [comment]
Hi,
templating is not supported for now. You have two options first is to format it on the loxone itself so that there is no need to format it with a template. Or the second is that you make a nother template sensor for this custom sensor and hide this one.

**Comment by gsmember** [comment]
Hi, thanks for your answer. I will go ahead with the loxone-side solution.
